### ISSUE TITLE
detecting long synchronous execution with async hooks

### ISSUE THREAD

**Issue by naugtur** [nodejs/diagnostics#102]
I took the idea behind `blocked` package and rewrote to async hooks to add a stack trace pointing to the slow function. https://github.com/naugtur/blocked-at

Does anyone see any obvious issues with that approach that I might have missed?

**Comment by AndreasMadsen** [comment]
The overall approach looks fine. There are some possible optimizations regarding the stack traces, but that has nothing to do with `async_hooks`. I'm also wondering if `(0, hooks.disable)()` works.

**Comment by Qard** [comment]
Yeah, rather than a throw and catch, you could just do:

```js
var error = {}
Error.captureStackTrace(error) // adds error.stack property
```

**Comment by naugtur** [comment]
Thanks for the tips!
