### ISSUE TITLE
Regroup at Node Interactive Vancouver

### ISSUE THREAD

**Issue by danielkhan** [nodejs/diagnostics#103]
Are there any plans to hold a diagnostics meeting at the collab summit?

I think it would be a good idea to restart this WG a bit and also put together and document the work that has been done so far - like trace events.
@jasnell also added perf_hooks meanwhile and I will meet with Adrian Cole of Zipkin (Pivotal, Spring) and discuss way to add tracing hooks for vendors.
Additionally I finally want to sketch out a tracing in Node post that documents what's possible and what isn't.

Please let me know who would be there to join.

**Comment by jkrems** [comment]
Haven't heard of any plans yet but I'm definitely around.

**Comment by mhdawson** [comment]
Both myself and Sam will be there. We should ask that we have some time during the summit.  @jasnell had suggested that we should start having a post mortem/diagnostic/etc summit like they "vm summits" we've been holding.  They seem to have been a good way to keep up momentum. 

The idea was that IBM would host the fist one in Ottawa.  I've been a bit distracted by family matters and recent community activity so I've failed to set that up yet. 

I'd suggest we get some time on the agenda at the summit and at least identify interested parties and initial topics and then I can work on scheduling one for Dec/Jan (not the best time for Ottawa, but the office is close to the airport :)).

**Comment by danielkhan** [comment]
Okay as I would solely come over for the summit, if we just set an agenda there, I'd be happy to send in my proposals then and we do this remotely. I have a new role which demands a bit more time at my home base. I'm happy to meet it December though if that's the plan.

**Comment by Qard** [comment]
I'll be at NI, though I'm not all that involved in diagnostics stuff lately.

**Comment by danielkhan** [comment]
I'd be happy to see you here more often, @Qard. You know a lot.

**Comment by Qard** [comment]
I don't work in APM currently, so I don't get as much time for it these days. 😞
