### ISSUE TITLE
[trace_event] GC flags from 2016

### ISSUE THREAD

**Issue by AndreasMadsen** [nodejs/diagnostics#104]
https://github.com/v8/v8/wiki/Tracing-V8 contains some flags that prints stack and GC information. The flags appear to be from 2016, I tried to run

```
node
  --trace-events-enabled
  --track_gc_object_stats
  --noincremental-marking
  --trace-event-categories disabled-by-default.v8.gc_stats,disabled-by-default-v8.runtime_stats,v8,node`
 file.js
```

but it doesn't contain the output. Is there a way to get the output with the current `trace_event` implementation?

**Comment by matthewloring** [comment]
I'm not sure what the current state of those flags/categories are. Maybe @lpy or @fmeawad know.

**Comment by lpy** [comment]
The tracing wiki is up-to-date, and the tracing categories `disabled-by-default.v8.gc_stats`, `disabled-by-default-v8.runtime_stats` and `v8` you used are correct.

`--track_gc_object_stats` and `--noincremental-marking` are V8 flags, I am not sure how Node handles that but I would assume node sets V8 flags correctly.

**Comment by AndreasMadsen** [comment]
Thanks. `runtime_stats` does work. `gc_stats` still doesn't work. I don't see any 
`V8.GC_Object_Stats` slices.

The [`node --v8-options`](https://gist.github.com/AndreasMadsen/541e993ddab75ad9a8e045d86e7a539a) output lists `--track_gc_object_stats` but not `--noincremental-marking`. Could the name have been changed?

**Comment by lpy** [comment]
the flag is `--incremental-marking`, and with a `no` prefix V8 will automatically recognize it as opposite. If there's no slice, that could mean it's not triggered. Was it possible that the script or whatever you run didn't trigger gc?

**Comment by AndreasMadsen** [comment]
@lpy I see, thanks. GC was triggered, there are `V8.GCScavenger` events in the output. I've uploaded the tracing dump to https://gist.github.com/AndreasMadsen/616f0fc31b265bac060bf6027b4f7c63

**Comment by gireeshpunathil** [comment]
should this remain open? [ I am trying to chase dormant issues to closure ]

**Comment by bnoordhuis** [comment]
To close the loop / for people coming here through search engines - the stanza below should work:
```
$ node --trace-events-enabled --trace-event-categories disabled-by-default-v8.gc_stats script.js
```
See https://github.com/nodejs/node/issues/44177#issuecomment-1221551513 for more details but in summary `--track_gc_object_stats` and `--trace-event-categories disabled-by-default-v8.gc_stats` don't go together well.
