### ISSUE TITLE
Summary of Diag WG Discussion - 2017/10/05 (Node Interactive)

### ISSUE THREAD

**Issue by mike-kaufman** [nodejs/diagnostics#106]
Diagnostic WG had a break-out discussion at Node Interactive 2017.  This is a summary of the disccusion from Friday afternoon, and is a proposed agenda for next WG meeting. 

Please chime in if anything is missing/incorrect. :)

1. **Logistics of WG meetings**
      - @joshgav was driving these, but he's been on leave.  
      - **Next Steps:**
        - @mike-kaufman & @mrkmarron to sync w/ Josh this week. 

2.  **Async-Context**
    - Good discussion on "what is Async Context" . 
    - Consensus was we should first close on high level concepts, terminology  and use cases 
    - some use cases mentioned:
         - long stacks
         - post-mortem analysis - i.e., what was the async path to some point in program execution. 
         - understanding details of each async-op on some async-path - i.e., how long spent blocked on IO, how long in event queue, total CPU cycles on path...)
          - others?
      - **Next Steps:** 
        - @mrkmarron  to post issue w/ link to paper defining async semantics in javascript
        - @jasnell - do some translation from "academic speak" to "something more accessible"
        - discussion to happen on that issue.

2.  **Tracing API**
    - Node has a ~tracing~ `trace_events` API now (namely Chrome's), but it isn't being fully leveraged by node core
    - Chrome's API may be moving out into separate library, so other libs can take a dep on this 
    - Need to understand how ~tracing~ `trace_events` API fits w/ alternative VMs (i.e., node-chakracore)
    - **Next Steps:**
      - TBD/Discuss at WG meeting

3.  **Docs/How-Tos**
    - missing/non-existent docs now on how to do diagnostic tasks
    - **Next Steps:**
      - TBD/Discuss at WG meeting

3.  **Unhandled promise rejections**
    - at least 2 PRs open on this
    - not clear if there is "correct" behavior
    - not clear if consensus on what "least sucky" behavior is
    -  **Next Steps:**
       - TBD/Discuss at WG meeting

**Comment by AndreasMadsen** [comment]
By _tracing API_ do we mean `trace_events`?

PS: I really dislike the word "tracing" it has too many meanings. Even in our own summaries, I think we need to be more precise.

**Comment by jkrems** [comment]
@AndreasMadsen Yep, this was about `trace_events`.

**Comment by mrkmarron** [comment]
Thanks for the summary notes Mike. I just opened issue [#107](https://github.com/nodejs/diagnostics/issues/107) for discussion and work around the async-context item.

**Comment by AndreasMadsen** [comment]
Are we going to have a Hangout meeting about this in the near future? I would like to catch up on the discussions since I couldn't be there.

**Comment by mike-kaufman** [comment]
>Are we going to have a Hangout meeting about this in the near future? 

That's the intention.  What are the general considerations for scheduling something? (e.g., times that work, how much lead time, other things?)

**Comment by mike-kaufman** [comment]
FYI - I went ahead and scheduled the next diag WG meeting.  See issue here:  https://github.com/nodejs/diagnostics/issues/108.

**Comment by mike-kaufman** [comment]
closing this.  Minutes are being checked into wg-meetings folder per PR https://github.com/nodejs/diagnostics/pull/122
