### ISSUE TITLE
Update Diag WG meeting on Node.js Calendar

### ISSUE THREAD

**Issue by mike-kaufman** [nodejs/diagnostics#119]
the [node.js calendar](http://nodejs.org/calendar) has the Diag WG  meeting at UTC 21:00/PST 13:00.  This needs to be at UTC 20:00/PST 12:00.  Previously, meeting was scheduled at 13:00 PDT, but with change to PST, it is now at 12:00.   
 
/cc @mhdawson

**Comment by mhdawson** [comment]
Ok updated, please validate and then close issue.

**Comment by mike-kaufman** [comment]
thanks!
