### ISSUE TITLE
How to get issues tagged for agenda? 

### ISSUE THREAD

**Issue by mike-kaufman** [nodejs/diagnostics#120]
I personally don't have perms sufficient to tag issues outside of the `diagnostics` repo with `diag-agenda`.  This makes it hard to tag issues for the WG meetings. 

Any way to fix this?

/cc @mhdawson, @ofrobots

**Comment by mhdawson** [comment]
Its strange.  I checked the team and you seem to be part of the team, and team members should have write access to the repo.

**Comment by mhdawson** [comment]
Yes a few different views show that you should have write access.  I assume you were logged in when you tried ?

**Comment by mike-kaufman** [comment]
thanks @mhdawson,  To clarify, it works fine in nodejs/diagnostics, but doesn't work in other repos (e.g., nodejs/node).  Not sure if there's an easy solution?  Not a big deal, but may be helpful when trying to put together agenda for WG meetings.

**Comment by mhdawson** [comment]
Ok now I understand.  No easy solution for that one.  You can ask somebody who is a collaborator in the other repo to add or in the worst case we can create a tracking issue in the Diagnostics repo.
