### ISSUE TITLE
Meeting Wednesday ?  Foundation calendar shows meeting for tomorrow

### ISSUE THREAD

**Issue by mhdawson** [nodejs/diagnostics#125]
@mike-kaufman hoping the meeting is still on, but don't see an issue for it yet.

Can you confirm its a go ?

**Comment by mhdawson** [comment]
Never mind I see the issue was created a while back. Assuming meeting is on so closing.

**Comment by mike-kaufman** [comment]
Yeah, I created items through January just to get it out of the way.  I'll fill in tomorrow's agenda in the morning .
