### ISSUE TITLE
administrative: team listed in README does not match team on GitHub

### ISSUE THREAD

**Issue by Trott** [nodejs/diagnostics#127]
Hi! It appears that the @nodejs/diagnostics team in the GitHub organization is somewhat out of date (probably should remove @mikeal and @joshgav, for example). Is the list in the README file in thie repository also out of date? Can we try to come up with a current canonical list and get it in both places?

**Comment by hashseed** [comment]
Is there any formal requirements and obligations to being part of the WG? So far I've been to two meetings, without explicitly being invited to.

**Comment by jkrems** [comment]
@hashseed I think adding yourself to the list in the README is as official as it gets and there's no further expectations beyond being active (https://github.com/nodejs/diagnostics/blob/master/GOVERNANCE.md#wg-membership).

**Comment by AndreasMadsen** [comment]
> Is the list in the README file in thie repository also out of date?

Some of the members are APM providers that just wants to be notified on relevant issues. So it is hard to judge activity. Also, there is no clear guideline of how much activity is needed to be a member.

The README list is the most updated list we have. The reason why @nodejs/diagnostics is outdated is mostly that no one in the WG have permissions to make changes to @nodejs/diagnostics.

**Comment by Trott** [comment]
> The reason why @nodejs/diagnostics is outdated is mostly that no one in the WG have permissions to make changes to @nodejs/diagnostics.

Currently four people in @nodejs/diagnostics have those permissions: @ofrobots, @mhdawson, @Fishrock123, and @joshgav.

(If that's not sufficient, they or I can add others if there's a clear obvious choice for someone to maintain it.

I'm also happy to make changes if I can get clear instructions as to who should be removed and who should be added.

**Comment by mhdawson** [comment]
The team is just not up to date with the README.md which should be the reference. 

I agree that a PR to add yourself the README.md is current process as far as I know.  The list through is pretty long and some rationalization might make sense before we update the team.  

@nodejs/automation it would be great if we had a bot to sync teams with lists in the README.md for each WG.  That would keep things in sync and be one less thing somebody has to remember to change.

**Comment by mhdawson** [comment]
One of thought is that we may want to take this opportunity to merge the merge the members from the post-mortem WG.

**Comment by joyeecheung** [comment]
@mhdawson That might actually fix https://github.com/nodejs/automation/issues/17 as well...we would need to come up with a consistent format of contacts for different repo though. (Is the format thing under the scope of nodejs/admin?)

**Comment by mhdawson** [comment]
I think having a consistent format defined in the admin repo makes sense, WGs can then "opt-in" if they want their team to be automatically maintained. (I'm guessing every will do that as opposed to having a different format :))

**Comment by mmarchini** [comment]
Is there anything left to be done here?
