### ISSUE TITLE
Get @mike-kaufman permissions issue to create hangouts/livestream as "node.js" 

### ISSUE THREAD

**Issue by mike-kaufman** [nodejs/diagnostics#138]
I currently lack perms to create a hangout under the "node.js" identity and subsequently create a livestream of the hangout under this identity.  We need to fix this.

**Comment by mhdawson** [comment]
I've given an FYI to the TSC/foundation that I'll do this unless there are objections by Friday.

**Comment by mhdawson** [comment]
Believe this is done, closing.
