### ISSUE TITLE
Run clang sanitizers on node.js

### ISSUE THREAD

**Issue by mike-kaufman** [nodejs/diagnostics#149]
- plan on how to run clang sanitizers (asan, ubsan,...) on node.js core
  - run nightly or weekly
  - identify & fix issues
- plan for instructinos/how-to on running clang sanitizers on native modules
  - if  a user has a problem, they should be able to compile their native modules with appropriate clang santiizer instrumentation, and then run workload & hopefully identify problems

**Comment by gireeshpunathil** [comment]
should this remain open? [ I am trying to chase dormant issues to closure ]

**Comment by mmarchini** [comment]
We're running ASAN on Linux. IMO this can be closed as there's another tracking issue on core for it.
