### ISSUE TITLE
make trace-events write to configurable sink

### ISSUE THREAD

**Issue by mike-kaufman** [nodejs/diagnostics#152]
in stateless/paas environments, we want trace-event data to be written to a configurable, arbitrary "sink" (i.e., a stream that can be a socket, file, ...).

  - can configure with an arbitrary file path
  - network socket
  - local shared memory?

For context, at diagnostics summit, we discussed getting "failure" data off of stateless environments in general.  We identified three types of data we're interested in:
  - stdout/stderr
  - core dumps
  - trace events

stdout/stderr is configurable by redirecting the stream. 
core dumps are configurable via the host environment
This leaves only trace-event data that we want to configure.

**Comment by mike-kaufman** [comment]
some overlap here w/ #163?

**Comment by AndreasMadsen** [comment]
I don’t think so. Trace Events is a provider for our UDTP (user defined tracking point) implementation. The other implementations will have their own sink mechanism (the kernel).

PS: https://github.com/nodejs/node/pull/18480 will land soon, so that will at least make it possible to write to an arbitrary file.

**Comment by jasnell** [comment]
Quick update on this: @ofrobots and I have been speaking about the possibility of using the inspector protocol to deliver trace events. Some work has already started in this direction with a PR to allow multiple concurrent inspector protocol sessions. There's a bit of work to do here but it should give us a number of solid options.

**Comment by mike-kaufman** [comment]
Having this data over CDP is really useful, but does it obviate desire to redirect trace events to a file/stream, e.g. via a command-line switch?  Consuming CDP may be challenging in PaaS environments, due to network constraints, process constraints, ...

**Comment by ofrobots** [comment]
File output would still be supported.

**Comment by gireeshpunathil** [comment]
should this remain open? [ I am trying to chase dormant issues to closure ]

**Comment by jasnell** [comment]
This can be closed
