### ISSUE TITLE
Diag WG meeting times?

### ISSUE THREAD

**Issue by mike-kaufman** [nodejs/diagnostics#158]
current meetings are at 1PM PST/9PM GMT.  There's an open question on if this time works for ppl around the world.  We're open to considering different times and/or alternating. 

There's a proposal to alternate bi-weekly meetings between 9AM PST and 1PM PST.  

Please chime in here if the above times don't work.

**Comment by hashseed** [comment]
I would greatly appreciate an earlier schedule. The reason I rarely attend is that it always happens at a time I ought to be sleeping.

**Comment by mcollina** [comment]
A time that was mentioned several time is 5pm GMT/9am PST

**Comment by hashseed** [comment]
I would prefer 7pm GMT if possible. 5pm sort of works but is not ideal.

**Comment by mmarchini** [comment]
Our next meeting will still be at 1PM PST or we'll update the time before that?

**Comment by mike-kaufman** [comment]
Let's do this week's meeting at 1 PM PST, and we'll close discussion on how to modify the schedule.

**Comment by mhdawson** [comment]
Both times work for me provide there are no conflicts with other wg meetings

**Comment by danielkhan** [comment]
Are the issues for the meetings gone or am I just not seeing them today @mike-kaufman. When wil this week's take place?

**Comment by mike-kaufman** [comment]
sorry, this wed @ 1PM PST.  I'll open the issue today.

**Comment by mike-kaufman** [comment]
Let's discuss at this week's diag meeting.  

  - here's the [node.js foundation calendar]( https://calendar.google.com/calendar/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98%40group.calendar.google.com)
 - 9AM PST/5PM GMT has a periodic conflict w/ TSC meetings
- 11AM PST/7 PM GMT has periodic conflict w/ moderation committee meetings.
 - We can alternate times bi-weekly, but we also discussed bi-weekly deep-dives on specifics topics.

**Comment by mike-kaufman** [comment]
Discussed at WG meeting.  Proposal is we move Diagnostics WG meeting to 11 AM PST/7PM GMT bi-weekly.  There will be periodic but infrequent conflicts with the moderation committee. Please thumbs-up/thumbs-down this post if you agree/disagree.

**Comment by mike-kaufman** [comment]
ping @nodejs/diagnostics.  Final opportunity to vote on the WG meeting time.  Please thumbs-up/thumbs-down [this post](https://github.com/nodejs/diagnostics/issues/158#issuecomment-367484685) if you have an opinion. :)

**Comment by mike-kaufman** [comment]
@mhdawson  - I'm not sure I have correct perms to update the time on the node.js calendar - can you do this?

**Comment by mcollina** [comment]
@mike-kaufman I've updated the calendar.
