### ISSUE TITLE
Request to join the diagnostics working group

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/diagnostics#159]
I have attended the diagnostics summit this February, and I think it makes sense for me to join the diagnostics working group.

I propose that people who are interested in joining this working group can reply here, after two days if there are no objections against the requests, I would collect the handles here and add people to the @nodejs/diagnostics team, then I'll open a PR that sync the team with the README using `ncu-team` that closes this issue.

**Comment by mcollina** [comment]
Count me in.

**Comment by mmarchini** [comment]
Me too o/

**Comment by hekike** [comment]
+1

**Comment by Hollerberg** [comment]
yes, please

**Comment by cjihrig** [comment]
@joyeecheung can you include me as well please.

**Comment by hashseed** [comment]
me too.

**Comment by jasnell** [comment]
me too :-) ...

**Comment by Flarna** [comment]
mee too

**Comment by joyeecheung** [comment]
I have sent out invitations for people who are not yet members of this organization @hekike @Hollerberg @Flarna  (people who are will just get added to the team I believe). Once those invitations are accepted I will open a PR to sync the README.
