### ISSUE TITLE
Flow events in trace_events

### ISSUE THREAD

**Issue by hashseed** [nodejs/diagnostics#166]
I recently learned that this is a thing in the trace events implementation that V8 and Chrome uses. [Async and flow events](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.jh64i9l3vwa1) can be used to chain asynchronous events together and about://tracing visualizes that.

For an example
* open about://tracing in Chrome
* start recording with the categories "toplevel" and "toplevel.flow" checked
* load some page
* stop recording
* check "Flow events" in "View Options"

**Comment by jasnell** [comment]
Yeah, I've been playing a bit with this and it certainly adds an interesting dimension. @AndreasMadsen ... Have you looked in to how flow events can be used with async_hooks at all?

**Comment by AndreasMadsen** [comment]
I looked into it. I think it was more for visualizing data flow and not the relationship between an async resource and its callback. If I recall correctly they are also used in TensorFlow profiles for visualizing data flow.

That being said, it could be that they can be used for `async_hooks`, in which case they are properly better. But, it wasn't really obvious to me how that would look like.

**Comment by mmarchini** [comment]
This seems like a PSA, so closing. Feel free to reopen if there's anything left to be discussed.
