### ISSUE TITLE
Diag WG Deep Dives - topics

### ISSUE THREAD

**Issue by mike-kaufman** [nodejs/diagnostics#168]
For the bi-weekly diag WG call, we want to have periodic deep-dives where we use the entire hour to discuss a specific topic at length.

Please do two things here:
  - 👍 or 👎 on this. 
  - comment on any topics you'd like to see or drive

Deep Dive Topics:
  - CI testing to ensure tools compatibility (#156)
  - Async Context Model (#107, http://mike-kaufman.github.io/async-context-definition)

/cc @nodejs/diagnostics

**Comment by mmarchini** [comment]
Anyone interested in a Deep Dive about **Expectation about tier of support from diagnostic tools and VMs** (#157)?

**Comment by mmarchini** [comment]
Proposed agenda: https://github.com/nodejs/diagnostics/issues/157#issuecomment-391725806

Feel free to edit the agenda and add/remove/change items.

**Comment by gireeshpunathil** [comment]
deep dives are established, and running. closing; pls re-open if there is anything outstanding here
