### ISSUE TITLE
V8's CpuProfiler uses busy wait on Windows.

### ISSUE THREAD

**Issue by hashseed** [nodejs/diagnostics#170]
The reason for that is described in [this comment](https://github.com/v8/v8/blob/28c81eeef7c3eea13f75d6af876bb9edd1e2239e/src/profiler/cpu-profiler.cc#L170):
```comment
// Do not use Sleep on Windows as it is very imprecise.
// Could be up to 16ms jitter, which is unacceptable for the purpose.
```

This in turn is not acceptable for some APM vendors who run the CpuProfiler in production. For sampling intervals significantly larger than 16ms we should be fine with using Sleep though.

@Hollerberg

**Comment by hashseed** [comment]
@Flarna @Hollerberg feel free to have this cherry-picked onto Node.js. I don't think we will backmerge this change in V8 upstream.

**Comment by Flarna** [comment]
@hashseed Thanks for the change!
But I think there is an else missing in current code. Now there is no wait at all for long intervals...

**Comment by Flarna** [comment]
Will close this as this is included in NodeJS 10 onwards.
