### ISSUE TITLE
Execution time analysis in Node

### ISSUE THREAD

**Issue by blackink000** [nodejs/diagnostics#171]
We are interested in making a real time performance monitoring tool that shows the developer the name and execution times of all the async functions in an application.

We are currently exploring 3 different avenues to get the required data: via async hooks, the debugging libraries, and through a general override of the function prototype.

We are interested in your feedback about whether our approaches to the problem are appropriate or if another approach would be necessary.

With async hooks module we can measure the duration of a request in the event loop but the attribution is by asyncID. Is there a way to tie in the asyncID to the actual name of the function? What approaches would you recommend we try?

Thanks to @mhdawson for suggesting we reach out to the diagnostics group.

**Comment by AndreasMadsen** [comment]
> Is there a way to tie in the asyncID to the actual name of the function? What approaches would you recommend we try?

That is very difficult because a single async function (as in public API) can create multiple async resources. For example, a single http request may generate a TCP socket, a timeout on the socket, and a HTTPParser.

You can use `new Error().stack` to look at how the async resource was created, but it isn't always that simple.

There are also cases where an async resource related to an async function isn't immediately created. For example, there might need to be a DNS lookup before a TCP socket can be created if you make a TCP request.

**Comment by danielkhan** [comment]
To get started, I recommend [this excellent presentation](https://www.youtube.com/watch?v=nvHxA7dYw0w) by @watson where he covers how to wrap functions or - alternatively - use async hooks to get timings.

**Comment by blackink000** [comment]
@AndreasMadsen We arrived at a similar conclusion when trying to use async hooks for nested async tracing.

Perhaps we have the wrong idea for async hooks in that they're more of a tool for developers to use for debugging rather than a tool for libraries to be built around.

Are we correct in this thinking?

Thanks @danielkhan, this is the exact same kind of tracing we're looking for, but it seems like @watson  company doesn't use async hooks as well, but rather framework specific middleware overriding to achieve this tracing information.

**Comment by AndreasMadsen** [comment]
> Perhaps we have the wrong idea for async hooks in that they're more of a tool for developers to use for debugging rather than a tool for libraries to be built around.
> 
> Are we correct in this thinking?

I would say it is exactly a tool for "libraries to be built around". `async_hooks` doesn't make the task easy but it does make the task easier.

**Comment by blackink000** [comment]
Ok thank you!
