### ISSUE TITLE
0x v4 announcement

### ISSUE THREAD

**Issue by davidmarkclements** [nodejs/diagnostics#177]
0x is a flamegraph generating tool that previously relied on dtrace and perf to sample a node process

0x v4 instead relies on the `--prof` flag to sample and the `--prof-process --preprocess` flags to convert isolate log file data to JSON for further processing.

This was primarily necessary because of the current incompatibility between ByteCodeHandler frames in V8 that Node 8.5.0+ uses and kernel tracing tools. 

However, additional benefits of using the V8 profiler include 
* Total cross platform support (anything that Node runs on) – in particular this gives 0x v4 Windows support
* Profiling node processes inside containers or vms with zero configuration (e.g. no need for privileged mode)
* No need for sudo/root access 

Other cool features in the latest release include

* capturing inlining data with the `--print-opt-source` flag (because it includes file paths) and creating an "inlinable" filter (https://github.com/davidmarkclements/0x/blob/master/docs/ui.md#inlinable)
* a "merge" button (https://github.com/davidmarkclements/0x/blob/master/docs/ui.md#merge) – stacks may diverge based on optimization status and whether functions in a stack have been inlined, the merge button ignores optimization status and removes functions that are inlined at some point in the sampling - this leads to a simplified flamegraph where stacks diverge based on core/userland logic only
* A neat `--on-port` flag, allowing for a process to be immediately load tested on start, after which the flamegraph is automatically generated (e.g. `0x -P 'autocannon localhost:$PORT' app.js`) 
(https://github.com/davidmarkclements/0x/#--on-port---p)

Repo: https://github.com/davidmarkclements/0x
Demo: http://davidmarkclements.github.io/0x-demo/

**Comment by ofrobots** [comment]
> a "merge" button

That's a killer feature! Thanks for sharing!

> Total cross platform support

Yep, this is why we added `--prof-process` to Node. `--prof` has the best out of the box profiling experience for most users. dtrace and Linux perf can enable even more lower level insights, but for majority of the users they are incredibly hard to setup and use.
