### ISSUE TITLE
Step Debugging section readme is outdated

### ISSUE THREAD

**Issue by glennschler** [nodejs/diagnostics#189]
The [Step Debugging section](https://github.com/nodejs/diagnostics/blob/master/debugging) referenced from the diagnostics working group readme has a number of broken and incorrect links.

1 - [Chrome Debugging Protocol](https://chromedevtools.github.io/debugger-protocol-viewer/) not landing in correct sub-section. Perhaps [devtools-protocol/v8/](https://chromedevtools.github.io/devtools-protocol/v8/)?
2 - [V8 Debugging Protocol](https://github.com/v8/v8/wiki/Debugging-Protocol) not landing at correct sub-section. Perhaps [v8/wiki/Debugging-over-the-V8-Inspector-API](https://github.com/v8/v8/wiki/Debugging-over-the-V8-Inspector-API)?
3 - [v8/include/v8-debug.h](https://github.com/v8/v8/blob/master/include/v8-debug.h) broken. Perhaps [v8/src/debug/debug.h](https://github.com/v8/v8/blob/master/src/debug/debug.h)?
4 - [v8/src/debug/debug.js#L2341-2372](https://github.com/v8/v8/blob/master/src/debug/debug.js#L2341-L2372) does reference a v8 debug.js file, though those line numbers do not exist.
5 - [node/src/debug-agent.h](https://github.com/blob/master/src/debug-agent.h) broken.
6 - [node/lib/_debugger.js](https://github.com/blob/master/lib/_debugger.js) broken.

To update this readme, should it also reference the Node.js Documents for [Debugger#debugger_advanced_usage](https://nodejs.org/api/debugger.html#debugger_advanced_usage), as well the recently updated [Debugging getting started guide](https://nodejs.org/en/docs/guides/debugging-getting-started/)?

**Comment by vmarchaud** [comment]
I've created a PR that try to fixes these issues over there : https://github.com/nodejs/diagnostics/pull/190
If you have anything to add or maybe clarify, do not hesitate !
