### ISSUE TITLE
[trace-events] Tracing Controller should keep list of possible categories

### ISSUE THREAD

**Issue by ofrobots** [nodejs/diagnostics#191]
Context: https://github.com/nodejs/node/pull/20608/files#r186918294

It would be good for the Tracing Controller to keep a list of categories available for use in the process.

**Comment by AndreasMadsen** [comment]
I'm not sure how that can be done since we are going to allow users to have their own categories. We could properly maintain a dynamic set object but a static list definitely isn't possible.

**Comment by jasnell** [comment]
For *now* at least, the API won't be exposed to end users but this still presents a challenge long term.

We would provide an API via the trace_events module to register categories for that list.

**Comment by ofrobots** [comment]
BTW, the former works fairly well for Chrome at the moment:

![image](https://user-images.githubusercontent.com/79017/39895119-f9461532-545d-11e8-98e2-988f12546d49.png)
