### ISSUE TITLE
Node.js Foundation Diagnostics WorkGroup Meeting 2018-05-31 (11 AM WEDT, 2AM PDT)

### ISSUE THREAD

**Issue by mhdawson** [nodejs/diagnostics#200]
## Time

**UTC Wed 31-May-2018 09:00**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 31-May-2018 11:00 (02:00 AM) |
| US / Mountain | Wed 31-May-2018 12:00 (03:00 AM) |
| US / Central  | Wed 31-May-2018 13:00 (04:00 AM) |
| US / Eastern  | Wed 31-May-2018 14:00 (05:00 AM) |
| London        | Wed 31-May-2018 19:00 (10:00 AM) |
| Amsterdam     | Wed 31-May-2018 20:00 (11:00 AM) |
| Moscow        | Wed 31-May-2018 21:00 (12:00 Noon) |
| Chennai       | Wed 31-May-2018 23:30 (2:30 PM) |
| Hangzhou      | Thu 31-May-2018 02:00 (02:00 PM) |
| Tokyo         | Thu 31-May-2018 03:00 (06:00 PM) |
| Sydney        | Thu 31-May-2018 04:00 (07:00 PM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Diagnostics%20WorkGroup+Meeting+2018-05-31&iso=20180531T09
* or http://www.wolframalpha.com/input/?i=09AM+UTC%2C+May+31%2C+2018+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1pNfwwHoZSfKKWwP-z4LH4yuN_VtrDo_6DTqzVdmT-PY/edit>

## Agenda

Extracted from **diag-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/diagnostics

* Strategic Initiatives/Champions like we have on TSC [#185](https://github.com/nodejs/diagnostics/issues/185)
* Diagnostics Channel - Next steps [#180](https://github.com/nodejs/diagnostics/issues/180)
* Diag WG Deep Dives - topics [#168](https://github.com/nodejs/diagnostics/issues/168)
* Node CPU Profiling Roadmap [#148](https://github.com/nodejs/diagnostics/issues/148)
* \[async_hooks\] stable API - tracking issue [#124](https://github.com/nodejs/diagnostics/issues/124)
* Async-context formalization and diagnostics support [#107](https://github.com/nodejs/diagnostics/issues/107)
* \[trace_event\] tracking issue [#84](https://github.com/nodejs/diagnostics/issues/84)

## Invited

* Diagnostics team: @nodejs/diagnostics

## Notes

The agenda comes from issues labelled with `diag-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: Will be added a few minutes before meeting starts
* For those who just want to watch: 
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

**Comment by mhdawson** [comment]
I'll be travelling so may not be able to make this one.

**Comment by mhdawson** [comment]
We can have sombody use their laptop to setup a hangout/zoom, but the experience will be subpar for remote people (as is the case in my opinion when there are a number of people in a room and other people are remote).

**Comment by hashseed** [comment]
+1 on combining.

**Comment by mike-kaufman** [comment]
Can someone post the time for the diag session at summit?

**Comment by mhdawson** [comment]
Agenda is here: https://github.com/nodejs/summit/issues/60

Currently shows 11-12:30 Berline time on May 31

**Comment by mike-kaufman** [comment]
OK, let's do this at 11 AM Berlin time (WEDT), (2 AM PDT) on May 31.  Given the timing, I will not be attending.  I'll leave it up to someone else to post any relevant notes.
