### ISSUE TITLE
Informal Diagnostic Meetup Around Node Summit

### ISSUE THREAD

**Issue by yunong** [nodejs/diagnostics#201]
From the collaborator's summit last week there was a discussion around holding another diagnostic summit in the next couple of months. 

Node Summit will be held in San Francisco during the week of July 23-27. Is there interest in holding it at that time in the Bay Area? We (Netflix) would be happy to provide office space/food/drinks before or after Node Summit.

**Comment by hashseed** [comment]
I'll have to pass on that. But I was actually thinking of hosting one in Munich, possibly November or February. I still have to hash out the details though.

**Comment by joyeecheung** [comment]
Isn't November too soon for another diag summit? Since we are probably going to talk about diagnostics at the summit after JS Interactive.

**Comment by mhdawson** [comment]
The reason we were talking about a diag summit is that it needs more than an hour or so to get into details.  In that case we'd really not be covering it at JS Interactive enough to preclude the dedicated 1-2 day summit.

**Comment by mmarchini** [comment]
NodeSummit is less than two months away. If we decide to have a Diag. Summit close to it, we should settle on dates soon.

**Comment by mcollina** [comment]
I’m ok in doing this nearby NodeSummit, I’ll be there.

**Comment by vdeturckheim** [comment]
If dagnostics summit happens on July 26-27 (and if I am allowed to attend it ;) ) I should be able to be here!

**Comment by ofrobots** [comment]
I can attend any day between 23-26, but not on the 27th.

**Comment by mcollina** [comment]
I am free on the 26th.

**Comment by mhdawson** [comment]
The node summit training days are JULY 26 & 27, so we might want to avoid those days in case people need to participate in those.

**Comment by mcollina** [comment]
> The node summit training days are JULY 26 & 27, so we might want to avoid those days in case people need to participate in those.

I'll need to be available on the 26th to help out with our workshop.

Should we do 28th and 29th or 30th and 1st?

**Comment by jasnell** [comment]
Friday 27th or Saturday 28th are the only days I would have available that week.

**Comment by mmarchini** [comment]
I'll be available before and after the conference as well as during the training days (26 and 27).

**Comment by yunong** [comment]
I'd like to avoid weekends(28-29) as folks in the Bay Area may have family obligations. Also, do we need a two day summit? Sounds like the 28th might work for everyone?

**Comment by jasnell** [comment]
One day is best, I think, and we should be able to get through the majority of what we need as long as we have a defined agenda and good time boxing.

**Comment by mcollina** [comment]
@yunong the 28th is a Saturday, did you mean the 27th?

**Comment by yunong** [comment]
@mcollina sorry, yes, 27th. I've updated my original comment.

**Comment by mmarchini** [comment]
27th works for me

**Comment by ofrobots** [comment]
As stated earlier, if the summit is on the 27th, I will not be attending.

I feel that this is getting rushed. I know some of you can attend, but are we leaving enough time for the rest to be able to make travel plans?

**Comment by mhdawson** [comment]
I agree that we should get more of the @nodejs/diagnostics team and other past participants chiming in.  At the risk of spamming mentioning those who attended that last summit:

1. @mhdawson
1. @mcollina
1. @mike-kaufman
1. @Qard
1. @hashseed
1. @watson
1. @mrkmarron
1. @jasnell
1. @danielkhan
1. @komawar
1. @joyeecheung
1. @cjihrig 
1. @fhinkel
1. @jkrems
1. @ofrobots
1. @dshaw
1. @kjin
1. @aruneshchandra 
1. @hekike
1. @mmarchini 
1. @Flarna
1. @Hollerberg
1. @distracteddev
1. @apapirovski
1. @skaegi 
1. @Fishrock123

**Comment by Flarna** [comment]
I don't think that I will attend but for sure I will follow offline. feb/march in Munich sounds good.

**Comment by Qard** [comment]
I have no plans of being at Node Summit currently. I'm not sure I'd be able to get Elastic to sponsor more travel again so soon after sending me to jsconf eu. 😞

**Comment by mrkmarron** [comment]
If it is on the 26th or 27th I should be able to attend (with a preference for the 26th).

**Comment by cjihrig** [comment]
I'll be at Node Summit but am leaving SF early on the 26th.

**Comment by gireeshpunathil** [comment]
I am interested as well as planning to participate.

**Comment by mhdawson** [comment]
We discussed in the Diagnostics meeting this week, that we need more time to schedule the summit.

Next steps will be to suggest a number of dates/locations and discuss.

**Comment by yunong** [comment]
We can still have an informal meetup hosted by Netflix on the 27th -- please RSVP if you'd like to participate.

**Comment by mcollina** [comment]
I'll be there if I can!

**Comment by mmarchini** [comment]
I'll be there too!

**Comment by vdeturckheim** [comment]
To be confirmed bu I should be arround

**Comment by mhdawson** [comment]
I can't make the 27th, I'm around the 26th though if plans change.

**Comment by apapirovski** [comment]
I should be able to make it out on either the 26th or the 27th.

**Comment by yunong** [comment]
Unfortunately, I haven’t been able to organize this in time for Friday. Going to cancel this informal meetup and I’ll see you all at node summit.
