### ISSUE TITLE
Next Diagnostic Summit

### ISSUE THREAD

**Issue by yunong** [nodejs/diagnostics#206]
Let's try this again and give folks a long lead time to figure out scheduling and travel.

How about a 2-day summit in September? There have been discussions for holding it alongside JS interactive and the collab summit in October -- but that's a lot of meetings all in one place and folks could feel burnt out by the end.

Netflix is happy to host in Los Gatos, CA, but of course open to other venues/dates as well.

**Comment by gireeshpunathil** [comment]
should this issue remain open? [ I am trying to chase dormant issues to closure ] @yunong

**Comment by gireeshpunathil** [comment]
makes sense; so let us close this, open another one for the future one.
