### ISSUE TITLE
Poll about APM usage

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/diagnostics#207]
During the collaborator summit I reached out on twitter to get some stats for APM usage in the ecosystem and that worked quite well (https://twitter.com/BridgeAR/status/1002127356553842689).

![image](https://user-images.githubusercontent.com/8822573/41819769-6de9a170-77c6-11e8-9667-1bef3709680c.png)

This knowledge should not only be useful for APMs but also somewhat for Node.js as most APMs will switch to using async_hooks where possible.

**Comment by bnb** [comment]
For what it's worth, I would like to cast a bit of doubt on a Twitter poll as a reliable source of data.

Not saying that this isn't a valuable point of data, but there are numerous factors here (followers, Twitter's algorithim, circles, being retweeted by those who have an express interest in it going one way or another) that contribute to the end result of a Twitter poll.

Actually pretty surprised that this came up today, as I've been having some discussions with @johnpapa about this over the past two days. Specifically, I actually pretty strongly agree with his statement [here](https://twitter.com/John_Papa/status/1011438944808992768) - polls are highly subjective 😁

**Comment by BridgeAR** [comment]
I have not been involved in anything APM related. Therefore I am pretty sure the poll is not biased due to that reason. The participants came mainly from the Node.js retweet and I believe that is neutral. Also: all polls are normally shared on twitter in users filter bubbles. So it's not really about twitter in my opinion but more about polls in general: some people care about a subject and will try to get their peers to participate.

All that aside: the poll was mainly to get a rough overview for the usage of APMs and async_hooks that might be used by APMs.
The numbers were confirmed by @sqreen (if I remeber correct) by their own internal survey.

**Comment by bnb** [comment]
Happy to have a more overarching discussion about this, but note that several people retweeted it from Elastic and NodeSource - myself included! We all have bubbles – especially those that work in this space tend to have followings that will lean in to their own experiences and activities. Because of this, bias will exist.

As I noted, this is a valuable data point - but definitely shouldn't be considered exhaustive.

**Comment by Qard** [comment]
APM is an obscure enough field that most of us that work in it actually only have a few other friends in the same field. The vast majority of my friends know little to nothing about APM/diagnostics things. 😅
