### ISSUE TITLE
Membership in README might need an update?

### ISSUE THREAD

**Issue by Trott** [nodejs/diagnostics#213]
Ryan Graham (@rmg) is listed in the README as a member of the Working Group. But they are not in @nodejs/diagnostics and they appear as an attendee in the minutes in the repo only once at a 2015 meeting. Should they be removed from the README? Alternatively, should they be left in the README and added to @nodejs/diagnostics?

**Comment by mhdawson** [comment]
Proposing a membership review - https://github.com/nodejs/diagnostics/issues/215

**Comment by rmg** [comment]
I'm ok with being removed (https://github.com/nodejs/diagnostics/issues/215#issuecomment-404674197).

**Comment by richardlau** [comment]
The list in the README has the directives to use `ncu-team sync` (https://github.com/nodejs/diagnostics/pull/147). Maybe a rerun is all that is required to sync the list with the GitHub group?
