### ISSUE TITLE
Membership review - still active?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/diagnostics#217]
Membership review as agreed in: https://github.com/nodejs/diagnostics/issues/215

@AndreasMadsen - Andreas Madsen -> Active
@bnoordhuis - Ben Noordhuis
@brycebaril - Bryce Baril -> emeritus
@cjihrig - Colin Ihrig -> Active
@danielkhan - Daniel Khan -> Actrive
@dberesford - Damian Beresford
@Fishrock123 - Jeremiah Senkpiel
@Flarna - Gerhard Stöbich ->active
@hashseed - Yang Guo ->active
@hekike - Peter Marton ->active
@Hollerberg - Gernot Reisinger -> Active
@jasnell - James M Snell ->active
@jkrems - Jan Olaf Krems -> Active
@joyeecheung - Joyee Cheung ->active
@kjin - Kelvin Jin -> Active
@mcollina - Matteo Collina -> active
@mhdawson - Michael Dawson ->active
@mike-kaufman - Mike Kaufman -> active
@mmarchini - Matheus Marchini ->active
@naugtur - Zbyszek Tenerowicz ->active
@ofrobots - Ali Ijaz Sheikh -> active
@othiym23 - Forrest L Norvell -> active
@piscisaureus - Bert Belder -> emeritus
@pmuellr - Patrick Mueller -> emeritus
@Qard - Stephen Belanger -> active
@rmg - Ryan Graham -> emeritus
@sam-github - Sam Roberts -> active
@thekemkid - Glen Keane
@thlorenz - Thorsten Lorenz -> emeritus
@trevnorris - Trevor Norris
@watson - Thomas Watson -> active
@yunong - Yunong Xiao -> active

Please confirm by posting a comment on this issue if you plan to continue being active in the Diagnostics WG. If we don't hear from you we will move you to emeritus as outlined in #215 .

**Comment by mhdawson** [comment]
Have already heard from (in issue discussion review in the first place)

@rmg  -> emeritus
@naugtur -> active
@hekike  -> active
@jasnell ->active
@hashseed ->active
@ofrobots ->active
@yunong ->active
@mmarchini ->active
@Flarna ->active

**Comment by joyeecheung** [comment]
I am still active

**Comment by AndreasMadsen** [comment]
I'm still here if you need me :)

**Comment by Hollerberg** [comment]
still breathing

**Comment by cjihrig** [comment]
Also still breathing. Sometimes

**Comment by kjin** [comment]
I also plan to continue being involved, I have been having time conflicts over the last few months but should be more available in Sept onward.

**Comment by othiym23** [comment]
still around, would like to get more involved

**Comment by danielkhan** [comment]
Still around. More involvement again soon.

**Comment by pmuellr** [comment]
I have not been active on the calls, probably won't have time to get back in the swing here for a while, but could come back later.  I guess a move to emeritus is appropriate.  

I do occasionally watch the various GH traffic in the repo tho, so would like to maintain GH team membership.

If it's not simple to do both of those I can be pulled from the GH team, and I'll re-request access when I get find time to collaborate here.

**Comment by jkrems** [comment]
I'm still around as well

**Comment by Qard** [comment]
I'm active.

**Comment by yunong** [comment]
I'm active.

**Comment by mhdawson** [comment]
@bnoordhuis - Ben Noordhuis
@brycebaril - Bryce Baril
@dberesford - Damian Beresford
@Fishrock123 - Jeremiah Senkpiel
@piscisaureus - Bert Belder
@sam-github - Sam Roberts
@thekemkid - Glen Keane
@thlorenz - Thorsten Lorenz
@trevnorris - Trevor Norris

This is the second reminder

**Comment by piscisaureus** [comment]
Hi Michael,

Long time. How are things?
I'm not active in this working group, I'm actually not even sure how I got
in here.

Cheers,
-Bert

**Comment by piscisaureus** [comment]
I'm not active.

**Comment by refack** [comment]
What's the path for joining?

**Comment by watson** [comment]
@refack I believe the process is still that you just open a PR like this one: https://github.com/nodejs/diagnostics/pull/28

**Comment by sam-github** [comment]
I'm planning on becoming more active soon, I've been taking some time off.

**Comment by brycebaril** [comment]
As much as I'd like to be, I just can't guarantee I'll be able to dedicate any time to this wg for a while. Better move me to emeritus.

**Comment by thlorenz** [comment]
I'm interested and working in this space, just not sure if I have the time to attend regular meetings.
So may move me to emeritus as well for now, but I'll help when I can.

**Comment by gireeshpunathil** [comment]
looks like this is actioned; closing. it makes sense to visit the membership once again, in some time
