### ISSUE TITLE
expose gc event as inspector's runtime event

### ISSUE THREAD

**Issue by vmarchaud** [nodejs/diagnostics#220]
Hi everyone,

I would like to discuss the best way to expose metrics about the GC life cycle to the JS land through the `inspector` module.
As lot of knows, we can give the `--trace-gc` and `--trace-gc-verbose` to V8, it will then print some data at each GC passage. I believe it would be really useful for users (and APM vendors) to be able to access those metrics to better understand diagnostics their applications.

Anyway i'm (and @keymetrics) willing to put some time on this problem but i'm not sure what is the right way to do it. I suppose modifying V8 in `deps/v8/` isn't a really good idea so i would have done it by "hijacking" the protocol session to add our own method. Then at this point just implement it in C++ with the V8 C++ API.

What you guys think of this ? Maybe someone already started to work on something similar ?

**Comment by gireeshpunathil** [comment]
- direct invocation of v8 APIs looks to be a good idea.
 - but how do we expose this to APMs? through JS callbacks? what would be the relevance of `inspector`?
 - slightly related: how node-report extracts [heap statistics](https://github.com/nodejs/node-report/blob/824648730f85b7d434e55382c49f4eef55ce884f/src/node_report.cc#L718)  (only snapshot)

**Comment by vmarchaud** [comment]
I believe we could expose this as a function of the `Runtime` domain, so we could do something like that : 

```javascript
const inspector = require('inspector')
const session = new inspector.Session()
session.connect()

session.post('Runtime.enable')
session.on('Runtime.garbageCollectionStats', (stats) => {
   // we get the GC duration, type etc
})
```

The heap statistics is already exposed trough the `v8` module so i believe we only need to get GC related metrics here

**Comment by ofrobots** [comment]
@vmarchaud Have you looked at the [`trace_events`](https://nodejs.org/dist/latest-v10.x/docs/api/tracing.html) API? V8 exposes high level GC events by default and there some 'disabled-by-default' categories for lower level events that expose GC behaviour in excruciating detail. Please give it a shot, and leave feedback on how well (or not) it would work for your use-cases.

`trace_events` is still rough around the edges, but is a better API for this use-case IMO. If you're willing to contribute to help shape it up, that would be awesome too!

**Comment by ofrobots** [comment]
FYI, the trace event data is exposed through a file – or through the inspector protocol – albeit we are still working on [bugs](https://github.com/nodejs/node/pull/22114) in the latter. Here's some sample code that you can use to connect to process and get Tracing data out: https://gist.github.com/ofrobots/ab4c4e68b0de4852197308cd25f3cc0e

**Comment by vmarchaud** [comment]
@ofrobots I knew about the trace_events API, but i didn't know it allow to get those metrics, i will try tomorrow to see what i can get with it.
I followed the different PRs about the API being toggleable at runtime, do you know if its planned to backport it to 8.x or 10.x ?

**Comment by ofrobots** [comment]
For back-porting, it depends. My recommendation would be to request a back-port on the specific PR for the feature/fix you would like in back-ported.

**Comment by vmarchaud** [comment]
After thinking about it i believe it would be easier for anyone wanting to retrieve those metrics (which are critical for every production deployment) without having to parse the `trace_events` stream.

Specially that from my understanding, you can't just get the stream of events continuously, you need to stop it, parse the data to get the metrics, and then re-start it to get new events.

If this is right, i believe my approach will be easier for people that just want to monitor the GC without having to understand how the tracing works IMO.

What do you think ?

**Comment by vmarchaud** [comment]
> The job of node.js itself, it not to make everything easy but to make everything feasible. I would prefer not to implement two ways of doing the same thing, for the sake of making things a bit easier. To take a page from "The Zen of Python".

Totally understandable, i would argue that we sometimes need to provide nicer API for the inspector protocol, for example [a PR is going on to simplify coverage report ](https://github.com/nodejs/node/pull/22527)

However i believe if it's possible that at some point to record continuously for GC metrics in the `trace_events` API, then the job of parsing the stream etc, would be better provided by a 3rd party module.

**Comment by hashseed** [comment]
I too am of the opinion that trace events are more suitable for this purpose. Fleshing out tracing output is still an on-going project, though.

**Comment by vmarchaud** [comment]
@hashseed Is there any on going development somewhere about flushing the tracing data ?

**Comment by vmarchaud** [comment]
Closing since we can receive GC event from the trace events that can be dynamically triggered at runtime
