### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by bnb** [nodejs/diagnostics#226]
Generally working groups have a CONTRIBUTING.md file. I was going to point an individual to it who asked about joining the WG's discussions, but it seems there isn't one at present 😅

**Comment by bnb** [comment]
cc @mannypamintuan, who is the individual ❤️

**Comment by watson** [comment]
Do we have a CONTRIBUTING.md file we can copy from other working groups? I was just looking at the CONTRIBUTING.md file from the post-mortem group, but I don't think it's a good example

**Comment by bnb** [comment]
In my experience with the CommComm initiatives, I've tried to help guide repo creators/maintainers to focus on building out something that's specific to their repo. General strucutre can be copied, but different WGs/teams have different approaches to contributing and even different criteria for what contributing means.

Here's an example from one of the initiatives that is pretty raw and doesn't give specific context (now I'm going to have to fix that 😅) that you could use as a base: https://github.com/nodejs/website-redesign/blob/master/CONTRIBUTING.md
