### ISSUE TITLE
Session at Collab Summit Vancouver 2018

### ISSUE THREAD

**Issue by mcollina** [nodejs/diagnostics#229]
I'm scheduling a session for the diagnostics wg on Day one of the Collab Summit Vancouver as per @yunong request.

Who will coordinate?

# Proposed Agenda

  * tbd, will be added here once agreed, for now see comments in this issue for work in progress/suggestions

**Comment by mhdawson** [comment]
Added to agenda to discuss who will be there and to co-ordinate.

**Comment by mhdawson** [comment]
It is at 3:30 - 5:00 Oct 12

- Start with overview of initiatives, try to get more interest
  

- Working sessions
  - Async terminology
  -

**Comment by mhdawson** [comment]
I'll be there

**Comment by ofrobots** [comment]
Working session proposal: async hooks & promise hooks performance.

**Comment by misterdjules** [comment]
https://docs.google.com/document/d/1UwU2eORCFrN7yCTYWbhjXI963ayMzf0wO1T-n1N4eqw/edit?usp=sharing

**Comment by misterdjules** [comment]
@kjin Do you mind sharing the slides that you presented during the breakout session?

**Comment by kjin** [comment]
Hi @misterdjules, sorry I missed your message. It's probably super late now but fwiw: https://github.com/nodejs/summit/issues/132#issuecomment-429937089

**Comment by misterdjules** [comment]
Thanks @kjin! It seems I need permissions to access that document.
