### ISSUE TITLE
Bump node-clinic to tier 3

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/diagnostics#234]
Right now node-clinic is not yet in any diagnostic support tier. However, recently we ran into issues with 10.10 that could have been detected early on if the clinic test suite would be run on the Node.js infrastructure.

The tool fulfills becomes more and more popular at the moment and bumping it to 3 would likely be the right thing at the moment. That way we are able to guarantee a better stability level overall.

I opened the issue here to discuss it first in the working group before opening a PR to change the tier right away. If there are any questions or if there is any further information necessary, please ask.

@mcollina please also weight in.

**Comment by mcollina** [comment]
Recently we had a case where the generation of flamegraphs was broken in both Node.js 10.10.0 (all the times) and 8.12.0 (in certain cases). I think we are not testing enough those parts of our runtime.

**Comment by mike-kaufman** [comment]
Discussed on Diagnostics WG call on 2018-09-19.  here's a summary:
  - There's some concern here that clinic is too broad and touches too many things, whereas smaller, more targeted tools would be better scoped here.  Is there some existing flame graph tool that could be added to the matrix that would be more targeted and prevent clinic's flame graphs from breaking?
  - is it appropriate to test this via citgm? 
  - can we add tests at an API level to ensure that the flame graphs APIs are working correctly?  i.e., the tests aren't validating clinic itself, but rather are testing APIs clinic depends on.   API tests would have a better chance of moving up to higher tiers (e.g., blocking releases)

Can we get some details on the exact APIs being used by clinic?

**Comment by mmarchini** [comment]
@mcollina could you give a little more context on what broke and why? This would help us understand how to keep it from breaking in the future.

**Comment by richardlau** [comment]
> is it appropriate to test this via citgm?

FYI there's a PR to add it to the default citgm lookup: https://github.com/nodejs/citgm/pull/603

**Comment by mcollina** [comment]
The following commit _not_ being backported broke Node 8.12.0 (I did a [brittle workaround](https://github.com/davidmarkclements/0x/pull/172) on 0x side): https://github.com/nodejs/node/pull/19285 https://github.com/nodejs/node/issues/19260 https://github.com/nodejs/node/issues/22825.

At more or less the same time, flamegraphs broke on Node 10.10 because of https://github.com/nodejs/node/issues/22786 and it was fixed in https://github.com/nodejs/node/pull/22790.

It seems that whole area of Node core is not tested nor validated before a release.

**Comment by joyeecheung** [comment]
Do the tests of clinic pass on all the Node.js release lines that it supports right now?
The majority of `--prof-process` comes from V8 and the breakage may come from V8 as well. https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/buildTimeTrend CITGM has been very red for a long time and I am concerned that adding something that deeply depends on V8 (hence the fix may have to come from V8) would make the situation worse.

**Comment by mhdawson** [comment]
Would a test for the tick profile processor have caught the problem?  Just wondering if we could add a smaller test to cover this case?

**Comment by ofrobots** [comment]
This case needs a test that runs as part of the CI so that V8's integration builds pick it up too. That way we can avoid V8 breaking this functionality in the first place. I would imagine that Clinic could be part of CitGM, but not the CI.

**Comment by richardlau** [comment]
> Would a test for the tick profile processor have caught the problem? Just wondering if we could add a smaller test to cover this case?

Our existing tick processor tests don't catch https://github.com/nodejs/node/issues/22825, so we at least have a coverage gap: https://github.com/nodejs/node/issues/22825#issuecomment-421098700

**Comment by mcollina** [comment]
Filling that coverage gap would solve the immediate problem, yes.

So, we can talk about bumping `--prof-process` up in the Tier hierarchy instead (T3).

**Comment by joyeecheung** [comment]
Bumping `--prof-process` to T3 first sounds more reasonable to me.

**Comment by mhdawson** [comment]
+1 to bump up --prof-process

**Comment by Fishrock123** [comment]
Please bump `--prof-process`. It's shipped with node and should obviously not ship broken.

**Comment by mmarchini** [comment]
I can include `--prof-process` in https://github.com/nodejs/node/pull/22915

**Comment by BridgeAR** [comment]
I am fixing the `tick-processor` tests and I am moving those to the `sequential` tests to run them with each CI. That way we should be able to detect failures early.

Refs: https://github.com/nodejs/node/pull/23100

**Comment by BridgeAR** [comment]
Please definitely bump `--prof-process` to at least T3. To me it seems like it should be even higher since this feature is used frequently.

**Comment by mhdawson** [comment]
@BridgeAR will the updated tick-processor tests adequately  test --prof-process?  I think that is what you are saying but want to be sure.

**Comment by BridgeAR** [comment]
@mhdawson sadly it is not yet testing all things properly but it's a good improvement nevertheless as we'll run them on each CI afterwards. I am also going to write further tests to ensure that all issues we faced so far would have been detected by our tests.

**Comment by BridgeAR** [comment]
Just as a note from the meeting today:

I am going to gather information on what systems `--prof-process` works properly and on what it does not.

We can then go ahead and either document that something is not supported or ideally improve the situation for the specific platform.

**Comment by RafaelGSS** [comment]
Fixed in: #537
