### ISSUE TITLE
Meeting timeslot

### ISSUE THREAD

**Issue by mhdawson** [nodejs/diagnostics#235]
Review the timeslot for the diagnostic WG meeting.

Possibly have 2 timeslots.

I know the current one is a challenge for @gireeshpunathil.  @gireeshpunathil can you comment with whether earlier or later would work better for you?

**Comment by mmarchini** [comment]
A different time would work better for me as well. Either earlier or later works fine for me.

**Comment by Flarna** [comment]
For me the current timeslot is also mostly impossible. it would be needed to move it for at least two hours earlier or later but I fear that this is a problem for others more involved then me.

**Comment by mhdawson** [comment]
2 hours earlier has the potential to overlap with the TSC weekly meeting, but that rotates so it would only be 1 week out of 3 that we would have to avoid.  Would 12 EDT/9Pacific work for people?

**Comment by ofrobots** [comment]
Convenience link to see 0900 PDT in local time: http://www.wolframalpha.com/input/?i=9AM+PDT+in+local+time.

It would be occasionally tricky for me to make this time as I have some childcare duties in the morning, but I am willing to give this a shot. 0930 PDT would work reliably for me.

**Comment by watson** [comment]
I'm in CEST (currently that's UTC+2, but will soon be UTC+1 when we switch back for the winter) and I'm pretty flexible with the meeting time. Basically I can start a meeting any time between 8am and 10pm my local time.

**Comment by BridgeAR** [comment]
I am also in CEST and for me it would be best to move the meeting a bit earlier. 0900 and 0930 PDT would therefore be pretty good.

**Comment by mhdawson** [comment]
or maybe

8, 12 and 5 EDT
5, 9 and 2 PDT
1p, 5p, 10p

**Comment by mhdawson** [comment]
on a cycle 1 off from the TSC meetings

**Comment by hashseed** [comment]
I'm pretty flexible regarding which weekday to choose, but the current time slot is the best I can offer from my evening. I'd like to spend time with my kids until they go to bed, and have about 2 hours until I head to bed as well.

**Comment by suresh-srinivas** [comment]
> or maybe
> 
> 8, 12 and 5 EDT
> 5, 9 and 2 PDT

5am, 9am, and 2pm PDT?

> 1p, 5p, 10p

**Comment by mhdawson** [comment]
@suresh-srinivas correct.

**Comment by mhdawson** [comment]
@gireeshpunathil can you review the feedback so far and then make a proposal that reflects other meetings in the calendar?

**Comment by gireeshpunathil** [comment]
@mhdawson - 9.30 AM PDT looks a perfect slot for everyone, looking at the above comments. I didn't follow the `make a proposal that reflects other meetings in the calendar` part properly - did you mean to ask me to raise a PR to that effect? I don't see a file that stores the calendar info. Or do you mean to ask me to make a proposal that adjusts `other` meetings based on `this` change proposal? if so what are the `other` meetings? please let me know.

**Comment by mhdawson** [comment]
Since its only a few days until the next meeting I'll leave this weeks meeting as is and  I'll update the time for the meeting afterwards (Nov 28 and later)

**Comment by mike-kaufman** [comment]
closing
