### ISSUE TITLE
Diagnostics Best Practices Guide content definition meeting

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/diagnostics#254]
As derived in #211 I have setup a [doodle](https://doodle.com/poll/arsm7kmfp2kfnx5e) with an expiry set for 24th to poll for a consensus on meeting dates. The proposed dates are 27/28/29th of this month. Please cast your availability. Thanks in advance!

/cc @mhdawson @mmarchini @mike-kaufman @joyeecheung @naugtur @amiller-gh @i0natan

/cc @nodejs/diagnostics

**Comment by gireeshpunathil** [comment]
the doodle got only 3 polls, so I guess we need to schedule it for a later date. I will make a new one with revised dates and post it here.

**Comment by gireeshpunathil** [comment]
I started a fresh [poll](https://doodle.com/poll/9f87yt7h5pz9keiq#table) for 16th, please cast your vote, thanks!

**Comment by gireeshpunathil** [comment]
As discussed in the 01/16th meeting, here is a draft table that outlines the top symptoms that we would like to have guides for, and associated tools that I picked up based on understanding about the capability of those. Feel free to:
 - add yourself to the table
 - add items as you deem fit
 - propose amendments if any



 | Symptom Type | Tool/API Name             | Guide developer | Guide priority order |  Remarks |
 |-----------|---------------------------|-------------------------------|-------------------------|-------------|
 |    Memory       |         heapdump                  |                               |                         |             |
 |    Memory       |         heap profiler                  |                               |                         |             |
 |    Crash       |         llnode                  |          @gireeshpunathil                      |                         |             |
 |    profiling       |         v8 profiler                  |                               |                         |             |
 |    profiling       |         linux profiler                  |                               |                         |             |
 |    tracing       |         trace events                  |                               |                         |             |
 |    live debugging       |         inspector                 |                               |                         |             |

**Comment by mmarchini** [comment]
Use cases from Diagnostics Summit

  - Memory leak
  - GC pressure
  - Premature object promotion to old space
  - Event loop saturation
  - Hot code paths
  - ...

**Comment by gireeshpunathil** [comment]
We have been thinking further on how to structure the documentation for user jounrey and the best practices, with a reasonable decoupling between them while making a meaningful association.

Here is what I think we can structure it: the user journey document contains journeys (definition of speicif user story, associated symptoms and external manifestations) and then link it with the specific best practice document that deals with the problem determination of that user journey.

This approach addresses two issues:
 - the user journey document does not get overloaded with too much content
 - improves the discoverability and consumability of the best practices with most relevant document flow

For example:

documentation/user_journeys.md (contains journeys and then points to one of the specific Best practices)

 - documentation/abnormal_termination/
    - /setup.md
    - /investigation_flow.md
      - /step1 - using_exit_stack_traces.md
      - /step2 - using_diagnostic_report.md
      - /step3 - using_lldb.md
    - case_study.md
 - /Memory/
    - /setup.md
    - /investigation_flow.md
      - /step1 - using_heap_dump.md
      - /step2 - using_gc_traces.md
      - /step3 - using_native_tools.md
    - /case_study.md


We can discuss this further in the upcoming diagnostic working group meeting.

cc @hekike @mhdawson

**Comment by hekike** [comment]
Discussed on the WG meeting today that it would make sense to consolidate user journey Google Docs into this structure. I can open a PR after the initial structure is merged in.

**Comment by gireeshpunathil** [comment]
acknowledged, thanks!

**Comment by naugtur** [comment]
Anything covered here: https://github.com/naugtur/node-diagnostics-howtos is available to be added to the guide. I'm hoping to participate as much as my limited free time permits.

**Comment by gireeshpunathil** [comment]
@naugtur - thank you very much for the offer, and the link. Yes, please feel free to pick up any items of your choice!

After several iterations in diagnostic summit and other working group meetings, we frozen on the prioritized content as defined in https://github.com/nodejs/diagnostics/issues/254#issuecomment-460999894 and desired structure as defined in https://github.com/nodejs/diagnostics/issues/254#issuecomment-538853390 . So while your content is highly consumable, it would be great if that can be translated to fit to this style?

**Comment by naugtur** [comment]
I'm happy to get it to be consistent with the structure there. 
Do we have guidelines around tools mentioned in the guides? I don't think we should limit ourselves by avoiding established tools and packages, but I also don't think I should plug my diagnostics experiments package...

**Comment by gireeshpunathil** [comment]
@naugtur - I don't think so (guidance on tools exists); my take is: best tool for the work at hand:
 - open source / free tool vs. proprietary / paid ones
 - proven ones vs. unproven
 - stable vs. under development
 - minimal features but easy to use vs versatile but complex

If there are specific tools you have in mind, let us discuss it here, in case if that helps.

**Comment by mhdawson** [comment]
PR for valgrind guide - https://github.com/nodejs/node/pull/31501. Will PR reference to it into our https://github.com/nodejs/diagnostics/blob/master/documentation/memory/step4/using_native_tools.md doc once it lands.

**Comment by mmarchini** [comment]
I thought the issue was going to be created today. Did it not work?

**Comment by gireeshpunathil** [comment]
me too thought the same. looks like the schedule is not ON. will check with @mhdawson to find out the reason.

**Comment by mmarchini** [comment]
No worries, I'll crate the issue manually this week.

**Comment by gireeshpunathil** [comment]
work is still on

**Comment by RafaelGSS** [comment]
I've added the `never stale` since it's still in the `diag-agenda`
