### ISSUE TITLE
Tier of Support: V8 Sampling Heap Profiler current state

### ISSUE THREAD

**Issue by Drieger** [nodejs/diagnostics#259]
I tried to summarize current state of requisites for `V8 Sampling Heap Profiler`. Requisites are taken from <a href="https://github.com/nodejs/node/blob/master/doc/guides/diagnostic-tooling-support-tiers.md">Tier 1</a> (most complete set of requirements).

There are some requirements that seem to be subjective (at least to me), which means it's not clear if a tool fulfills it or not.

### Requisites
* Must always be working (CI tests passing) for all LTS Node.js
* Have a good test suite
* Test suite job must exist in Node.js CI
* The maintainers of the tool must remain responsive when there are problems (Subjective)
* The tool must be actively used by the ecosystem (Subjective)
* The tool must be heavily depended on (Subjective)
* The tool must have a guide or other documentation in the Node.js GitHub organization or website
* The tool must be working on all supported platforms
* The tool must only be using APIs exposed by Nodejs as opposed to its dependencies
* The tool must be open source.

### Tool Analysis
<table>
    <tr>
        <td align="center"><strong>Name<strong></td>
        <td align="left">V8 Sampling Heap Profiler</td>
    </tr>
    <tr>
        <td align="center"><strong>URL</strong></td>
        <td align="left"><a href="https://github.com/v8/sampling-heap-profiler">https://github.com/v8/sampling-heap-profiler</a></td>
    </tr>
    <tr>
        <td align="center"><strong>Type<strong></td>
        <td align="left">Memory</td>
    </tr>
    <tr>
        <td align="center"><strong>Target Tier</strong></td>
        <td align="left">1</td>
    </tr>
</table>

<table>
    <tr>
        <th>Requisite</th>
        <th>Status</th>
        <th>Observation</th>
    </tr>
    <tr>
      <td align="center">Must always be working (CI tests passing) for all LTS Node.js</td>
      <td align="center">Ok</td>
      <td align="left">Tests are passing and runs on every LTS Node.js</td>
    </tr>
    <tr>
      <td align="center">Have a good test suite</td>
      <td align="center">Maybe </td>
      <td align="left">Test suite exists. Not sure if it is complete yet, based on the following open issues <br /><a href="https://github.com/v8/sampling-heap-profiler/issues/2">https://github.com/v8/sampling-heap-profiler/issues/2</a><br /> <a href="https://github.com/v8/sampling-heap-profiler/issues/14">https://github.com/v8/sampling-heap-profiler/issues/14</a></td>
    </tr>
    <tr>
      <td align="center">Test suite job must exist in Node.js CI</td>
      <td align="center">Fail</td>
      <td align="left">Job do not exist in Node.js CI</td>
    </tr>
    <tr>
      <td align="center">The maintainers of the tool must remain responsive when there are problems</td>
      <td align="center">Maybe</td>
      <td align="left">The tool has a few maintainers. Today mainly active maintainer seems to be @ofrobots</td>
    </tr>
    <tr>
      <td align="center">The tool must be actively used by the ecosystem</td>
      <td align="center">Maybe</td>
      <td align="left">The tool does not seem to be used by a large part of the ecosystem.
                         <br /><strong>[npm] 253 weekly downloads</strong></td>
    </tr>
    <tr>
      <td align="center">The tool must be heavily depended on</td>
      <td align="center">False</td>
      <td align="left">Diagnostic tools are never depended on to run systems. Although it should be interesting to make sure that these tools are never broken, so they can
   be used when necessary. We could try to use npm dependents, but it doesnt't seems to be a good approach</td>
    </tr>
    <tr>
      <td align="center">The tool must have a guide or other documentation in the Node.js GitHub organization or website</td>
      <td align="center">Fail</td>
      <td align="left">No guide or documentation found in the Node.js GitHub organization or website. Project has only a <a href="https://github.com/v8/sampling-heap-profiler#readme">README</a> file in its own repository with a some usage explanation</td>
    </tr>
    <tr>
      <td align="center">The tool must be working on all supported platforms</td>
      <td align="center">Ok</td>
      <td align="left">Works on all platforms where V8 heap profiler is also working</td>
    </tr>
    <tr>
      <td align="center">The tool must only be using APIs exposed by Nodejs as opposed to its dependencies</td>
      <td align="center">Ok</td>
      <td align="left">The tool seems to be using only exposed APIs</td>
    </tr>
    <tr>
      <td align="center">The tool must be open source</td>
      <td align="center">Ok</td>
      <td align="left">The tool is open source under Apache License 2.0 <a href="https://github.com/v8/sampling-heap-profiler/blob/master/LICENSE">https://github.com/v8/sampling-heap-profiler/blob/master/LICENSE</a></td>
    </tr>
</table>

Based on this it is possible to have a more clear view of the current state and what is necessary to work on to move `V8 Sampling Heap Profiler` to target tier. It is also an opportunity to debate if requirements are correct. Any ideas and opinions are welcome.

**Comment by mcollina** [comment]
I think most of the activities are on the Node.js side. 
I'm +1 on moving it to Tier 1, however I'm a bit skeptical to because of the big "Experimental"  warning at the top.
I don't think Tier 1 tools should be experimental.

**Comment by ofrobots** [comment]
Thanks for starting this thread @Drieger. One thing to clarify would be the distinction between the V8 Sampling Heap Profiler API and the user-space module (that I maintain) at https://github.com/v8/sampling-heap-profiler. At first, I think we take the API itself through the rigor to figure out the tier of support. Whether or not my user-space implementation is the best way to consume the V8 API may be a different topic.

An alternative user-space implementation could become better than mine, or alternatively we could argue that this is important enough to bake directly into Node.js itself.

BTW, note that [`@google-cloud/profiler`](https://www.npmjs.com/package/@google-cloud/profiler) uses the code from my module. It has ~80k weekly downloads. The plan is for this module to start directly depending on [heap-profile](https://www.npmjs.com/package/heap-profile) once we have pre-built binaries built and published 

P.S. It would be great to have more collaborators on [heap-profile](https://www.npmjs.com/package/heap-profile). If anyone is interested, let me know.

**Comment by vmarchaud** [comment]
I believe you are referring to https://github.com/nodejs/node/issues/23328.

I will point out the same point as i did for having a API in core for taking heapdump : We already have this API through the `inspector` API, wouldn't be an overhead to maintain both ? 
Or maybe that the solution of having a high level API built on top of `inspector` make sense, maybe in a userland package ? We could also implement the specific case like filtering frame from the inspector itself for profilers (CPU/Heap)
