### ISSUE TITLE
Tier of Support: Linux perf  and V8 --interpreted-frames-native-stack current state

### ISSUE THREAD

**Issue by Drieger** [nodejs/diagnostics#261]
I tried to summarize current state of requisites for `Linux perf`. Requisites are taken from <a href="https://github.com/nodejs/node/blob/master/doc/guides/diagnostic-tooling-support-tiers.md">Tier 1</a> (most complete set of requirements).

There are some requirements that seem to be subjective (at least to me), which means it's not clear if a tool fulfills it or not.

### Requisites
* Must always be working (CI tests passing) for all LTS Node.js
* Have a good test suite
* Test suite job must exist in Node.js CI
* The maintainers of the tool must remain responsive when there are problems (Subjective)
* The tool must be actively used by the ecosystem (Subjective)
* The tool must be heavily depended on (Subjective)
* The tool must have a guide or other documentation in the Node.js GitHub organization or website
* The tool must be working on all supported platforms
* The tool must only be using APIs exposed by Nodejs as opposed to its dependencies
* The tool must be open source.

### Tool Analysis
<table>
    <tr>
        <td align="center"><strong>Name<strong></td>
        <td align="left">Linux perf</td>
    </tr>
    <tr>
        <td align="center"><strong>URL</strong></td>
        <td align="left"><a href="https://github.com/torvalds/linux/tree/master/tools/perf">https://github.com/torvalds/linux/tree/master/tools/perf</a></td>
    </tr>
    <tr>
        <td align="center"><strong>Type<strong></td>
        <td align="left">Profiling</td>
    </tr>
    <tr>
        <td align="center"><strong>Current Tier</strong></td>
        <td align="left">3 (<a href="https://github.com/nodejs/node/blob/master/doc/guides/diagnostic-tooling-support-tiers.md">according to guide</a>)</td>
    </tr>
    <tr>
        <td align="center"><strong>Target Tier</strong></td>
        <td align="left">2</td>
    </tr>
</table>

<table>
    <tr>
        <th>Requisite</th>
        <th>Status</th>
        <th>Observation</th>
    </tr>
    <tr>
      <td align="center">Must always be working (CI tests passing) for all LTS Node.js</td>
      <td align="center">Maybe</td>
      <td align="left">It isn't related specific to Node.js versions. And --perf-basic-prof is working correctly</td>
    </tr>
    <tr>
      <td align="center">Have a good test suite</td>
      <td align="center">Ok</td>
      <td align="left">Tool has a good test suite</td>
    </tr>
    <tr>
      <td align="center">Test suite job must exist in Node.js CI</td>
      <td align="center">Ok</td>
      <td align="left">Test might be found on <a href="https://github.com/nodejs/node/blob/master/test/v8-updates/test-linux-perf.js">test/v8-updates/test-linux-perf.js</a></td>
    </tr>
    <tr>
      <td align="center">The maintainers of the tool must remain responsive when there are problems</td>
      <td align="center">Ok</td>
      <td align="left">As this tool is under Linux development community, maintainers should be fairly responsive. Also --perf-basic-prof is under V8 supervision</td>
    </tr>
    <tr>
      <td align="center">The tool must be actively used by the ecosystem</td>
      <td align="center">Maybe</td>
      <td align="left">Hard to tell as this is an analysis tool that comes with many Linux distributions</td>
    </tr>
    <tr>
      <td align="center">The tool must be heavily depended on</td>
      <td align="center">Fail</td>
      <td align="left">Diagnostic/analysis tools are almost never depended on to run systems.</td>
    </tr>
    <tr>
      <td align="center">The tool must have a guide or other documentation in the Node.js GitHub organization or website</td>
      <td align="center">Fail</td>
      <td align="left">Tool doesn't have any guide in the Node.js Github organization or website. Tool has a good documentaion <a href="https://github.com/torvalds/linux/tree/master/tools/perf/Documentation">https://github.com/torvalds/linux/tree/master/tools/perf/Documentation</a><br />--perf-basic-prof has almost no documentation in organization Github or website</td>
    </tr>
    <tr>
      <td align="center">The tool must be working on all supported platforms</td>
      <td align="center">Fail</td>
      <td align="left">Tool only works on Linux based platforms</td>
    </tr>
    <tr>
      <td align="center">The tool must only be using APIs exposed by Nodejs as opposed to its dependencies</td>
      <td align="center">Ok</td>
      <td align="left">Tools has no dependencies from Node.js. Only dependency we might consider here is to use the `--perf-basic-prof` or related flags</td>
    </tr>
    <tr>
      <td align="center">The tool must be open source</td>
      <td align="center">Ok</td>
      <td align="left">Tool is open source, under the GNU GPL. --perf-basic-prof is under V8 and is open source as well</td>
    </tr>
</table>

Based on this it is possible to have a more clear view of the current state and what is necessary to work on to move `Linux perf` to target tier. It is also an opportunity to debate if requirements are correct. Any ideas and opinions are welcome.

**Comment by mcollina** [comment]
I think we should move `The tool must be working on all supported platforms` to the "if-applicable" category, and relax this for `Linux perf`.

> Diagnostic/analysis tools are almost never depended on to run systems.

This will be true for all tools that are tracked via this process. IMHO `perf` is lightly depended on, as several companies are depending on this to work, e.g. Netflix. We used it quite ofter at NearForm as well.

> Must always be working (CI tests passing) for all LTS Node.js

I think `perf` integration is broken on Node 8, and it's not really fixable. @mmarchini added a flag to fix the data in Node 10+.

**Comment by naugtur** [comment]
As for the docs/guide

I've been working on a guide for flame graphs using perf and it's been almost finished for a while, but I couldn't get it to display correct function names (yes, with the new flags) because of OS support issues. I wanted to figure those out before finally posting. 
I'm hoping to finish it soon

https://github.com/nodejs/nodejs.org/pull/1444

**Comment by Drieger** [comment]
Great @naugtur as soon as it is merged we can update the state here.

**Comment by Drieger** [comment]
As pointed by @mcollina in https://github.com/nodejs/diagnostics/issues/262, it makes more sense to evaluate `perf` and `--interpreted-frames-native-stack` together, so I will move  `--interpreted-frames-native-stack` current state to continue its evaluation here.

### Tool Analysis
<table>
    <tr>
        <td align="center"><strong>Name<strong></td>
        <td align="left">V8 --interpreted-frames-native-stack</td>
    </tr>
    <tr>
        <td align="center"><strong>Type<strong></td>
        <td align="left">Profiling</td>
    </tr>
    <tr>
        <td align="center"><strong>Current Tier</strong></td>
        <td align="left">3 (<a href="https://github.com/nodejs/node/blob/master/doc/guides/diagnostic-tooling-support-tiers.md">according to guide</a>)</td>
    </tr>
    <tr>
        <td align="center"><strong>Target Tier</strong></td>
        <td align="left">2</td>
    </tr>
</table>

<table>
    <tr>
        <th>Requisite</th>
        <th>Status</th>
        <th>Observation</th>
    </tr>
    <tr>
      <td align="center">Must always be working (CI tests passing) for all LTS Node.js</td>
      <td align="center">Maybe</td>
      <td align="left">Flag was added on Node.js v10.x. So since that version, all LTS Node.js should be ok</td>
    </tr>
    <tr>
      <td align="center">Have a good test suite</td>
      <td align="center">Maybe</td>
      <td align="left">Test exists for the feature. I'm not sure if test coverage enough</td>
    </tr>
    <tr>
      <td align="center">Test suite job must exist in Node.js CI</td>
      <td align="center">Maybe</td>
      <td align="left">Tests are run based on V8 (<a href="https://github.com/nodejs/node/blob/master/test/v8-updates/test-linux-perf.js">test/v8-updates/test-linux-perf.js</a>)</td>
    </tr>
    <tr>
      <td align="center">The maintainers of the tool must remain responsive when there are problems</td>
      <td align="center">Ok</td>
      <td align="left">This is mantained as part of V8, so should be ok</td>
    </tr>
    <tr>
      <td align="center">The tool must be actively used by the ecosystem</td>
      <td align="center">Maybe</td>
      <td align="left">No metrics available to define this</td>
    </tr>
    <tr>
      <td align="center">The tool must be heavily depended on</td>
      <td align="center">Maybe</td>
      <td align="left">It is hard to define it, specially if we think that the ecosystem could be only people interested in diagnostics/profiling/... </td>
    </tr>
    <tr>
      <td align="center">The tool must have a guide or other documentation in the Node.js GitHub organization or website</td>
      <td align="center">Fail</td>
      <td align="left">Tool doesn't have any guide in the Node.js Github organization or website.<a href="https://github.com/v8/sampling-heap-profiler#readme">README</a> file in its own repository with a some usage explanation</td>
    </tr>
    <tr>
      <td align="center">The tool must be working on all supported platforms</td>
      <td align="center">True</td>
      <td align="left">Works on all platforms where V8 is also working</td>
    </tr>
    <tr>
      <td align="center">The tool must only be using APIs exposed by Nodejs as opposed to its dependencies</td>
      <td align="center">Fail</td>
      <td align="left">Tool must use some of its dependencies. But it is necessary for this kind of tool</td>
    </tr>
    <tr>
      <td align="center">The tool must be open source</td>
      <td align="center">Ok</td>
      <td align="left">Tool is part of V8</td>
    </tr>
</table>
