### ISSUE TITLE
Tier of Support: V8 --interpreted-frames-native-stack current state

### ISSUE THREAD

**Issue by Drieger** [nodejs/diagnostics#262]
I tried to summarize current state of requisites for `V8 --interpreted-frames-native-stack`. Requisites are taken from <a href="https://github.com/nodejs/node/blob/master/doc/guides/diagnostic-tooling-support-tiers.md">Tier 1</a> (most complete set of requirements).

There are some requirements that seem to be subjective (at least to me), which means it's not clear if a tool fulfills it or not.

### Requisites
* Must always be working (CI tests passing) for all LTS Node.js
* Have a good test suite
* Test suite job must exist in Node.js CI
* The maintainers of the tool must remain responsive when there are problems (Subjective)
* The tool must be actively used by the ecosystem (Subjective)
* The tool must be heavily depended on (Subjective)
* The tool must have a guide or other documentation in the Node.js GitHub organization or website
* The tool must be working on all supported platforms
* The tool must only be using APIs exposed by Nodejs as opposed to its dependencies
* The tool must be open source.

### Tool Analysis
<table>
    <tr>
        <td align="center"><strong>Name<strong></td>
        <td align="left">V8 --interpreted-frames-native-stack</td>
    </tr>
    <tr>
        <td align="center"><strong>Type<strong></td>
        <td align="left">Profiling</td>
    </tr>
    <tr>
        <td align="center"><strong>Current Tier</strong></td>
        <td align="left">3 (<a href="https://github.com/nodejs/node/blob/master/doc/guides/diagnostic-tooling-support-tiers.md">according to guide</a>)</td>
    </tr>
    <tr>
        <td align="center"><strong>Target Tier</strong></td>
        <td align="left">2</td>
    </tr>
</table>

<table>
    <tr>
        <th>Requisite</th>
        <th>Status</th>
        <th>Observation</th>
    </tr>
    <tr>
      <td align="center">Must always be working (CI tests passing) for all LTS Node.js</td>
      <td align="center">Maybe</td>
      <td align="left">Flag was added on Node.js v10.x. So since that version, all LTS Node.js should be ok</td>
    </tr>
    <tr>
      <td align="center">Have a good test suite</td>
      <td align="center">Maybe</td>
      <td align="left">Test exists for the feature. I'm not sure if test coverage enough</td>
    </tr>
    <tr>
      <td align="center">Test suite job must exist in Node.js CI</td>
      <td align="center">Maybe</td>
      <td align="left">Tests are run based on V8 (<a href="https://github.com/nodejs/node/blob/master/test/v8-updates/test-linux-perf.js">test/v8-updates/test-linux-perf.js</a>)</td>
    </tr>
    <tr>
      <td align="center">The maintainers of the tool must remain responsive when there are problems</td>
      <td align="center">Ok</td>
      <td align="left">This is mantained as part of V8, so should be ok</td>
    </tr>
    <tr>
      <td align="center">The tool must be actively used by the ecosystem</td>
      <td align="center">Maybe</td>
      <td align="left">No metrics available to define this</td>
    </tr>
    <tr>
      <td align="center">The tool must be heavily depended on</td>
      <td align="center">Maybe</td>
      <td align="left">It is hard to define it, specially if we think that the ecosystem could be only people interested in diagnostics/profiling/... </td>
    </tr>
    <tr>
      <td align="center">The tool must have a guide or other documentation in the Node.js GitHub organization or website</td>
      <td align="center">Fail</td>
      <td align="left">Tool doesn't have any guide in the Node.js Github organization or website.<a href="https://github.com/v8/sampling-heap-profiler#readme">README</a> file in its own repository with a some usage explanation</td>
    </tr>
    <tr>
      <td align="center">The tool must be working on all supported platforms</td>
      <td align="center">True</td>
      <td align="left">Works on all platforms where V8 is also working</td>
    </tr>
    <tr>
      <td align="center">The tool must only be using APIs exposed by Nodejs as opposed to its dependencies</td>
      <td align="center">Fail</td>
      <td align="left">Tool must use some of its dependencies. But it is necessary for this kind of tool</td>
    </tr>
    <tr>
      <td align="center">The tool must be open source</td>
      <td align="center">Ok</td>
      <td align="left">Tool is part of V8</td>
    </tr>
</table>

Based on this it is possible to have a more clear view of the current state and what is necessary to work on to move `V8 --interpreted-frames-native-stack` to target tier. It is also an opportunity to debate if requirements are correct. Any ideas and opinions are welcome.

**Comment by mcollina** [comment]
I think this tool is a must-use in combination with `perf` https://github.com/nodejs/diagnostics/issues/261, and I do not think we should evaluate this separately from `perf`.

**Comment by Drieger** [comment]
@mcollina I will close this issue and move it to the same one where `perf` is being discussed. I believe this will make it clearer as pointed in your comment.
