### ISSUE TITLE
Node.js Foundation Diagnostics Best practices Meeting 2019-01-16

### ISSUE THREAD

**Issue by mhdawson** [nodejs/diagnostics#270]
## Time

**UTC Wed 16-Jan-2019 15:30 (03:30 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 16-Jan-2019 07:30 (07:30 AM) |
| US / Mountain | Wed 16-Jan-2019 08:30 (08:30 AM) |
| US / Central  | Wed 16-Jan-2019 09:30 (09:30 AM) |
| US / Eastern  | Wed 16-Jan-2019 10:30 (10:30 AM) |
| London        | Wed 16-Jan-2019 15:30 (03:30 PM) |
| Amsterdam     | Wed 16-Jan-2019 16:30 (04:30 PM) |
| Moscow        | Wed 16-Jan-2019 18:30 (06:30 PM) |
| Chennai       | Wed 16-Jan-2019 21:00 (09:00 PM) |
| Hangzhou      | Wed 16-Jan-2019 23:30 (11:30 PM) |
| Tokyo         | Thu 17-Jan-2019 00:30 (12:30 AM) |
| Sydney        | Thu 17-Jan-2019 02:30 (02:30 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Diagnostics%20WorkGroup+Meeting+2019-01-16&iso=20190116T15
* or http://www.wolframalpha.com/input/?i=03PM+UTC%2C+Jan+16%2C+2019+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/12S_nvDFDJ0kgGrtqfBZw_4ormceiiQzXviE2w1rTq-Y/edit>

## Agenda

Extracted from **diag-best-practices-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/diagnostics

* Diagnostics Best Practices Guide content definition meeting [#254](https://github.com/nodejs/diagnostics/issues/254)

## Invited

* Diagnostics best practices meetings: @nodejs/diagnostics

## Notes

The agenda comes from issues labelled with `diag-best-practices-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: https://zoom.us/j/466707925
* For those who just want to watch: youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

**Comment by mike-kaufman** [comment]
Yeah, I won't be able to attend here either, as I have a conflict and my schedule has very limited room.

**Comment by hashseed** [comment]
I'm also unlikely to be able to attend this, unfortunately.

**Comment by hekike** [comment]
Sorry, I had a last minute business meeting and couldn't make it.
