### ISSUE TITLE
Diagnostics Summit 2019 Summer Edition

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#272]
Following Yunong's idea from last year, I would like to host a Diagnostics Summit in the Bay Area next Summer, probably in the same week as [NodeSummit](https://www.nodesummit.com). Dates for the conference are not defined yet, but it will probably be late July.

I spoke with Netflix and they can provide the venue.

**Comment by hashseed** [comment]
I'd be interested. This + Node Summit + chance to visit bay area folks is enough motivation for me to make the trip :)

**Comment by mcollina** [comment]
I’m likely to be around, do we have any news on the dates for NodeSummit?

**Comment by dshaw** [comment]
I pinged the organizers.

**Comment by mmarchini** [comment]
@dshaw any updates from the organizers?

**Comment by mmarchini** [comment]
2019 is over and it's unlikely we'll have any in-person summits this year. Closing, we can start organizing another one when things wind down.
