### ISSUE TITLE
Session at the OpenJS Collaborator Summit?

### ISSUE THREAD

**Issue by mcollina** [nodejs/diagnostics#289]
Hey Folks,

Are we planning to do a session at the Collab Summit?
https://github.com/nodejs/summit/issues/149

M

**Comment by hekike** [comment]
I think it would be a good opportunity to discuss and seek alignment on some of the ideas from the [Proposal to drive Diagnostics WG initiatives through user journeys](https://github.com/nodejs/diagnostics/issues/295)

**Comment by mcollina** [comment]
I think that would be fantastic to have, would you mind to send in a proposal?

**Comment by mhdawson** [comment]
+1

**Comment by hekike** [comment]
Sure, I sent one: https://docs.google.com/forms/d/1GCVcmMKplbhbn1qlESg7fwsxdmP3qHTvW3J2ZTmwCFs/edit#response=ACYDBNhi0SIH7kLgbT1AFUuoEMWJcJCj-ABEyZa85g5MSgWg7vPdcT9hsgg29QW2UNt3BpA

**Comment by gireeshpunathil** [comment]
obsolete, closing
