### ISSUE TITLE
seeking feedback: diagnostic report tooling

### ISSUE THREAD

**Issue by boneskull** [nodejs/diagnostics#301]
I’m working on a toolkit (still unreleased) to help inspect and process diagnostic reports (generated via `process.report`).

I’m hoping to drop in to an upcoming meeting and get some feedback about the current state of the project, and how it can better serve various use-cases. 

Tentative plan:

I’d want to present a couple slides with an overview of the tool’s functionality and goals, then perhaps a quick demo (2-3 minutes).  I’d open it up for questions and general feedback, then ask a few specific questions.  What do you think?

**Comment by mhdawson** [comment]
I think this is a good idea, given the collaborator summit conflicts with the next meeting I'd suggest we think about doing it in the meetin gon June 12th.

**Comment by boneskull** [comment]
Sounds good to me.  I am also available to meet about it during the summit!

**Comment by mhdawson** [comment]
Tagged with diag-agenda, if there is a meeting before the 12th, we will just need to skip it on the agenda

**Comment by boneskull** [comment]
@mhdawson So, the 12th then?

**Comment by mhdawson** [comment]
Will be on the agenda for the 12th.

**Comment by boneskull** [comment]
errr, is that supposed to be now?  maybe I have the wrong TZ.

**Comment by mhdawson** [comment]
Sorry for some reason there was no entry on the Calendar (or any other data anymore). In any case too late for this week so I've re-added to the Calendar for next week.

**Comment by gireeshpunathil** [comment]
I guess the purpose of this issue is resolved? if so can we close this?

**Comment by mmarchini** [comment]
Closing, feel free to reopen if there's anything left to be discussed
