### ISSUE TITLE
Proposal: async stack trace support in v8 CPU profiler / JavaScript profiler

### ISSUE THREAD

**Issue by Raynos** [nodejs/diagnostics#305]
In v12 of nodejs and v8 7.2 "zero cost async stacktraces" were implemented.

https://v8.dev/blog/v8-release-72#async-stack-traces

Currently these are available when doing `err.stack` ; For example:

```
      Error: an error in my code
          at TestHarness.loadIngress (/test-harness.js:127:11)
          at async TestHarness.bootstrap (/test-harness.js:213:25)
```

If I were to look at this in a CPU profile

![image](https://user-images.githubusercontent.com/479538/58596240-a144c780-8273-11e9-9a3c-7d1f891300e3.png)

I would see `loadIngress` at the top of the chart. I do not see `async TestHarness.bootstrap` anywhere in the chart.

I took a CPU profile with `time node --cpu-prof index.js` in node v12.3.1

Would it be possible for the C++ CpuProfiler in v8 to implement async stack traces so that I can see all the async functions that called my code instead of just seeing the non-async stack upto the most recent `await` expression.

It would have to implement the same strategy used in `Error.stack` but when computing a stacktrace to put in the `.cpuprofile` file.

**Comment by hashseed** [comment]
Unfortunately it's not that easy.

The CPU profiler is a sampling profiler that runs in a background thread. It must not access V8's JavaScript heap. The way `--async-stack-trace` works though is to look at the pending async function to string them up.

The best thing I can think of here is to keep an explicit stack of async functions while profiling for access from the sampling thread. That would not be zero cost though.

**Comment by Raynos** [comment]
@hashseed 

Can you explain what " It must not access V8's JavaScript heap." means ?

The CPU profiler needs to take a backtrace to get a stacktrace. This stacktrace needs be symbolicated so that I'm looking at javascript function names and javascript files instead of assembly / C / C++ .

That symbolication needs to read the V8 heap to find FunctionName info and to find the FileName and line number associated.

There are various userland modules that need to read the V8 heap for example given a SharedFunctionInfo v8 object, find the function name
 
 - https://github.com/joyent/mdb_v8/blob/master/src/mdb_v8.c#L3391-L3416
 - https://github.com/uber-node/node-flame/blob/master/lib/heap-reader.js#L228-L241

In my experience with the implementation of [`node-flame`](https://github.com/uber-node/node-flame) which uses `libptrace` it was necessary to do ( source: https://github.com/uber-node/node-flame/blob/master/node_backtrace.linux.cc )

```
ptrace(PTRACE_INTERRUPT)
ptrace(PTRACE_GETREGS)
// read from v8 heap to desymbolicate C++ & javascript function names
ptrace(PTRACE_CONT)
```

We actually had to pause the process because v8 moves functions around in the v8 heap which sometimes made it really difficult to get the function name of a function which v8 was moving due to GC or due to the optimizing compiler.

How does the existing sampling profiler manage to get function names & line numbers without accessing the V8 JavaScript heap ?

Separetly, for my understanding. Does v8 only have one profiler or two ? I can use `node --prof` to get profiling data out, and I can use `node --cpu-prof` ( The `--cpu-prof` flag was very recently added, it calls `StartCpuProfiling` ( https://github.com/nodejs/node/commit/e0e308448240260c207958dfc3dd9245d903af85#diff-2db57efb8e738b054b10d12223f8a34dR321 ) which in turn dispatch a `R"({"id": 2, "method": "Profiler.start"})");` message to the inspector which apparently calls into this ( https://chromedevtools.github.io/devtools-protocol/v8/Profiler ).

**Comment by hashseed** [comment]
The sampling profiler keeps data it needs outside of the JS heap.

**Comment by Raynos** [comment]
I think I understand.

The function name, file name and file number are static information about a JavaScript function that can be kept out of the heap.

It’s also something that can be statically determined.

The async promises chain is something that needs run time information. When you see a stack frame in a stack trace you do not statically know who called the async function in the await.

You would need to find .promise by some mechanism and follow the linked list of promises. This is all runtime information on the current execution of the function.

**Comment by Matt-Esch** [comment]
Of course, an external debugger can stop the world at a (significant) performance cost and read from the heap.

The problem with any form of off-heap instrumentation is that it all has to be eagerly collected. So we would have to be pushing the promise continuations off heap every time we await a promise rather than just referring to the current state of the world.

I'm fairly certain the profiler could read from the heap if it wanted to. You can even have the main js code thread do the work with some stack/pc manipulation if you really wanted to avoid accessing the heap from a different thread. It's probably cheaper than recording the promise stack in the hot path.
