### ISSUE TITLE
Diagnostics Use Case Survey 2019

### ISSUE THREAD

**Issue by hekike** [nodejs/diagnostics#309]
Part of the use case and [user journey driven diagnostics](https://github.com/nodejs/diagnostics/issues/295) and [best practices](https://github.com/nodejs/diagnostics/issues/211) efforts we would like to collect information from the community about Node.js diagnostics use cases. We are planning to use the collected data to decide which diagnostics use-cases we will focus in the first round. The information will be also used to complete the [Node.js WG Diagnostics User Journeys](https://docs.google.com/document/d/1fAvQyelASBK5qkZiF4CP9LXqWxfAAhhSh37iBNKb-GQ/edit) document and to help move out the document from the draft state. 

Please see the proposal for the survey content:
https://docs.google.com/document/d/1T2hGtYcUxLiBZD29daDNvZkgRZi4YPNHwYqZ8YtT0yw/edit#heading=h.6wa1g9fvakxd

We are also looking for distribution channels.

cc @gireeshpunathil @mhdawson

**Comment by gireeshpunathil** [comment]
@hekike - here are some points, feel free to incorporate

4.1 How frequently you get into production anomalies?
 - none so far
 - couple of times an year
 - few times a month

4.2 What do you do when your Node.js deployment has issues?
 - try to debug and fix myself
 - report an issue in the ommunity
 - i have an internal node.js support team
 - i have an external node.js support vendor

4.3 What is your knowledge level on Node.js diagnostics?
 - zero, or little
 - moderate, I understand the Node.js excution environment
 - advanced, I know to use most of the tools, including crash diagnostics

4.3 If we were to develop and deliver diagnostic best practices content, how do you want the format?
 - as a long list of best practices
 - as a case study with real issue
 - as a story telling with lot of examples in it




Section 5. Your Business with Node.js

5.1 How long you have been using Node.js?
 - not yet, seriously considering
 - < 1 year
 - \> 5 years

5.2 How important Node.js is to your business?
 - non-critical, used for trivial tasks with alternatives
 - minimal, but moderately improtant
 - a good share of my business depend on it
 - critical, node.js is startegically improtant for me.

**Comment by Flarna** [comment]
Maybe add a question like "Are diagnostic/monitoring tools used continuously in production or only in case of problems".

**Comment by mhdawson** [comment]
A few questions to add:

How many node instances do you have running in production
* 5 or less
* 5-20
* 20-100
* 100 or more

When you try to debug production issues do you use
* JavaScript Debuggers
* Native Debuggers
* Other JavaScript tools
* Operating system tools

Can you access for production environment directly?


If you cannot access your production environment directly how do you debug/get
information?



When you try to debug and fix production issues, what tools do you use?


What production issues have you most commonly run into?
* out of memory
* crash
* high cpu usage
* hang
* other

**Comment by hekike** [comment]
Thank you for sharing your thoughts, great ideas! I incorporated them into the docs.
Please take a look.

**Comment by gireeshpunathil** [comment]
LGTM!

**Comment by mmarchini** [comment]
Did we share and gather results for this survey, or did it went stale? We could still send it if we want to.
