### ISSUE TITLE
add support for function hooking

### ISSUE THREAD

**Issue by Flarna** [nodejs/diagnostics#316]
During diagnostics summit 03-2019 there was a discussion to add some V8 API to allow to hook into JS functions. The discussion was triggered by a comparison with Java which has APIs to do byte code modification.
The functionality to hook into a function is for sure not the same as the Java functionality but it's anyway not the target to get Java and JavaScript equal.

The followup discussion on summit ended with the result that this would not remove the need for APMs,... to wrap functions so no further activities were done.

I had some thoughts again on this and even if it doesn't remove the need for doing monkey patching/wrapping of functions at various places it still would have a lot benefits:
* Ensures that a function is really just one function - not a wrapped one outside of the module but the cached on internally
* Avoid any `instance of` issues for wrapped constructors
* Allows to hook functions from ES6 modules without the needed of complicated (and currently not supported) module loaders

A function hook would have following needs:
* access `this` object (I don't think it's needed to allow the hook to change that `this` refers to another object)
* access and modify function arguments (including adding/removing arguments)
* access the function return value and allow modification of this one
* access thrown exceptions (I don't think modification of the exception is needed)
* the general mechanism should be capable to support multiple users

@bmeurer Main idea regarding this was from you that time. Any thoughts are welcome.

**Comment by Qard** [comment]
I too am _very_ interested in this possible feature.

I don't think modifying function arguments is actually _needed_ for the APM case, as we just modify callbacks, so we could just use the same hook on the callback too, I think, so long as we can have enough structural awareness of the code to locate it. 🤔 

What scenarios are you thinking of for needing to modify return values?

I think _in theory_ it should be possible to achieve what we need without _any_ need for mutation features, but I haven't done any really deep analysis yet to be sure.

**Comment by Flarna** [comment]
> I don't think modifying function arguments is actually _needed_ for the APM case, as we just modify callbacks, so we could just use the same hook on the callback too, I think, so long as we can have enough structural awareness of the code to locate it.

I think it depends where the hook is applied, on the function or the function template (hope my wording is correct).
A callback may be reused in several independent transactions therefore a single hook will be not able to provide this context. As far as I remember the discussions during summit were also going towards callbacks and it turned out that function hooking will not work there in all cases which further resulted in function hooking is of no help but this is actually not the case.
A function hook with the possibility to modify the arguments could replace the passed callback by a wrapped one (like it's done now by the monkey patched wrapper) or even add a dummy in case none is passed by user to still allow to track how long the operation takes even if the user is not interested in the result in the application.


> What scenarios are you thinking of for needing to modify return values?

I think that mutating the return value (e.g. add some property) should be possible even if it is not needed in most cases. Let's say the return value is some stream so you may want to attach your transaction context there or register some listener/handler. In some special cases it may be also needed to return some proxy object or we have to modify a `Buffer` which may result in a new `Buffer` object.

**Comment by hashseed** [comment]
Do you have a hunch on how much of this can be implemented via Chrome DevTools protocol?

**Comment by Flarna** [comment]
@hashseed I never used Chrom DevTools protocol till now. Do you have a pointer where I could start reading? Do you have specific devtools apis in mind which should be used to implement at least parts of this?

I expect the use of debugger is not intended here as I assume it has quite some performance impact. We would use this a replacement of monkey patching to performance should be equal or better.

**Comment by vmarchaud** [comment]
I think a good starting point would be to look at how [`Runtime.callFunctionOn`](https://chromedevtools.github.io/devtools-protocol/v8/Runtime#method-callFunctionOn) is implemented

**Comment by Flarna** [comment]
@hashseed I think at least parts of it may work via inspector protocol via the debugger domain but this is not matching the production readiness requirement.

**Comment by mmarchini** [comment]
Right now the Debugger domain can introduce a huge overhead. Maybe having it on the `Runtime` domain would make more sense?

**Comment by Flarna** [comment]
There are two phases for the use case I have in mind:
1. instrumentation/placing of a function hook: this happens once during startup/module loading - currently monkey patching is done at this time. Overhead here is not critical.
1. actual call to the function: This happens frequently and overhead should be as low as with monkey patching

I think the code path for (2) has to be as short as possible to reach this target so no indirections via some in-between protocol.

**Comment by theanarkh** [comment]
I think this feature makes a lot of sense. I've been trying to do this in the application layer recently, mainly by getting the source code through `Debugger.scriptpasred` and parsing it into an AST tree, then modifying the AST tree, finally, modified the code by `debugger.setScriptSource`. But it's still in the exploratory stage. It would be nice if V8 supported this feature.
