### ISSUE TITLE
Meeting focus, time and frequency

### ISSUE THREAD

**Issue by hekike** [nodejs/diagnostics#319]
Recently the number of attendees on the recurring WG meeting dropped significantly.
What could we do to make this meeting more useful?

- Should we change the time? (from http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Diagnostics%20WorkGroup+Meeting+2019-07-17&iso=20190717T17)
- Should we reduce the frequency? (from bi-weekly to monthly?)
- Should we change the style? And do more deep-dive kind of meetings focused around one-two topics?
- Other suggestions?

@nodejs/diagnostics

**Comment by Flarna** [comment]
For me the timeslot is a serious problem. A few hours earlier would be possible for me - but as far as I can remember there was a poll a few month ago where this was not possible for a lot other people in general more involved then me.

**Comment by mhdawson** [comment]
I think a once every 3 weeks regular meeting and then try to schedule "working" type meetings as needed to make progress on specific issues would make sense.

**Comment by mike-kaufman** [comment]
Sorry I have been unable to attend meetings lately - I have a number of other commitments which are really requiring all of my time lately. :(

**Comment by hashseed** [comment]
The current time slot is the worst choice possible for me. An hour later would work a lot better for me.

**Comment by Qard** [comment]
I've been in Asia for the last month and a bit, and will be for another month. The current times are middle of the night for me, so I've been skipping them all.

I would vote _against_ reducing the frequency, but I _do_ feel we have a problem with the meetings getting rather repetitive as we've had several things stay on the agenda for months and months. We should probably drop a bunch of those from the regular agenda and mark them for only occasional check-in or async-only updates until they become more active again. Half of every meeting seems to be "Any changes on X? No? Moving on..."

Also, 👍 for more deep-dives. Even quick or more basic ones would be great to benefit those following along from the sidelines.

**Comment by hekike** [comment]
Thank you for the input, I appreciate it. Sounds like there would be interest in both rethinking the time and trying out new forms as well in the future. I'll propose some deep drive ideas based on running topics and we could try that form. About the time, @mhdawson do you have the vote and results at hand?

**Comment by mhdawson** [comment]
Not sure what you mean by " vote and results"?  I don't think we've done any sort of poll/vote on times lately.

**Comment by hekike** [comment]
Ohh, I must have misunderstood something. In this case, I think we should start with a vote :)
Should we use Doodle or what's the preferred way? Also, what are the constraints? I guess it cannot conflict with any other Node.js meeting.

**Comment by mhdawson** [comment]
Right, it can't conflict with any other Node.js meeting and we should have options that are feasible for both Pacific and European times.  Doodle has commonly been used. A spreadsheet which lets people fill in times that work for them has also been used by the TSC and CPC.

**Comment by mhdawson** [comment]
@nodejs/diagnostics if you are not making the meeting, please post in this issue some times/days you could make and we'll see if we can figure out a better time

**Comment by gireeshpunathil** [comment]
would like to resurrect this and see some actions. current time is not very good for me, would like to have it a couple of hours earlier, if others are good with that too.

**Comment by mhdawson** [comment]
@gireeshpunathil can you work with @hekike to propose a new time?

**Comment by Qard** [comment]
The time sucks for me too. I'll be living in Asia for awhile, so it's basically middle of the night for me. 😬

**Comment by gireeshpunathil** [comment]
Given the general demand for a change in the meeting time (plus couple of recent cancellations due to thin attendance) I have set up this doodle to collect consensus. Hope the the options provide a meaningful range across the timezones of the team. Let me know if I did some bad choice of selections. thanks!

https://doodle.com/poll/pk8kmbq7zsrm6fh4

cc @nodejs/diagnostics Request to complete this in one week's time, so that we can implement this for the upcoming one.

**Comment by mhdawson** [comment]
@gireeshpunathil that doodle seems to be in UTC which I think may confuse people.  I believe there is an option that will show the time in people's local timezone.

**Comment by gireeshpunathil** [comment]
@mhdawson - modified doodle here: https://doodle.com/poll/6u5e88hxg28g6aun . Hope this is better now?

**Comment by mmarchini** [comment]
Is the doodle still up? I'm getting

![img-2020-01-02-121009](https://user-images.githubusercontent.com/4048656/71690197-e0328280-2d58-11ea-82e8-419d0388acdf.png)

**Comment by mhdawson** [comment]
@gireeshpunathil probably a good time to send out a new doodle and see if we can find a good time.

**Comment by gireeshpunathil** [comment]
@mmarchini - the doodle you refer is expired in December. We did not get a meaningful time slot with the folks who voted in there, so we will need to redo it anyways.

@mhdawson - sure, let me setup one again

**Comment by mhdawson** [comment]
I think this can be closed as we've moved meeting time, have more participants.
