### ISSUE TITLE
Thoughts on the function implementation hiding proposal (stage 2 tc39)

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#329]
I'm looking for thoughts from APM vendors and users who rely heavily on observability tools in production on the [function implementation hiding proposal](https://github.com/tc39/proposal-function-implementation-hiding). I'm also looking for thoughts from Node.js collaborators on how this feature would be used in core (for example, do we want to hide implementation details from functions on `lib/internal`?). This proposal is currently on stage 2, but it might move to stage 3 based on the notes from the last tc39 meeting (https://github.com/tc39/tc39-notes/blob/master/meetings/2019-07/july-24.md#update-on-function-implementation-hiding).

The summary of the proposal is:

> In practice, this directive currently hides the source text revealed by Function.prototype.toString and position information and calling behavior revealed by Error.prototype.stack. It may be expanded in the future as new implementation leakages are discovered or added to the language.

I can see users who will be happy about having internal details hidden from their stack traces, but I can also see users (including myself) who would like the option to still see the full stack trace.

I guess the changes to `Error.prototype.stack` will be the one affecting most users (for example, users who log their errors to a centralized log solution like logstash or fluend, or users who rely on error monitoring tools like Sentry). This will also affect `diagnostics-report`, since the stack trace we get there comes from `Error.stack`.

I imagine `Function.prototype.toString` will also break APM vendors based on discussions from the last diagnostics summit.

Am I missing any diagnostics-related use case?

(cc @nodejs/diagnostics for visibility)

**Comment by Flarna** [comment]
Thanks for reaching out!

We don't use `Function.prototype.toString` in our product at this time and we have nothing on the roadmap which has the need for it. Therefore this part of the proposal has no impact to us.

The changes on `Error.prototype.stack` has impact. We capture stack traces regularly and correlate them with transactions to add so called "code level visibility" on monitored transactions (somehow like a sampling profiler). If there are just a few internal functions hidden it should be no big deal but in worst case users no longer get useful information which code parts contribute to their transactions (but a lot customers ask for this).

Additionally we think about using stack traces also to get insight on what code is executed outside of monitored transactions (e.g. background/ambient activity).
Reason for using stack traces also for background activity instead v8 CpuProfiler is that CpuProfiler can't distinguish between transaction/background and besides that it we have seen unacceptable high overhead in some usecases.

According to the proposal [devTools are not effected](https://github.com/tc39/proposal-function-implementation-hiding#how-does-this-affect-devtools-or-other-methods-of-inspecting-a-functions-implementation-details), they don't have to hide anything. The proposal mentions e.g. `console.log` which seem to be seen as DevTool there.
Based on this it's unclear to me how this proposal effects built in diagnostic tools (e.g. v8 CpuProfiler) and also if some new v8 Api will offer to get the "diagnostics stack" (maybe just native, not mapped to JS) which again has full details to enable development of user land DevTools.

Node.Js includes the inspector module therefore this proposal makes it not impossible to get the information hidden - it's just getting harder and most likely with more overhead.

**Comment by Qard** [comment]
Same here, `Function.prototype.toString` is not not used. The changes to `Error.prototype.stack` also should not _break_ our stuff, we'd just be missing some frames that could still be useful.

I'm unclear though how it interacts with the non-standard `Error.captureStackTrace(...)` function--we use that in several places.

**Comment by misterdjules** [comment]
@Flarna Thanks for the detailed info!

> The proposal mentions e.g. console.log which seem to be seen as DevTool there.

IIUC, it does mention `console.log` _only_ for the use cases of logging functions instances, not for outputting error stack traces.

For stack traces, they mention:

> What error stack traces the developer eventually sees on their screen when an unhandled exception or rejection occurs (which don't have to be related to JavaScript-exposed .stack strings).

which I think does _not_ cover the use case of `console.log(new Error('boom'))`.

Was that your understanding as well?

**Comment by Flarna** [comment]
My understanding is that `console.log(fn)` is just a sample of a dev tool which is not effected by this proposal.
If this is allowed that it prints what we now get via `fn.prototype.toString()` but `console.log(fn.prototype.toString())` would print something different its a clear indication that there must be some sort of API for the embedder to get the "real" information.

Similar I interpret the proposal that it is still allowed that `console.log(new Error('boom'))` prints a stack trace like now but `console.log(new Error('boom').stack)` would print something different.

My understanding is that the proposal only modifies what `Function.prototype.toString()` and `Error.prototype.stack` return but it also allows to expose new APIs to retrive the same information by some other means (to allow dev tooling).
It's up to the embedder if/how these new Apis are exposed. I would expect that browsers choose a different path in this then node.

**Comment by jkrems** [comment]
I would hope that node doesn't hide internal functions in stack traces, at least not by default. Adding highlighting when printing them is one thing but hiding the internal callsite in production error reporting (which most likely is using `err.stack` today) seems problematic.

I wouldn't expect node to make use of this mechanism itself.

**Comment by misterdjules** [comment]
@Flarna I think I was overlooking that the fact that _currently_ `console.log` relies on the `Error.prototype.stack` accessor does not imply that it has to rely on it in the future. Thank you for helping me realize that :)

I'm still wondering how the node platform would enable dev tools liek `console.log` to inspect error stack traces without any information hiding while preventing application code from doing so.

**Comment by Flarna** [comment]
One could argue that the proposal is fulfilled if the APIs in question are not visible on JS surface, just as native API from v8. Not sure what a lawyer would think about this :grin:

On the other hand Node allows JS code to access the debugger (and more) via inspector protocol - it is hard to implement and has a lot overhead but there is in fact no 100% protection.

A little bit off topic: I think a structured approach to handle such conflicting requirements could be to define a Tooling API on language level like Java/.NET have it.

**Comment by Qard** [comment]
More powerful tooling around that would _definitely_ be _very_ cool. :)

**Comment by misterdjules** [comment]
@Flarna 

> One could argue that the proposal is fulfilled if the APIs in question are not visible on JS surface, just as native API from v8.

That's exactly what I'm not sure about. I asked some clarification on this at https://github.com/tc39/proposal-function-implementation-hiding/issues/28.

**Comment by hashseed** [comment]
As a rule of thumb we generally like to keep V8's C++ API not more powerful than the JS to avoid future issues. We've been bitten a few times because the C++ API behaves differently or has more capabilities than JS, and spec changes do not consider the C++ API.

**Comment by Flarna** [comment]
@hashseed I would not vote for different behavior of "same" API but there could be a C++ API which is not mapped to JS.
There are several APIs not mapped to JS, e.g. `CpuProfiler` or `Function::GetInferredName()`.

**Comment by mmarchini** [comment]
> A little bit off topic: I think a structured approach to handle such conflicting requirements could be to define a Tooling API on language level like Java/.NET have it.

@Flarna do you mind sharing more about Tooling APIs on Java/.NET for those (like myself) who are not familiar with it? It sounds interesting. (could be in another issue, so we keep the discussion focused on this).

**Comment by Flarna** [comment]
@mmarchini 
JVM Tooling Interface: https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html
.NET Profiling: https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/profiling-overview#profiling_api

**Comment by misterdjules** [comment]
@hashseed When the proposal at https://github.com/tc39/proposal-function-implementation-hiding is implemented, would the V8 team be open to provide a way to access detailed information about JS Error stack frames representing functions marked as "sensitive" from a V8 API available to native Node.js add-ons?

**Comment by joyeecheung** [comment]
It seems plausible to expose the "sensitive" field to the `Local<Array> sites` passed to `PrepareStackTraceCallback` set by embedders, in that case embedders who set this callback (like Node.js) can choose to omit the sensitive stack traces themselves when generating the string returned in the callback.
