### ISSUE TITLE
should Node core maintain a JSON schema for diagnostic report files?

### ISSUE THREAD

**Issue by boneskull** [nodejs/diagnostics#362]
I don't think it'd be a _bad_ thing, and may let consumers more accurately parse and validate them.  It may also help Node core test itself, by asserting the output matches the schema.  There's a maintenance overhead, of course, and we'd probably want to vendor a module (like [ajv](https://npm.im/ajv)) to assist us with testing it.

- Here's a [naive implementation of a JSON schema for v2](https://github.com/IBM/report-toolkit/blob/d3dbb7b265224c690b0efa2849dcfbe3134af30a/packages/common/diagnostic-report-v2.schema.json) I just created
- And here's source, a [the TypeScript definition file](https://github.com/IBM/report-toolkit/blob/d3dbb7b265224c690b0efa2849dcfbe3134af30a/packages/common/diagnostic-report.d.ts)

(For the curious, the [@types/node](https://npm.im/@types/node) folks will support this definition file once diagnostic reports is stable.  I'm "maintaining" it in the meantime.)

**Comment by boneskull** [comment]
I'm not sure how we'd want to _ship_ such a thing, since IMO it shouldn't come down with the main distributable.

**Comment by mhdawson** [comment]
@boneskull could it be considered as part of the api documentation and be "shipped" through a reference in the API sections related to report?

**Comment by boneskull** [comment]
@mhdawson I think that’s a good idea, but it should be versioned and distributed on npm as well since the main use case is for machines. I don’t know if there’s a precedent for this sort of thing

**Comment by mhdawson** [comment]
I'm not aware of us doing anything like this except for things like the headers which are based on the Node.js version.
