### ISSUE TITLE
proposal: elevate diagnostic report to tier1

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/diagnostics#369]
refs: https://github.com/nodejs/node/blob/master/doc/guides/diagnostic-tooling-support-tiers.md

diagnostic report meets all the criteria required for being tier1, namely:

 - The maintainers of the tool must remain responsive when there are problems; tool is part of the core, so maintainers are node core collaborators itself.
 - The tool must be actively used by the ecosystem; evidence of usage in the field - through core and help repo issues, as well as in person feedback in collab summit 2019 montreal
 - The tool must be heavily depended on; subjective, but report is being established as a unique FFDC capability that helped many issues so far.
 - The tool must have a guide or other documentation in the Node.js GitHub organization or website; - API guide exists part of the org, and several external documentations.
 - The tool must be working on all supported platforms; achieved
 - The tool must only be using APIs exposed by Nodejs as opposed to its dependencies; and
- The tool must be open source. achieved

I propose to elevate report to tier1 status.

**Comment by hekike** [comment]
On the WG meeting, we decided to ping the working group members then wait 7 days before we open a PR with tier bump.

**Comment by mmarchini** [comment]
cc @nodejs/diagnostics

**Comment by richardlau** [comment]
> I propose to elevate report to tier1 status.

The current https://github.com/nodejs/node/blob/master/doc/guides/diagnostic-tooling-support-tiers.md#diagnostic-tooling-support-tiers doesn't mention diagnostic report at all, so this would be adding diagnostic report as tier 1 rather than elevating it. 

[`node-report`](https://github.com/nodejs/node-report), the precursor to diagnostics report is on the list but doesn't meet the tier 1 criteria.

**Comment by gireeshpunathil** [comment]
> The current https://github.com/nodejs/node/blob/master/doc/guides/diagnostic-tooling-support-tiers.md#diagnostic-tooling-support-tiers doesn't mention diagnostic report at all, so this would be adding diagnostic report as tier 1 rather than elevating it.

I don't understand - can you elaborate? `diagnostic report` is the in-core version of `node-report`, right? reference: https://github.com/nodejs/node/pull/22712 

the guide does not mention diagnostic report, because:
 - the guide predates the report
 - the report was renamed as part of https://github.com/nodejs/node/pull/22712

**Comment by richardlau** [comment]
They've diverged and `node-report` still exists (and will probably still exist until Node.js 10 goes End-of-Life). Any tooling or guides written for diagnostic report would not automatically apply to `node-report` (and vice versa).

**Comment by gireeshpunathil** [comment]
ok - so you are talking about the grace period when both (node-report and diagnostic-report) will co-exist due to logistical / policy related reasons.

I am talking about diagnostic-report as a replacement of node-report (reasons and background in the first comment of https://github.com/nodejs/node/pull/22712) which is a result of endorsement from this working group. I am seeking a similar endorsement in this WG to replace node-report from the (unclassified) tooling tiers with diagnostic-report as classified.

**Comment by gireeshpunathil** [comment]
this is achieved, closing. thanks all!
