### ISSUE TITLE
COVID-19 and WG sittings

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/diagnostics#370]
We disucssed about any potential revision in our WG sittings in view of the `COVID-19/Novel Coronavirus situation`. This issue is to gather member status of their ability to attend, and derive at a decision. Please share your views and / or choice. Safety and health of our attendees is our top priority over anything else.

 - business as usual, continue with the same (fortnightly) cadence
 - business as usual, re-assess / re-check the situation in every sittings
 - run on light-weight mode (skip deep dives)
 - cancel regular calendar indefinitely
 - something else

**Comment by gireeshpunathil** [comment]
my work is not affected as of now. I opt:
 - business as usual, re-assess / re-check the situation in every sittings

**Comment by mmarchini** [comment]
business as usual, re-assess / re-check the situation in every sittings

**Comment by mmarchini** [comment]
GitHub needs a poll feature :)

**Comment by jasnell** [comment]
Business as usual for the most part.

**Comment by Flarna** [comment]
Business as usual, just work from home now.
Meeting time did not match for me till now - this hasn't changed either.

**Comment by legendecas** [comment]
business as usual, re-assess / re-check the situation in every sitting

**Comment by Qard** [comment]
Another point for business as usual.

**Comment by hekike** [comment]
business as usual

**Comment by mhdawson** [comment]
Business as usual for me.

**Comment by gireeshpunathil** [comment]
almost converging to `Business as usual`, but let us keep it open for one review in the next meeting before closing

**Comment by mmarchini** [comment]
Let's close this for now, but if anyone is having trouble coping with the situation alongside the meeting frequency, feel free to reopne/open another issue or to reach out to me directly (if you don't want to share it publicly) on the nodeslackers channel or IRC.
