### ISSUE TITLE
npm audit vulnerability in version 14

### ISSUE THREAD

**Issue by shpraveen** [nodejs/diagnostics#382]
Dear Team,

npm audit --fix says

Some vulnerabilities require your attention to resolve.

I tried a lot but still it persists. 

below is the complete log:
"
D:\Workspace_UI\ps\js-demo>npm audit --fix

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   lite-server [dev]

  Path            lite-server > browser-sync > chokidar > fsevents >
                  node-pre-gyp > mkdirp > minimist

  More info       https://npmjs.com/advisories/1179

  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   lite-server [dev]

  Path            lite-server > browser-sync > chokidar > fsevents >
                  node-pre-gyp > tar > mkdirp > minimist

  More info       https://npmjs.com/advisories/1179

  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   lite-server [dev]

  Path            lite-server > browser-sync > chokidar > fsevents >
                  node-pre-gyp > rc > minimist

  More info       https://npmjs.com/advisories/1179

  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   lite-server [dev]

  Path            lite-server > minimist

  More info       https://npmjs.com/advisories/1179

found 4 low severity vulnerabilities in 3504 scanned packages
  4 vulnerabilities require manual review. See the full report for details.

D:\Workspace_UI\ps\js-demo>
"

**Comment by DanielRuf** [comment]
Hi,

This is a problem with npm,  not node itself.
So this should be reported at https://github.com/npm/cli/issues

**Comment by mmarchini** [comment]
As Daniel said, the issue is on `npm`. It also has been fixed on more recent versions of npm and Node.js. Closing.
