### ISSUE TITLE
New chairman election

### ISSUE THREAD

**Issue by hekike** [nodejs/diagnostics#392]
Hi,

due to my daily job, I've less time recently to focus on this working group and I would like to hand over the chairmanship to someone who has both the expertise and is passionate about the future of Node.js diagnostics. I feel extremely lucky that I could be part of this journey and work with you in the last 1-2 years. Thank you all! In the future, I expect that I'll have less time to be involved with Node.js in general but I hope from time to time I'll be able to contribute back.

**About the Chairmanship**

I don't think we summarized before what this working group expects from a chairman, but to give an idea for people who are interested let me share my own reflections. I see the chairman as a person who helps to orchestrate the work of the group by sharing context, making clarification questions, organize and run meetings, and takes notes to be accountable. The chairman is not here to tell people what to do or assign tasks to members, this is an open-source project. The chairman is here to help the group to align on priorities, work, and shared vision by organizing and facilitating conversations.

**About the Election**

We discussed the chairmanship election process on our [May 20, 2020 working group meeting](https://docs.google.com/document/d/1n9Y82Q5YOWJun5X9-piLfhyob3lTodu9o7T9u5NtwDY/edit) and we decided to open a GitHub issue (this one) to see who else would be interested to orchestrate the Node.js Diagnostics work.

@gireeshpunathil and @mmarchini expressed their interest in our last meeting to take over the position in a co-chairman structure. A benefit of having more than one person for this position could be more flexibility around timing and organizing our meetings.

If you would be interested in chairmanship or you have a thought about the election process please comment on this issue. We expect to keep this issue open for a week.

cc @nodejs/diagnostics

**Comment by gireeshpunathil** [comment]
this has been open for 2 weeks, so closing with @hekike 's proposal as consensus. I guess it is worth to document the name of the chairs in the README.md?
