### ISSUE TITLE
Documentation for format of heapdump files

### ISSUE THREAD

**Issue by osher** [nodejs/diagnostics#394]
Hi all.

I'm trying to access the information in heapdump files programmatically, so I'm looking for the place where the format of these files is documented or packages that facilitate the work with this format from which I can reverse engineer what I'm looking at.

Any help will be appreciated!

Thanks in advance!

**Comment by naugtur** [comment]
It's a feature of V8 so I'd start looking there.

**Comment by addaleax** [comment]
Fwiw, the Node.js test suite also contains a (naïve) parser for the format: https://github.com/nodejs/node/blob/08892fc0c488a4205f2880acda250af4a922aa51/test/common/heap.js#L17-L86

**Comment by mmarchini** [comment]
It is not documented by V8 (or at least it wasn't last time I checked) and AFAIK there's no stability guarantees for the format.

This seems worth a @nodejs/v8 ping: is the V8 heap snapshot format documented anywhere? Does it have any stabilities guarantees?

**Comment by victorgomes** [comment]
@mmarchini : The heap snapshot is not documented anywhere, since it is tied to very internal optimisations. We don't provide any stabilities guarantees.

**Comment by mmarchini** [comment]
As such I'll be closing this issue. Feel free to reopen if there's anything else to be discussed.
