### ISSUE TITLE
meta: meeting frequency to be reflected in the calendar

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/diagnostics#395]
today (10-06) it was just @legendecas and me in the meeting, so we cancelled it after 10 minutes.

looks like part of the problem is that we don't have an invite for the meetings on every other week, so it is very easy for folks to miss out.

@mhdawson - can you please adjust the node.js calendar, so that we get invites on a weekly cadence?

**Comment by Qard** [comment]
It'd be nice to have reminder issues for it too. I checked for an issue this morning to find the zoom link but nothing was there so I just gave up. 🤷

**Comment by gireeshpunathil** [comment]
tracked in #396 , so closing
