### ISSUE TITLE
Proposal: create meeting issue for Deep Dives

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#396]
Does anyone opposes to it? I think it would be a good way to remind us when the meeting is happening, as well as coordinate prior to the meeting on what we'll be discussing. We can start creating it manually, and if it works well we can include it on the automated issue generator.

**Comment by Qard** [comment]
Yep, that'd be handy. I missed the meeting today because I couldn't find an issue with the zoom link.

**Comment by gireeshpunathil** [comment]
partly addressed by https://github.com/nodejs/create-node-meeting-artifacts/pull/93 , by transforming the best practices meeting to deep dive meetings. landing this, and scheduling will complete the action I guess.

/cc @mhdawson

**Comment by mhdawson** [comment]
Landed and added to schedule for generation. We'll see if it generates correctly next deep dive.
