### ISSUE TITLE
Node.js Diagnostics Deep Dive Meeting 2020-07-01

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#402]
## Time

**UTC Wed 01-Jul-2020 16:30 (04:30 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 01-Jul-2020 09:30 (09:30 AM) |
| US / Mountain | Wed 01-Jul-2020 10:30 (10:30 AM) |
| US / Central  | Wed 01-Jul-2020 11:30 (11:30 AM) |
| US / Eastern  | Wed 01-Jul-2020 12:30 (12:30 PM) |
| London        | Wed 01-Jul-2020 17:30 (05:30 PM) |
| Amsterdam     | Wed 01-Jul-2020 18:30 (06:30 PM) |
| Moscow        | Wed 01-Jul-2020 19:30 (07:30 PM) |
| Chennai       | Wed 01-Jul-2020 22:00 (10:00 PM) |
| Hangzhou      | Thu 02-Jul-2020 00:30 (12:30 AM) |
| Tokyo         | Thu 02-Jul-2020 01:30 (01:30 AM) |
| Sydney        | Thu 02-Jul-2020 02:30 (02:30 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Diagnostics%20WorkGroup+Meeting+2020-06-17&iso=20200617T16
* or http://www.wolframalpha.com/input/?i=04PM+UTC%2C+Jun+17%2C+2020+in+local+time

## Links

* TBD

## Agenda

We'll be continuing the Deep Dive on User Journeys. This week's topic still to be decided.

## Invited

* Diagnostics team: @nodejs/diagnostics

Use emojis to let us know who's attending!

:+1: attending
:-1: not attending
:confused: not sure if will make it

## Joining the meeting

* link for participants: https://zoom.us/j/466707925
* For those who just want to watch: 
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

**Comment by mmarchini** [comment]
I left the agenda items out since I don't believe we'll be discussing neither of those two issues in this meeting. With that being said, I didn't think of a particular topic to discuss yet. The last one we discussed was the Performance Use Case: https://docs.google.com/document/d/1Yip9zU_8axfZwN-clGMeoNWVYHZPfBjepLV3Ur2JjwA/edit#, and I think we're mostly done with it. I encourage folks to read it before the meeting and comment here if we left anything out or if you think there's still room for discussion. I'll do the same.

Any suggestions on which topic to discuss next? So far we covered [Performance](https://docs.google.com/document/d/1Yip9zU_8axfZwN-clGMeoNWVYHZPfBjepLV3Ur2JjwA/edit?usp=sharing), [Memory Leaks](https://docs.google.com/document/d/16PeoMhREmJxSbrpyom9Uypl2lJuMsqAfB96oocDTPwQ/edit?usp=sharing), and [Process Crash](https://docs.google.com/document/d/1Yip9zU_8axfZwN-clGMeoNWVYHZPfBjepLV3Ur2JjwA/edit?usp=sharing). _Unexpected behavior_ seems like a good candidate to discuss next? Or we could talk about how to start moving the content we already have to the website (I suggested we can add a Diagnostics cateogry on https://github.com/nodejs/nodejs.dev/issues/775, we just need to figure out how to coordinate the content we generate here to submit there), although this could also be discussed in the regular meeting (in which case I'll add `diag-agenda` to the issue).

**Comment by Qard** [comment]
There's the unified hooks discussion I'd like to continue. We could use this session for that.

**Comment by mmarchini** [comment]
@Qard the idea was for the deep dives to focus on User Journeys and documentation. I believe the undefined hooks discussion would fit better at the standard meeting (but I'm open to switch the deep dive to talk about unified hooks if folks are more inclined for that this week).

**Comment by Qard** [comment]
I don’t want to replace the whole main meeting though, and it seemed like there wasn’t anything specific planned for the deep-dive this week.

**Comment by mmarchini** [comment]
No worries, I should've been more clear that we'd be deep diving into the User Journeys, it's just not decided what user journey we'll be talking about or if we'll talk about how to start turning the user journeys into consumable content for customers. We usually define the topic during the first few minutes of the meeting, but I thought bringing the options to the issue (now that we have a meeting issue) would help everyone organize and prepare for the meeting.
