### ISSUE TITLE
Migrate meeting generation to https://github.com/pkgjs/meet?

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#404]
This was brought up in the TSC repo, but might be a good idea for us too. The `pkgjs/meet` Action can be used to generate meeting issues from templates. On the plus side, the issue template will live in our repository. On the other hand, it might be less synced with the Foundation calendar (I'm not sure if the current approach ensures sync between issues and calendar though). Should we try it? Since we have two distinct meetings, we could try generating for one first (maybe the deep dive), and if it works well we can move the other meeting too. I think the Web Frameworks WG is already using this Action.

**Comment by legendecas** [comment]
If I remember correctly, the current meeting issue is generated according to the calendar by some pre-defined format - that is to say, if the calendar event format is not recognizable to the generator, there will be no issue generated for that. I have a peek into the generator repo once but can not find it again. /cc @mhdawson since he's the author of the automated meeting issue generator IIRC.

**Comment by mhdawson** [comment]
It is automatically generated based on the nodejs.org/calendar. I think the major thing missing is in the action used by the web frameworks team is the generation of the google doc (or alternative) for the minutes. If I was the host I'd keep using the existing automation so I would not have to generate the minutes doc manually, but its up to chair of each meeting as to what they want to do.  So just to say whatever works for @mmarchini and @gireeshpunathil who have volunteered to chair the diagnostics meetings.

**Comment by mmarchini** [comment]
In theory we could turn the current script into an Action and keep the templates on the repository, but yeah I don't think it's super urgent. If we want to try something I think we can leverage the fact that we have two meetings, so we can try an experimental tool on the deep dive meetings first.

**Comment by mmarchini** [comment]
also tbh I would like to try something different from Google Docs where we can still collaborate in real time but that respects markdown syntax, so it's easier to publish to GitHub later.

**Comment by mhdawson** [comment]
@mmarchini that has been a long standing request (something with markdown support).  The main challenge with re-using the existing script is the credential setup but that should be possible.

**Comment by mmarchini** [comment]
Repository Secrets should solve the credentials issue :)

**Comment by mmarchini** [comment]
Once https://github.com/pkgjs/meet/pull/30 lands we should be able to use the `meet` Action for deep dives. We still need https://github.com/pkgjs/meet/issues/29 for regular meetings though.
