### ISSUE TITLE
How I can help?

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/diagnostics#410]
Hello!

The topics that @nodejs/diagnostics uses are so helpful for me. And I interested to help the team as I can, but I'm a bit confused to start.

- I read the doc and the topics that you are coordinating
- I started (today) to see the meetings every Wednesday
- Check some topics that are more valued for me like CPU Profiling

But, I don't know the next steps to **try** help in something.

**Comment by Qard** [comment]
There's lots of room for improvements in the docs. The fact you've read them and still feel this uncertainty is evidence of that. Any help you can provide to make diagnostics more approachable and friendly would be greatly appreciated. I'm happy to answer any questions you might have, here or on the Node.js slack.

You can also join the meetings and follow along, or even as questions there, to build your understanding around what we do and what still needs to be done. :)

**Comment by RafaelGSS** [comment]
> here or on the Node.js slack.

What's the Node.js slack? Maybe can be util to set in README. (If agree, I can set or create a CONTRIBUTORS.md which a set of this information)

> You can also join the meetings and follow along, or even as questions there, to build your understanding around what we do and what still needs to be done. :)

Well, I join in the meetings at youtube live, how I can make questions there? I don't know if the chat is read

**Comment by mmarchini** [comment]
Just as a general reminder, the Slack is not official and also not very active (I guess @Qard is referring to http://www.nodeslackers.com/). The kinda-official chat for the project is #node-dev on freenode (IRC).

> Well, I join in the meetings at youtube live, how I can make questions there? I don't know if the chat is read

You can join the Zoom link (it's open). Let us know in the issue that you will be joining. In theory we read the comments on YouTube, in practice we forget sometimes (last time I didn't look at YT chat thinking it would show on Zoom, so I missed a few questions).

**Comment by Qard** [comment]
Yep, that's what I meant. Not official, but I'm on there so you can ping me there if you have any questions. 🙂

**Comment by mmarchini** [comment]
I guess we could create a chat there for the WG, there's already #core-dev and #build.

**Comment by RafaelGSS** [comment]
I see some issues are migrated from `nodejs/nodejs` to here, this is nice, I'll check and help as I can. Nice work creating the channel, I think that will help most of the people (including me).

**Comment by Qard** [comment]
We don't specifically migrate issues here, but we sometimes open issues here rather than on the core repo because it may involve a longer-running discussion that is mostly just relevant to diagnostics folks. We put it here just so it's easier to keep track of for those longer running projects.

**Comment by RafaelGSS** [comment]
I'm a little confused about where the issues are that are discussed at the meeting on Wednesday, just for a briefing.

Is there an order?

**Comment by Qard** [comment]
The issues can be anywhere. There's an org-wide label "diag-agenda" to add issues to the meeting. As long as the issue continues to have that label it will keep getting added to the meetings.

**Comment by RafaelGSS** [comment]
Ok, thanks!

So, for now where place the feature that `nodejs/diagnostics` are working on? [here](https://github.com/nodejs/diagnostics#current-initiatives) is the only entrypoint for the initiatives? 

May possible to see these initiatives in micro-features that can allow other contributors to working on? (Like small issues of a history)

**Comment by Qard** [comment]
At the individual task level we are less involved. The working group is mostly about discussing the higher-level direction of diagnostics tools in general and individual tasks are left to whomever is interested in working on it. PRs will often @ mention the nodejs/diagnostics team though to notify anyone on the team. If you are interested in joining the team, you can make a PR to this repo, like this: https://github.com/nodejs/diagnostics/pull/363

**Comment by RafaelGSS** [comment]
For anyone who came here through a search or something, the [CONTRIBUITORS](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md) it's a good start and the tips above too.
If you miss something, feel free to open this issue again. Thanks all.
