### ISSUE TITLE
Alternative to Google Drive for meeting notes

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#414]
This was brought up before: Google Docs is suboptimal to write markdown notes. I've been looking at alternatives and https://hackmd.io seems to be a good alternative for us. It is free, it allows collaboration in real time, it has a CLI which allows creating new documents from a template, and it has a self-hosted version if we need to host it by ourselves. I'd like to try it in one of the next meetings (I won't attend this week, but if y'all want to try and share the experience later, go for it :D ).

(this would also fit well with https://github.com/pkgjs/meet if we decide to move meeting creations to there, and it could even help us write an Action to automatically create a PR for meeting notes after our meetings)

**Comment by richardlau** [comment]
There's some related discussion over in https://github.com/nodejs/create-node-meeting-artifacts/issues/72

**Comment by mmarchini** [comment]
I guess more teams are unhappy with Google Docs for notes. I think we can experiment in the Diagnostics repo in a "lightweight" manner: manually create a link to hackmd and edit the meeting issue. We can try this a few times and if folks are happy, we can automate it.

(also, as mentioned before, I'd like to try the new https://github.com/pkgjs/meet action instead of the create artifact script, as it seems more lightweight and easier for folks to contribute to)

**Comment by mmarchini** [comment]
https://github.com/pkgjs/meet added support for HackMD recently. The only thing left for us to be able to adopt it is https://github.com/pkgjs/meet/issues/29.
