### ISSUE TITLE
Deep Dive Suggestion: list subsystems which would benefit from trace points

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#415]
As pointed out by https://github.com/nodejs/diagnostics/issues/82, there are subsystems without trace points even though trace points would be useful. I suggest we have one or more deep dives to:

1. List all subsystems which would benefit from trace points
2. Identify which of those subsystems already have trace points, and whether the existing trace points are comprehensive enough
3. Create a new Tracking Issue with all the remaining subsystems.

**Comment by mhdawson** [comment]
+1
