### ISSUE TITLE
Expand the scope of deep dive meetings

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#417]
For a while we've been focused on using the deep dive meetings to explore the User Journeys documents. Myself and others have suggested other possible deep dive topics recently, as such I would suggest we start "rotating" the deep dive meetings among the topics we have. This might also bring more folks who are interested in participating to these meetings, we just need to decide the topic in advance (which could be done in the meeting issue).

Adding to the wg meeting agenda as this is more of a meta suggestion.

**Comment by mhdawson** [comment]
+1
