### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#424]
Discussed today in the TSC meeting, we would like to experiment with `main` as default branch on some smaller repositories before making any changes to `nodejs/node`. We would keep `master` around for a while as read-only and then use a GitHub Actions to keep those in sync. We could probably do that on other repositories owned by the WG, like `nodejs/llnode` and `nodejs/node-inspect` (would need to ask directly on those repositories though). I'm willing to do the work to make those changes.

Any objections? If not I intend to start working on this in a week or so. cc @nodejs/diagnostics

**Comment by mhdawson** [comment]
@mmarchini I assume we don't want this to go stale.

**Comment by mhdawson** [comment]
Nevermind I see you already removed the label.

**Comment by mhdawson** [comment]
@gireeshpunathil did you volunteer to rename this one in the TSC meeting last week?

**Comment by gireeshpunathil** [comment]
@mhdawson - Yes I did, but I am not sure about its timelines. Didn't we say we rename repos with no PRs (language specific repos for example), then those with few PRs etc, and then learn from those before attempting repos with PRs?

**Comment by gireeshpunathil** [comment]
rename complete: `master` -> `main`.

I will keep this open for few days to see if there are any issues due to this change (for example open PRs etc.)
