### ISSUE TITLE
Node.js  Diagnostics Deep Dive Meeting 2020-08-12

### ISSUE THREAD

**Issue by mhdawson** [nodejs/diagnostics#425]
## Time

**UTC Wed 12-Aug-2020 16:30 (04:30 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 12-Aug-2020 09:30 (09:30 AM) |
| US / Mountain | Wed 12-Aug-2020 10:30 (10:30 AM) |
| US / Central  | Wed 12-Aug-2020 11:30 (11:30 AM) |
| US / Eastern  | Wed 12-Aug-2020 12:30 (12:30 PM) |
| London        | Wed 12-Aug-2020 17:30 (05:30 PM) |
| Amsterdam     | Wed 12-Aug-2020 18:30 (06:30 PM) |
| Moscow        | Wed 12-Aug-2020 19:30 (07:30 PM) |
| Chennai       | Wed 12-Aug-2020 22:00 (10:00 PM) |
| Hangzhou      | Thu 13-Aug-2020 00:30 (12:30 AM) |
| Tokyo         | Thu 13-Aug-2020 01:30 (01:30 AM) |
| Sydney        | Thu 13-Aug-2020 02:30 (02:30 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Diagnostics%20Deep%20Dive+Meeting+2020-08-12&iso=20200812T16
* or http://www.wolframalpha.com/input/?i=04PM+UTC%2C+Aug+12%2C+2020+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1QvdaI5eRFQV24-APpIBcl26RtetXUt_ZdQ64tmmG-Ak/edit>

## Agenda

Extracted from **diag-deepdive-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/diagnostics

* Deep Dive Suggestion: triaging existing long-standing issues [#416](https://github.com/nodejs/diagnostics/issues/416)
* Deep Dive Suggestion: list subsystems which would benefit from trace points [#415](https://github.com/nodejs/diagnostics/issues/415)
* Continue unified hooks discussion [#401](https://github.com/nodejs/diagnostics/issues/401)
* Production readiness guide [#399](https://github.com/nodejs/diagnostics/issues/399)
* Discuss usage and support of eBPF [#386](https://github.com/nodejs/diagnostics/issues/386)
* Diagnostics Best Practices Guide content definition meeting [#254](https://github.com/nodejs/diagnostics/issues/254)
* Diagnostics Channel - Next steps [#180](https://github.com/nodejs/diagnostics/issues/180)

## Invited

* Diagnostics deep dive meetings: @nodejs/diagnostics

## Notes

The agenda comes from issues labelled with `diag-deepdive-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: https://zoom.us/j/466707925
* For those who just want to watch: youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

**Comment by mmarchini** [comment]
These are the options we have to deep dive tomorrow:

* Deep Dive Suggestion: triaging existing long-standing issues #416
* Deep Dive Suggestion: list subsystems which would benefit from trace points #415
* Continue unified hooks discussion #401
* Production readiness guide #399
* Discuss usage and support of eBPF #386
* Diagnostics Best Practices Guide content definition meeting #254
  * Continue [Unexpected Behavior User Journey](https://docs.google.com/document/d/1ivHjgzucnA6QVYyS535EHg-kYQhGJCm9v1Jn5ntSxT8/edit?usp=sharing)
* Diagnostics Channel - Next steps #180

Should we continue/finish the Unexpected Behavior User Journey tomorrow, or do folks want to jump on another topic? I don't think there's much left to discuss on the Unexpected Behavior User Journey.
