### ISSUE TITLE
Meeting times post US DST changes Nov 2020

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#442]
It's that time of the year again. Please answer the following questions, so we can decide if a time change is necessary as well as how to proceed:

1) Does the current time work for you after DST changes (9:30am Pacific Time)?
2) If we change the meeting time, is Wednesday the best day for you?

@nodejs/diagnostics please answer so we can create a Doodle to find a new time if necessary.

**Comment by mhdawson** [comment]
The time in the calendar is ok for you, being on the half hour is a bit awkward as it's more likely to conflict with meetings in both hours that it spans.

**Comment by gireeshpunathil** [comment]
- Current time is 11 PM for for me, which is tight. Earlier, the better
 - No preference for any particular day

**Comment by Qard** [comment]
So shift off the half-hour mark, and earlier? Do we want to do half an hour earlier? Or a full hour and a half earlier? I can definitely do half an hour earlier. An hour and a half...well...I'll make it work, but I suck at mornings. 😆

**Comment by Flarna** [comment]
As mentioned already in similar queries evening slots in CET are hard for me. But I will monitor as I did it in the past.

**Comment by mhdawson** [comment]
Half hour earlier works for me but 1 and 1/2 hours would conflict often with other meetings I have.

**Comment by mmarchini** [comment]
Half an hour earlier works for me too (it's the earliest I can go for a meeting)

**Comment by Qard** [comment]
Do we have enough of a distribution of people that we should start alternating? Would we have more people if, for example, we timed it 12 hours later?

**Comment by mmarchini** [comment]
I think we have 6 active members who have shown interest in joining meeting, on either slot we can get up to 4 members attending I think (that's mostly my guess, might be less for one of the slots).

**Comment by RafaelGSS** [comment]
> we timed it 12 hours later?

For me is a bad time (too late)

**Comment by mhdawson** [comment]
12 hours later would be out for me (middle of the night).

**Comment by mhdawson** [comment]
Maybe we should gather timezones to figure  out what if any overlap there is.

**Comment by legendecas** [comment]
I'm on UTC+8. One and a half hour earlier works for me too.

**Comment by mmarchini** [comment]
I'm on PST (UTC-8)

@nodejs/diagnostics if you would like to join the meetings moving forward, please share your timezone here :)

**Comment by mhdawson** [comment]
I'm in EST (UTC -5)

**Comment by Flarna** [comment]
I'm in CET (UTC+1)

**Comment by Qard** [comment]
UTC-8 also.

**Comment by RafaelGSS** [comment]
I'm in UTC-3.

**Comment by mmarchini** [comment]
Ok, so this is the [current time](https://www.timeanddate.com/worldclock/converter.html?iso=20210106T173000&p1=3922&p2=3910&p3=3919&p4=3903&p5=3917&p6=tz_ist) for everyone based on comments from this thread:

![image](https://user-images.githubusercontent.com/4048656/103805914-1a3c0180-5009-11eb-94dc-8718aa4824eb.png)

We can move it back half an hour, which would look like this:

![image](https://user-images.githubusercontent.com/4048656/103805977-2f189500-5009-11eb-92ba-705e9a686e10.png)

Or one hour:

![image](https://user-images.githubusercontent.com/4048656/103806060-51121780-5009-11eb-893e-052c2871e81b.png)

Or one hour and a half:

![image](https://user-images.githubusercontent.com/4048656/103806023-435c9200-5009-11eb-87b6-3c9ea149455b.png)

I'm fine with all options, I would just ask someone else to host for the last two (moving back one hour or one hour and a half).I checked and 8am PST on Wednesdays doesn't conflict with other Node.js or OpenJSF meetings

Let's use reactions on this issue to vote for a new time @nodejs/diagnostics!

👀 move back half an hour
🚀 move back one hour
❤️ move back one hour and a half

**Comment by gireeshpunathil** [comment]
> I would just ask someone else to host for the last two

I can do that, if we end up picking up one of those

**Comment by Qard** [comment]
I'd like to add 😄 to the votes for "all are fine with me"

**Comment by mmarchini** [comment]
So the results are:

- Move back half an hour: 2 votes
- Move back one hour: 1 vote
- Move back one hour and a half: 2 votes

I think I should've been more clear on the instructions: *please vote on all times you _can_ join the meeting, not your preference*, otherwise it will be hand to find a time that works for most people. I'll give a couple more days in case folks want to update their votes.

**Comment by mmarchini** [comment]
Results are:

![image](https://user-images.githubusercontent.com/4048656/106041758-12640000-6091-11eb-8b52-5caea20b456b.png)

Move back half an hour: 1 votes
Move back one hour: 1 vote
Move back one hour and a half: 2 votes
All are good: 3 votes

With that, moving back one hour and a half is the winner. @mhdawson can you update the calendar (or point me to where I can update it)?

**Comment by mhdawson** [comment]
Is it ok if we also shift 1 week? I have a conflict every week at the new time on the current weeks, but if it was shifted 1 week I'd be able to make it. 

So moved back 1 1/2 hours and shifted a week ok? If so I'd make the next one Feb 10 at 11 ET and then it would be every 2 weeks after that?

**Comment by mmarchini** [comment]
sounds good to me

**Comment by RafaelGSS** [comment]
SGTM

**Comment by Qard** [comment]
I'm fine with shifting a week. 👍

**Comment by mhdawson** [comment]
Calendar updated, closing.
