### ISSUE TITLE
Investigate async continuity on Bluebird

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#446]
Repository: https://github.com/petkaantonov/bluebird
Reference PR: https://github.com/petkaantonov/bluebird/pull/1472

**Comment by Rauno56** [comment]
How to properly test continuity? I looked into context propagation through Bluebird's async resources and everything seemed to propagate fine (even without [asyncHooks](http://bluebirdjs.com/docs/api/promise.config.html) enabled).
cc: @Flarna
