### ISSUE TITLE
Seeking consensus: Move node-inspect into core?

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#459]
Creating issue to add this discussion to our agenda: https://github.com/nodejs/node/discussions/36481.

---

**Update 2020-01-06**

Consensus on the [meeting](https://youtu.be/rPiD0OchmpA) was to merge `node-inspect` into core, deprecate/discontinue the npm package and archive the repository. If anyone have concerns or objections please comment on this issue.

**Comment by mmarchini** [comment]
@nodejs/diagnostics unless there are any objections, we plan to move forward with merging `node-inspect` into core. We plan to share the decision broadly on next Monday 1PM PST.

**Comment by mhdawson** [comment]
Discussed no objections from those in the Diagnostics WG meeting today, and a number of thumbs up so consensus assumed, closing.
