### ISSUE TITLE
async_hooks use case gathering blog post

### ISSUE THREAD

**Issue by Qard** [nodejs/diagnostics#482]
I've updated the draft blog post for gathering async_hooks use cases. How does this look?

https://gist.github.com/Qard/c6998c739f93aaa74abbb2fb9bb331b6

**Comment by RafaelGSS** [comment]
LGTM

**Comment by AndreasMadsen** [comment]
Two more use cases I can easily think of now
* Counting promise objects created
* Detecting server port without monkey patching

**Comment by mhdawson** [comment]
@Quard that updated version looks great to me. I say Ship it.  If you want any help connecting with Rachel at the foundation who usually publishes this for us  just let me know.

**Comment by gireeshpunathil** [comment]
+1 to publishing

**Comment by Qard** [comment]
@AndreasMadsen I added your two use-cases, though I see paths forward for both with `diagnostics_channel` for detecting server ports and `https://github.com/nodejs/node/pull/39283` for counting created promises, so I think we have a path forward already on eliminating the need for async_hooks for those. :)

@mhdawson Yep, help would be appreciated. :)

**Comment by mhdawson** [comment]
@Qard emailed Rachel with you on CC asking for help in getting it published.

**Comment by AndreasMadsen** [comment]
I think "domains" is also a usecase. While already covered by the domain module, there are those who wish to role their own implementation.

**Comment by bmeck** [comment]
I came across https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/ and realized that to implement a nursery properly and detect the state of if pending task are in flight I couldn't reproduce the behavior purely with AsyncLocalStorage, I haven't managed to completely reproduce the API with async_hooks yet but it seems possible just needs to check when all the tasks are destroyed properly

**Comment by RafaelGSS** [comment]
@Qard Is it still a thing?

**Comment by Qard** [comment]
The blog post already happened, so this can be closed.
