### ISSUE TITLE
inactive branches in the repo

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/diagnostics#486]
There are some 18 branches in this repository, may of those with no reasons to be existing. This issue is to track the review and proper action on the same.

**Comment by RafaelGSS** [comment]
![image](https://user-images.githubusercontent.com/26234614/127352368-7c681379-97e2-4386-b68c-1835148d2cbf.png)

Could we enable that?

**Comment by gireeshpunathil** [comment]
> Could we enable that?

enabled, thanks @RafaelGSS .

will keep this open, till we finished clearing up all the existing branches.

**Comment by gireeshpunathil** [comment]
https://github.com/nodejs/diagnostics/branches/stale

@Trott @jasnell @mike-kaufman @hekike @naugtur @mcollina @mmarchini 

I see many stale branches in this repo created by you; apparently all are stale remnants of old PRs and are delete candidates; but it would be great if each of you can confirm on your branches, thanks!

**Comment by gireeshpunathil** [comment]
deleted all the stale branches, closing
