### ISSUE TITLE
Tracing/Diag WG Meeting - 2016-06-01

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#49]
## Time

[UTC Wed 1-June-2016 19:00](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Tracing%2FDiag+WG+Meeting&iso=20160601T19) (1 hour before weekly CTC meeting)
Click for your local time.

San Francisco: Wed 18-May-2016 12:00
New York: Wed 18-May-2016 15:00
Amsterdam: Wed 18-May-2016 21:00
Moscow: Wed 18-May-2016 22:00
Sydney: Thu 19-May-2016 05:00
Tokyo: Thu 19-May-2016 04:00

## Join/Watch

YouTube (view only): https://www.youtube.com/watch?v=Ve3ADadWULU

Hangouts on Air: https://plus.google.com/events/cigjfiuh256pliibr7kfvg2rk2s (https://hangouts.google.com/hangouts/_/hoaevent/AP36tYfB3XA4oawS2lM_fMv6ycUT_-VU7WwlqQYC8gKAkjDlY9wQIw

## Minutes

- Minutes: https://docs.google.com/document/d/13kzR1TPPKZpn7seUuGZlOaM3wU8kCpgxqW1WdUaSaWU
- Previous minutes: https://github.com/nodejs/tracing-wg/blob/master/wg-meetings/2016-01-26.md (see #38 too).

## Agenda

- TRACE_EVENT - Google's plans and how Node can build on them (@ofrobots)
- Trace module - @joshgav's proposal (#50) - why and what.
- Chrome Debugging Protocol and v8_inspector ([nodejs/node#6792](https://github.com/nodejs/node/pull/6792)) (@ofrobots or other from Google)
    - What it brings to Node and the community now and in the future.
    - How can the Diagnostics WG utilize it?
- AsyncWrap - update from @trevnorris
- Expanding scope to Diagnostics WG

**Comment by trevnorris** [comment]
I'll be to this one. By then the AsyncWrap EP will be more flushed out so may be worth some discussion.

**Comment by joshgav** [comment]
I've updated the time based on the outcome of the Doodle. We'll meet at 12pm US Pacific this Wednesday (6/1). That's right before the weekly CTC meeting. :)

Following is an updated proposed agenda. @ofrobots, can you confirm this looks good to you? Thanks!

- TRACE_EVENT - Google's plans and how Node can build on them (@ofrobots)
- Trace module - @joshgav's proposal (#50) - why and what.
- Chrome Debugging Protocol and v8_inspector ([nodejs/node#6792](https://github.com/nodejs/node/pull/6792)) (@ofrobots or other from Google)
    - What it brings to Node and the community now and in the future.
    - How can the Diagnostics WG utilize it?
- AsyncWrap - update from @trevnorris
- Expanding scope to Diagnostics WG

**Comment by ofrobots** [comment]
@joshgav Myself and a few other folks should be able to join and talk about trace_event and v8_inspector.

**Comment by TheAlphaNerd** [comment]
I would like to join the call I'd that is alright

**Comment by AndreasMadsen** [comment]
@TheAlphaNerd shouldn't be a problem. The Hangout is open and there is usually enough room.

**Comment by jasonLaster** [comment]
Hi, I'd like to join and listen in.  The Firefox DevTools team is investigating node debugging.

**Comment by joshgav** [comment]
As long as Hangouts can handle it, I believe anyone is welcome to attend.

**Comment by joshgav** [comment]
Reminder that we're on for today (Wednesday, 6/1) at [12pm US Pacific](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Tracing%2FDiag+WG+Meeting&iso=20160601T19). Hangouts on Air allows at least 10 people with video, possibly more; I've added the view-only YouTube link above for overflow or for those who just want to listen. Thanks!

**Comment by ofrobots** [comment]
The Hangouts on air link doesn't seem to be correct.

**Comment by joshgav** [comment]
Hmm, I'm on and clicked Start. What am I missing? Thanks!

**Comment by pmuellr** [comment]
Here are the instructions I use - https://github.com/nodejs/node/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event

**Comment by AndreasMadsen** [comment]
We can watch the video from the link, but not join the hangout.

**Comment by joshgav** [comment]
https://hangouts.google.com/hangouts/_/hoaevent/AP36tYfB3XA4oawS2lM_fMv6ycUT_-VU7WwlqQYC8gKAkjDlY9wQIw?hl=en&authuser=0

**Comment by watson** [comment]
I had hotel wifi issues, but seems like we've reached the maximum attendees on-air

**Comment by joshgav** [comment]
Thanks to all those who joined and apologies for the early hiccups. I'll process the materials and notes shortly and post here when I do.

**Comment by joshgav** [comment]
Wrapping up this meeting:

- Opened #52 and #53 to continue discussions on CDP profile for Node and Trace Events in Node respectively.
- Opened #54 with meeting notes.
- Moved recording to Node Foundation YouTube channel: https://www.youtube.com/watch?v=Ve3ADadWULU
- Continued discussion on 'Diagnostics WG' here: https://github.com/nodejs/tracing-wg/issues/46#issuecomment-223412876

Next meeting will be Wednesday 7/6 at 12 pm US Pacific. In the meantime discussions will continue in GitHub.

Once #54 is closed this issue will be closed too.

Thanks everyone for your contributions!
