### ISSUE TITLE
is it possible to identify synchronous executed functions?

### ISSUE THREAD

**Issue by helio-frota** [nodejs/diagnostics#495]
When looking at flamegraph tools we can see some executed functions.

I was thinking if is it possible to:

a) To see all the executed functions without native modules
or
b) To see all the executed functions using native modules

c) to use async_hooks +  the results of a) or b) above to make a diff between all the sync and async executed functions.

If something like that is possible to do, then it will probably help to answer this: 

https://github.com/nodejs/diagnostics/issues/439
https://docs.google.com/document/d/1Yip9zU_8axfZwN-clGMeoNWVYHZPfBjepLV3Ur2JjwA/edit#
`TODO: Investigate how to identify synchronous calls on running processes`

Let's imagine an app is made of 20 functions, even if all the 20 were not executed if we are able to identify 4 of 13 making a difference for example 4 sync and 9 async, I believe that is really helpful to try to answer that item.

please let me know if that makes any sense :+1:

**Comment by RafaelGSS** [comment]
> Does make sense to try to combine the results from this tool + results from async_hooks?

I don't think so. If I understood correctly the objective is to identify sync functions that are blocking the event-loop, so, I don't think that `async_hooks` has something very useful to it.

I believe that `CPU profiling` is the best way to identify which function is doing more work in the whole context.

I may not have understood what you want to achieve from that.

**Comment by helio-frota** [comment]
> If I understood correctly the objective is to identify sync functions that are blocking the event-loop,

@RafaelGSS  exactly, my initial thoughts don't make any sense, it would be good to update the document.

from:
`TODO: Investigate how to identify synchronous calls on running processes`
to
`TODO: Investigate how to identify sync functions that are blocking the event-loop on running processes`

Then close this issue :+1: 

thanks

**Comment by RafaelGSS** [comment]
> TODO: Investigate how to identify sync functions that are blocking the event-loop on running processes

I believe CPU Profiling is common sense in this case.

**Comment by Qard** [comment]
Specific correlation between the two is difficult, but you can track event loop blocking time and time spent executing a given function, then just loosely correlate them based on time. You won't know X set of async tasks were delayed because of Y function taking too long, but you _will_ know that Y function frequently blocks and would _likely_ be a leading cause of async task delays.

**Comment by helio-frota** [comment]
@Qard thank you for that extra information :+1:  that clarifies more to me in relation to my first question and the subsequent comment.

Also, I've updated the document with a suggestion based on @RafaelGSS response, that is why I decided to close this issue.
