### ISSUE TITLE
meeting time, again

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/diagnostics#507]
the current meeting time is not the best, but worked for most of us.

it has the drawback that it conflicts with the TSC meeting once in a while.

the solutions was to move this or that, temporarily. not a great way moving forward.

**Comment by Qard** [comment]
I've said before that rotation might be worth considering. The current time doesn't work super great for me either as I usually have to skip another meeting to make it to the WG meeting. Any earlier though and I'd still be sleeping...

**Comment by RafaelGSS** [comment]
I'm fine moving 1h after.

**Comment by gireeshpunathil** [comment]
in the last meeting, a consensus was arrived to move this meeting to Tue same time (11 ET). This at least avoids the frequent conflict with the TSC, while a better time still needs to be derived at, and that discussion is still not concluded.

If anyone has concerns on the new date please let me know in a week's time.

**Comment by Qard** [comment]
Fine with me. It conflicts with another meeting, but that time slot conflicts with meetings every day of the week for me so... 🤷

**Comment by gireeshpunathil** [comment]
one week has passed with no objections. Meeting day will be moved to Tuesdays instead of Wednesdays. (No change in meeting time as of now, as it would require a wider discussion, so can be picked up later.)

**Comment by gireeshpunathil** [comment]
reopening this, to now visit the time. (we have fixed the day of the week, but the current time seems to be inconvenience to few members)

**Comment by tony-go** [comment]
Hey @gireeshpunathil 👋 

I filled the doodle 🙌

**Comment by gireeshpunathil** [comment]
here is what I find: if we go with meetings at 2 different time slots, here are the possibilities, based on the current doodle: (all times in UTC)

possibility one:

```
slot 1: 3.30 PM (covers 4/7 members)
slot 2: 10.30 PM (covers 3/7 members)
```

with at least one person (@bmeck) not on their best selections.

possibility two:

```
slot 1: 7.30 PM (coveres 4/7 members)
slot 2: either 
9.30 AM (coveres 4/7 memebrs)
or
3.30 PM (coveres 4/7) members
```

this approach will give us maximum members in each, but will leave out at least one person (@mmarchini )

**Comment by Qard** [comment]
I would prefer not to leave out anyone interested in attending. May also be worth reaching out to people that have attended in the past and stopped due to our current time slot being unsuitable for them.

**Comment by gireeshpunathil** [comment]
@legendecas - IIRC, you had difficulty in attending the meeting due to time conflicts. If that is the case, would you mind filling out the doodle linked [here](https://github.com/nodejs/diagnostics/issues/507#issuecomment-1019181518) ?

**Comment by legendecas** [comment]
@gireeshpunathil thank you for reminding me, I've filled out the doodle.

**Comment by gireeshpunathil** [comment]
ok, with @legendecas 's data coming in, we have more converging slots:

```
slot 1:  3.30 PM (covers 5/8 members with "yes if need-be" for @bmeck)
slot 2: 10.30 PM (covers the other 3/8 members)
```

**Comment by gireeshpunathil** [comment]
setup the new timing in effect. few highlights:
 - 3.30 PM UTC for slot 1
 -  10.30 PM UTC for slot 2 (few instances are clashing with other Node.js meetings, so those will commence at 11 PM UTC)
 - a slot will get exactly one meeting in a month
 - next week we start with slot 1
