### ISSUE TITLE
Document async_hooks types purposes

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/diagnostics#511]
I'm working on a profiler tool that uses `async_hooks` to trace events, however, I'm a bit lost to understand the reason for each type of resource.

In the documentation, we have the list of types: https://nodejs.org/api/async_hooks.html#type but there is no description of each event.

Not sure where I should open this issue, if you think that it's more suitable at the node repository feel free to move.

**Comment by RafaelGSS** [comment]
Currently, there are 2 suggestions:

- Generate the types of documentation based on the definition (we aren't sure if we want to it)
- Improve the documentation
  - Update the documentation to explicitly says to not rely too much on the types, because it might change arbitrarily.

**Comment by tony-go** [comment]
Hi @RafaelGSS 👋 

Do you plan to raise a pull request for the second point?

I can do it otherwise :) Let me know ^^

**Comment by RafaelGSS** [comment]
Go ahead :)
