### ISSUE TITLE
Subset of CDP as profile for Node.js tools and VMs

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#52]
> **NOTE**: Background reading and resources at the end of this post.

[CDP](https://chromedevtools.github.io/debugger-protocol-viewer/) groups functionality into Domains containing Methods, Events, and Types. The domains and members supported by a given runtime/debug target can be specified in a `protocol.json` file, ideally retrievable dynamically by the debugger at a `/json/protocol` endpoint on the debugee. Examples and discussion:

- [Blink](https://src.chromium.org/blink/trunk/Source/devtools/protocol.json)
- [Edge](https://github.com/Microsoft/edge-diagnostics-adapter/blob/0beea6055435e041a249a30cf9fa97b3699428f5/protocol.json) (see [Microsoft/edge-diagnostics-adapter#24](https://github.com/Microsoft/edge-diagnostics-adapter/pull/24))
- [cyrus-and/chrome-remote-interface#10](https://github.com/cyrus-and/chrome-remote-interface/issues/10), [cyrus-and/chrome-remote-interface#24](https://github.com/cyrus-and/chrome-remote-interface/issues/24)

V8's currently-supported Domains are listed [here](https://chromedevtools.github.io/debugger-protocol-viewer/v8/).

**For Node to fully support CDP we must implement and specify which Domains and other members Node supports**, likely in a `protocol.json` file, and likely starting from those supported by V8 and the inspector agent. We could call this the Node "profile" for CDP.

This was discussed in #49's meeting.

- [ ] This issue is to track progress on creating such a profile for Node.

---

### Background and Resources

> Please suggest more in the thread and I'll add them.

- CDP == [Chrome Debugging Protocol](https://chromedevtools.github.io/debugger-protocol-viewer/)
- Google's [help page on CDP](https://developer.chrome.com/devtools/docs/debugger-protocol)
- @auchenberg's [list of related specs](http://remotedebug.org/specifications/)

**Comment by TheAlphaNerd** [comment]
thanks for putting this together @joshgav I'll go through the reading list today / tomorrow

**Comment by bnoordhuis** [comment]
nodejs/node#7470 suggests linking/forwarding to a public URL but I'd be okay with embedding protocol.json in the binary.  Then the user doesn't need an active network connection.

[v8_inspector/js_protocol.json ](https://github.com/nodejs/node/blob/bbf3838/deps/v8_inspector/platform/v8_inspector/js_protocol.json) when minified and compressed is about 8.5 kB, which seems acceptable to me.

**Comment by NathanaelA** [comment]
+1 to embedding.  Internet isn't always reliable...

**Comment by auchenberg** [comment]
I favor expending the HTTP endpoint to add `/json/protocol` endpoint, which services the bundled `protocol.json` directly from Node. We already added support for this in the [edge-diagnostics-adapter](https://github.com/Microsoft/edge-diagnostics-adapter), and have worked the community to get support added in clients like [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface/issues/24).

For now we don't have a formel spec for the HTTP endpoint exposed by various runtimes, but we can easily sketch one together as the mount of HTTP methods are fairly limited.

**Comment by bnoordhuis** [comment]
https://github.com/nodejs/node/pull/7491

**Comment by joshgav** [comment]
In our meeting last week - #64 - we decided to close this and go with what's provided within v8_inspector for now. If a more constrained profile is needed later we'll evaluate then.

@auchenberg started a [chart](http://compatibility.remotedebug.org/) to track compatibility across platforms, which helps with this too.
