### ISSUE TITLE
Add using clinic/heap-profiler step

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/diagnostics#521]
Once clinicjs has released the [heap-profiler](https://clinicjs.org/heapprofiler/) support I think that makes sense to add it to a step inside [memory](https://github.com/nodejs/diagnostics/tree/main/documentation/memory) documentation.

**Comment by mmarchini** [comment]
Have we listed any third party tool so far?

**Comment by RafaelGSS** [comment]
Not exactly, there is a mention to `@mmarchini/observe`.
