### ISSUE TITLE
Move Slack channel to OpenJS Foundation server

### ISSUE THREAD

**Issue by mmarchini** [nodejs/diagnostics#527]
The OpenJS Foundation has a paid [Slack server](https://openjs-foundation.slack.com/) available for projects to use ([invite](https://slack-invite.openjsf.org/)), which means we have access to more features as well as infinite chat history. Does anyone oppose to moving the #diagnostics-wg channel from NodeSlackers to OpenJS Foundation Slack?

**Comment by mhdawson** [comment]
+1 to moving from me.

**Comment by RafaelGSS** [comment]
+1

**Comment by gireeshpunathil** [comment]
+1 from me

**Comment by tony-go** [comment]
+1 for me too 🎉

**Comment by RafaelGSS** [comment]
The channel is: `#node-diagnostics-wg`? Just joined.
