### ISSUE TITLE
re-assess the tooling list and their maturity status

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/diagnostics#532]
https://github.com/nodejs/node/blob/a199387f045aa55b58c6d2e52bb69bf32c9d3d5e/doc/contributing/diagnostic-tooling-support-tiers.md

the list of tools and their support tier level are not reviewed updated for some time. tools might have moved on with capabilities / stabilities. this issue is to track the re-assessment activity.
 - pick up one or more tools in the list
 -  discuss / examine the latest art on those
 -  make a decision as to whether their current slot is good, or need a change
 - apply the change, otherwise identify / document any actions out of the discussion

**Comment by tony-go** [comment]
I thought it could be nice having `trace_gc` in the list, so I opened a PR. Let me know if you prefer having a discussion here or there.

**Comment by gireeshpunathil** [comment]
this is being worked upon actively.

**Comment by tony-go** [comment]
Awesome work!
