### ISSUE TITLE
Re-evaluate eBPF Tracing tool tier-list

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/diagnostics#535]
As discussed in #533. I'm adding this item to the agenda to evaluate its tier or remove it from the tier-list document.

**Comment by kvakil** [comment]
I put an example of one eBPF thing I've done in #569, if you're interested.

**Comment by RafaelGSS** [comment]
I think we can close it. The support was removed and a discussion about how to bring it back is available on https://github.com/nodejs/node/issues/44550
