### ISSUE TITLE
Re-evaluate `heapdump`	in the tools tier-list

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/diagnostics#548]
As discussed in https://github.com/nodejs/diagnostics/issues/533. I'm adding this item to the agenda to evaluate its tier or remove it from the tier-list document.

**Comment by RafaelGSS** [comment]
No information. No module `node-heapdump` in npm.

**Comment by richardlau** [comment]
> No information. No module `node-heapdump` in npm.

It's https://www.npmjs.com/package/heapdump.

**Comment by tony-go** [comment]
Thanks, @richardlau 🙌 

Do you think we should let it like this at the moment and rediscuss it in the next instance?

IMO we could delete it anyway as the `v8` API already offers this. 

Fun fact, by scrolling down into the web, I found this post from Bryan English: https://dev.to/bengl/node-js-heap-dumps-in-2021-5akm where `heapdump` is mentioned as the "old-way" 👍

**Comment by richardlau** [comment]
> Thanks, @richardlau 🙌
> 
> Do you think we should let it like this at the moment and rediscuss it in the next instance?
> 
> IMO we could delete it anyway as the `v8` API already offers this.

I think that sounds reasonable. 

> Fun fact, by scrolling down into the web, I found this post from Bryan English: https://dev.to/bengl/node-js-heap-dumps-in-2021-5akm where `heapdump` is mentioned as the "old-way" 👍

cc FYI @bengl 🙂
