### ISSUE TITLE
Re-evaluate `--trace-gc` in the tools tier-list

### ISSUE THREAD

**Issue by tony-go** [nodejs/diagnostics#554]
Hi, Diag family 👋 

As mentioned in issue #532, I proposed to add `--trace-gc` to the tier list. Here is the [pull request](https://github.com/nodejs/node/pull/42346). You'll find there the discussion we had with @gireeshpunathil and the final statement we had [here](https://github.com/nodejs/node/pull/42346#issuecomment-1075391019).

Then [another PR](https://github.com/nodejs/node/pull/42471) was raised to add integration tests between Node.Js and `--trace-gc` (v8).

IMO, the remaining pillar is the documentation. We already have an [API reference documentation](https://nodejs.org/api/v8.html#v8setflagsfromstringflags). Maybe should we consider creating a guide? 

As a Node.Js newcomer, I'd like to see a guide about: "how diagnosis a memory leak" and `--trace-gc` could be a protagonist there. Feel free to share any thoughts you have on this ^^ I'll probably raise a draft PR in the following days to expose the tree structure of this guide.

With love ❤️

**Comment by tony-go** [comment]
I started working on a guide a few days ago but nothing strong enough to share it on a PR. 

https://www.twitch.tv/videos/1459580297

**Comment by RafaelGSS** [comment]
@tony-go it was added?

**Comment by tony-go** [comment]
yes
