### ISSUE TITLE
Marketing request

### ISSUE THREAD

**Issue by gtewallace** [nodejs/diagnostics#56]
Apologies in advance if this is the wrong place for this request. I plan to post this as well on postmortem

The Node.js Foundation is putting together a presentation for general use by the community to unequivocally establish Node's place as enterprise-ready. The intended audience is Node.js devs inside enterprises who may not be using Node as much as possible. The preso, ideally, will equip them with the material they need to convince their peers and management.

One of the things still missing is a slide (preferably a single slide, but could be multiple if needed) to summarize the performance/performance tuning/debugging considerations for enterprises running Node.js at scale.

Obviously we're not going to cover the topic in any detail in a single slide. Rather, the goal is to highlight the key elements of the topic and share the tools/resources available and work underway in Core and in the community on the topic.

Is this something this group could help with? 

Thanks in advance!

**Comment by joshgav** [comment]
There's a list of capabilities and some available tools in #47; you can browse it at my fork: https://github.com/joshgav/tracing-wg/tree/foundation till we merge it hopefully soon.

Work underway includes #52 (CDP), #53 (Tracing), and #29 (AsyncWrap).

Do you need help designing the slide?

**Comment by gtewallace** [comment]
@joshgav thanks.

I'll read the stuff you pointed to and lyk if I need help on slide design

Thanks again! 

Greg

**Comment by joshgav** [comment]
Thanks Greg, good luck! Closing now.
