### ISSUE TITLE
Collab Summit session?

### ISSUE THREAD

**Issue by Qard** [nodejs/diagnostics#563]
Do we have any people going to the Collab Summit? Should we set a time for an in-person session there?

**Comment by tony-go** [comment]
> Do we have any people going to the Collab Summit? Should we set a time for an in-person session there?

Hey @Qard 👋🏼

Hope you're doing well :)

Maybe a silly question but what is the Collab Submit?

**Comment by Qard** [comment]
There's a gathering of Node.js collaborators at the upcoming OpenJS World conf in Austin in early June to catch up and talk about Node.js core things. Sounds like there might also be another around NodeConf EU maybe, but not confirmed yet.

**Comment by tony-go** [comment]
Thanks for sharing @Qard 🙌 

It will be a bit hard to be in Austin for June, but If another round is confirmed at NodeConf EU, I could consider it ^^

**Comment by gireeshpunathil** [comment]
done, closing

**Comment by RafaelGSS** [comment]
How was it? Any news on the diagnostics side?
