### ISSUE TITLE
llnode - Current Status 

### ISSUE THREAD

**Issue by No9** [nodejs/diagnostics#576]
As per [Diagnostics Meeting 2022-07-26](https://github.com/nodejs/diagnostics/pull/575/commits/e503cf13f4bd6adf2241bce1f18a21b3cc3dc46f#diff-d0fda06c79c7e1a2e9bb8618f888d0ef209b10e1f9732f3f9fac2ba264d9ee07R25) 
This issue tracks work on llnode

### Discussion 
Support Matrix - https://github.com/nodejs/llnode/issues/405

### Work In Progress

- User Journeys for llnode - https://github.com/nodejs/llnode/issues/401 @tony-go 
- Discussion on reducing features in tool to make it more maintainable is commencing. 
  https://github.com/nodejs/llnode/issues/405
  This will be followed up in later calls.
- Coordinate the announcement of support reestablished in the tool tier list https://github.com/nodejs/node/blob/main/doc/contributing/diagnostic-tooling-support-tiers.md 
- Next call 2022-08-23
 
### Backlog 
- Medium term debug_helper is being evaluated as a possible replacement for some llnode capabilities
  Discussion around how debug_helper is integrated and additional requirements will be documented as discussion continues @kvakil to open issue as work starts.

### Work Completed 

- Establish core dump tools meeting to discuss roadmap/strategy/keyissues - https://github.com/nodejs/llnode/issues/402 Moved to main diagnostics
- CI is now back to green https://github.com/nodejs/llnode/actions/runs/2721848039
- 2FA Enabled on npm for publishing
- Support for later versions of llvm to 14 -  https://github.com/nodejs/llnode/pull/389/commits @No9 
- V8 Changes to support node v16-v18 - https://github.com/nodejs/llnode/issues/399 Initial patch submitted this week and scope of further work needs to be defined. @kvakil

**Comment by RafaelGSS** [comment]
Meeting scheduled to next DWG
