### ISSUE TITLE
doc: define writing practices/rules

### ISSUE THREAD

**Issue by tony-go** [nodejs/diagnostics#578]
During the review of pull request #572, I thought that it could be interesting to have our list of practices/rules when it comes to writing documentation.

It should not be necessary strict rules. It could be an excellent way to onboard new writers easily.

Here is an example of two rules I can extract from my discussion with @RafaelGSS:
- Simplify code examples as much as you can - for example, prefer using a basic script over an HTTP server.
- Avoid first-person communication within the documentation

Let me know WDYT.

**Comment by RafaelGSS** [comment]
This is a good reference: https://developers.google.com/tech-writing
