### ISSUE TITLE
support: llnode project settings and diagnostics team access

### ISSUE THREAD

**Issue by No9** [nodejs/diagnostics#579]
Hey All,
Can I get access to the project settings on llnode?
I would like to be able to add an npm auth secret to the project so we can automate the publishing of llnode [similar to the corepack approach](https://github.com/nodejs/corepack/blob/main/.github/workflows/publish.yml)

Also can I be added to the @nodejs/diagnostics working group so I get the meeting notifications? Missed the last one.
Thanks

**Comment by gireeshpunathil** [comment]
@No9 - added you to the WG.

For the other request,  @mhdawson may be best placed.

**Comment by mhdawson** [comment]
@No9 can you PR yourself into the members on https://github.com/nodejs/diagnostics. Once that lands I can add you to the right group.

**Comment by mhdawson** [comment]
@No9 do you know have access to the settings?  I change your role in the project.

**Comment by No9** [comment]
Perfect Thank you @gireeshpunathil @mhdawson 😎
