### ISSUE TITLE
Discuss Possible Agenda Items for Collab Summit 

### ISSUE THREAD

**Issue by No9** [nodejs/diagnostics#583]
Noting @Qard 's idea that we should have diagnostics sessions at the collaboration summit.
Opening this issue to put it onto the next DWG session.

**Comment by RafaelGSS** [comment]
Hopefully, I'll be there

**Comment by tony-go** [comment]
Me too!

**Comment by RafaelGSS** [comment]
1. Adding eBPF Support
2. Next years of `llnode`
3. Investigate our current tutorial list (https://github.com/nodejs/diagnostics/issues/502)

**Comment by Qard** [comment]
I submitted a session proposal for the collab summit. https://github.com/openjs-foundation/summit/issues/330

**Comment by RafaelGSS** [comment]
Closing as done.
