### ISSUE TITLE
Diagnostics WG Meeting - 2016-07-13

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#60]
## Time

UTC Wed 13-July-2016 19:00 (1 hour before weekly CTC meeting)
[Click][] for your local time.

[Click]: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Tracing%2FDiag+WG+Meeting&iso=20160713T19

San Francisco: Wed 13-July-2016 12:00
New York: Wed 13-July-2016 15:00
Amsterdam: Wed 13-July-2016 21:00
Moscow: Wed 13-July-2016 22:00
Sydney: Thu 14-July-2016 05:00
Tokyo: Thu 14-July-2016 04:00

## Join/Watch

YouTube: https://youtu.be/QQ65Y4dfv84

## Minutes

- Minutes: https://docs.google.com/document/d/1rq2VXKb4gj4RBTI1ZfAhRXmMDgO7LDCcLiDeI0FlErI
- Previous minutes: https://github.com/nodejs/tracing-wg/blob/master/wg-meetings/2016-06-01.md

## Agenda

- AsyncWrap - https://github.com/nodejs/node-eps/pull/18
- Trace system for Node - update from @matthewloring and @ofrobots (see #53, #50)
- Inspector Protocol (https://github.com/nodejs/node/issues/7393, #52, #59)
- APM Summit (#58)
- Topics from APM Summit thread? - ES6 module patching, trace system, F2F meetings

/cc @nodejs/diagnostics

**Comment by joshgav** [comment]
Agenda subject to this discussion. I think we should start with AsyncWrap since we missed it last time. @trevnorris @AndreasMadsen can you present status and next actions and lead a discussion for 10-15 minutes?

I'm working on something related to the Inspector stuff, will share soon.

**Comment by AndreasMadsen** [comment]
@trevnorris should do the status update this time. I haven't been following the EPS that closely, since the initial discussion was mostly reserved to CTC members. Besides the EP, the only thing that is new is:
* uid are now doubles
* backport to 4.x

On future work that is discussion worth, I think it is mostly about getting handle context bugs fixed. https://github.com/nodejs/diagnostics/issues/29 contains an overview of that. The status is (my opinions)
* **Microtask**: difficult, but @ofrobots @jeisinger are optimistic about getting visibility from v8.
* **timers**: should be relatively easy
* **addon modules integration**: very difficult, at least without major breaking changes to how `MakeCallback` work.

**Comment by ofrobots** [comment]
I am away during the week of July 4, so I won't be able to make it.

**Comment by joshgav** [comment]
@ofrobots - good point. Would you be able to attend on 7/13? Would others also prefer to postpone a week?

I'm +1 :)

**Comment by TheAlphaNerd** [comment]
I'm +1 on postponing a week

**Comment by pmuellr** [comment]
Makes sense, w/ July 4th holiday

**Comment by joshgav** [comment]
Great, July 13 it is. Thanks!

**Comment by joshgav** [comment]
@nodejs/diagnostics: **reminder: meeting is this Wednesday July 13 at 12pm Pacific**

@ofrobots @matthewloring - can you discuss the trace system? https://github.com/nodejs/diagnostics/issues/53
@pavelfeldman - can you discuss progress on inspector integration? https://github.com/nodejs/diagnostics/issues/52
@trevnorris - do you want to discuss AsyncWrap? /cc @bnoordhuis

I'd like to briefly discuss potential goals of https://github.com/nodejs/node/issues/7393.

**Comment by matthewloring** [comment]
We'll be there to discuss the tracing controller.

**Comment by trevnorris** [comment]
@joshgav Not sure I have anything to discuss, but I'll be happy to take any questions.

**Comment by AndreasMadsen** [comment]
@trevnorris I think this will be an good opportunity to get an update on the v8 microtask hooks and for you to explain the `MakeCallback` solution.

**Comment by rvagg** [comment]
@Fishrock123 has an update about the microtask hooks .. not great news afaik

**Comment by Jeff-Lewis** [comment]
I'm not sure if this means anything but [v8 ticket 4643 MicrotaskQueue lacking introspection APIs](https://bugs.chromium.org/p/v8/issues/detail?id=4643) was just assigned last night.

**Comment by jmealo** [comment]
If anyone from the diagnostics group could provide some guidance on getting debugging/inspector support back into pl/v8 it would be much appreciated!

https://github.com/plv8/plv8/issues/131

**Comment by ofrobots** [comment]
@jmealo: At this point, v8_inspector is the best bet for implementing debugging for V8; the older JSON based protocol has been deprecated for ~2 years now. From skimming the issue it seems like plv8 might be on V8 ~4.3 which would be unfortunately too old (you need atleast V8 5.0+ for v8_inspector to work).

To use v8_inspector in your project, here's a rough outline of what you will have to do:

1. Get v8_inspector from https://github.com/pavelfeldman/v8_inspector. We are keeping this repo as a convenient location for integration with Node.js. You can pick this code up directly from upstream Chromium too if you prefer. Note that at some point in the near-ish future this code will be merged directly into V8 and you won't have to pick it up externally.
2. A websockets implementation that would serve your debugger endpoint. You should look at `src/inspector_agent.cc` in Node.js as an example to see how this is wired up.

**Comment by jmealo** [comment]
@ofrobots Thanks for the reply. The master branch is at 5.1.281.14. I haven't coded any serious C++ but I can take a look at it. I'm trying to get an implementation plan and do the footwork at the very least; so this was very helpful.

**Comment by joshgav** [comment]
Would be great if I could get a couple LGTMs on the [notes from this meeting](https://github.com/nodejs/diagnostics/pull/63). Thanks!
