### ISSUE TITLE
Monthly meeting suggestion

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/diagnostics#602]
I would like to propose changing our meeting schedule from bi-weekly to monthly meetings. The reason is that very often we don't have much to discuss in that short timeframe. 

Of the last 5 meetings, 4 were canceled:

- https://github.com/nodejs/diagnostics/issues/601
- https://github.com/nodejs/diagnostics/issues/600
- https://github.com/nodejs/diagnostics/issues/595
- https://github.com/nodejs/diagnostics/issues/594

Hopefully, this group will get more traction over the year, but until we have many items on the agenda, I believe it's reasonable to meet once per month. What do you guys think about it? @nodejs/diagnostics

**Comment by gireeshpunathil** [comment]
+1

**Comment by Qard** [comment]
It _does_ tend to slow down around the holidays, but also the group has just not been super active lately so turning the meeting frequency down a bit could be reasonable. I think we should do something about expanding the group to get more activity happening though. I don't think it's inactive for a lack of things to do, just a lack of people doing them. 🤔

**Comment by RafaelGSS** [comment]
@Qard Absolutely. I think we could clean up the README and perhaps set up new goals. Pretty much the same as we are doing for Security (https://github.com/nodejs/security-wg/issues/846). But, until we have this issue and people engaging, I'm still +1 to monthly meetings.

**Comment by mhdawson** [comment]
+1

**Comment by Qard** [comment]
To be clear, I'm +1 to this. I just _also_ think we should do something to get the activity back up. 😅

**Comment by tony-go** [comment]
> To be clear, I'm +1 to this. I just _also_ think we should do something to get the activity back up. 😅

+1

**Comment by RafaelGSS** [comment]
@mhdawson could you do it for us?
