### ISSUE TITLE
Issue for Diagnostics project related news ?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/diagnostics#614]
The next-10 team is working to get more visibility of project related news as outlined in https://github.com/nodejs/node/blob/main/doc/contributing/sharing-project-news.md

I'd meant to bring up in recent Diagnostic team meetings but have either forgotten to do so or missed the meeting. This is to add to the agenda so we discuss.

If the team would like to participate I'm happy to create the issue and PR into the doc that has the links for the issues across all of the teams.

**Comment by Qard** [comment]
My [AsyncLocalStorage rewrite](https://github.com/nodejs/node/pull/48528) is getting close to ready. That might be worth talking about soon. 😄

**Comment by mhdawson** [comment]
Created issue to post news to in https://github.com/nodejs/diagnostics/issues/619
PR to add to list in collaborator documentation - https://github.com/nodejs/node/pull/49306/
PR to add to news feeder list - https://github.com/nodejs/nodejs-news-feeder/pull/35

**Comment by mhdawson** [comment]
Closing as complete.  Please post any news worthy info to https://github.com/nodejs/diagnostics/issues/619
