### ISSUE TITLE
Q: Should we skip August Diag WG meeting?

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#62]
Hi all - we scheduled the August Diag WG meeting for 8/3. However, we just met a couple weeks ago and I haven't even uploaded those notes yet (I will soon). I also don't believe we have anything pressing to discuss. Finally, summer (in Northern Hemisphere) plans might effect people's schedules this month.

So I propose we skip August and meet next on Wednesday September 7. Thoughts?

/cc @nodejs/diagnostics

**Comment by joshgav** [comment]
We skipped August and I'll schedule our next meeting soon, I think we should target Wed Sept 14. Will work on agenda and open an issue shortly. Thanks!

**Comment by mhdawson** [comment]
Sep 14 is the day before Node interactive.  People might be travelling ?
