### ISSUE TITLE
Transfer of import-in-the-middle

### ISSUE THREAD

**Issue by Qard** [nodejs/diagnostics#634]
We are proposing to donate the import-in-the-middle project to the Node.js organization to better open it up to shared collaboration with other APM vendors. There's an admin repo issue for this already, creating this one for our own reference and to add it to the working group agenda.

https://github.com/nodejs/admin/issues/858

**Comment by RafaelGSS** [comment]
+1

**Comment by mhdawson** [comment]
+1 from me

**Comment by bengl** [comment]
The current active contributor base (which we hope will grow!) for `import-in-the-middle` consists mainly of:

@bengl
@trentm
@jsumners-nr
@Qard

It would be good if these folks were involved in maintainership going forward. Under the assumption that this WG will assume maintainership of import-in-the-middle, should they all be members of (or seek membership in) this WG?

**Comment by jsumners-nr** [comment]
I am currently discussing with the Node team at New Relic to determine what we are up for (I don't see why we wouldn't want to be maintainers, but still need to go through the process).

**Comment by Qard** [comment]
No particular time commitment expected or anything like that, of course. Just want to make sure the keys to the project aren't held exclusively by Datadog. Other vendors sometimes encounter issues to be fixed and shouldn't be blocked on someone else landing and releasing those changes, especially given we're all depending on this project for our own products customers are paying for and expecting quick responses to issues on.

**Comment by bengl** [comment]
@nodejs/diagnostics please note the questions I asked in nodejs/admin#858. In particular, it would be great the first question (i.e. is maintainership going to be handled by this WG? or some new team perhaps?) can be answered. I'm happy to initiate the transfer after that.

**Comment by RafaelGSS** [comment]
We have discussed it a bit in today's meeting (https://github.com/nodejs/diagnostics/pull/637/) an it seems there are a significant number of contributors who would like to support the maintenance of this module as well as participate in other working group initiatives and that ends the meeting

Recording: https://www.youtube.com/watch?v=Q6snsixbu9o&ab_channel=node.js

**Comment by timfish** [comment]
Is the transfer still in the works? 

Having spent the last month living `import-in-the-middle` and helping with the roll-out at Sentry, I feel I mostly understand the challenges now and would love to be a maintainer 😁

**Comment by Qard** [comment]
It is, and we'd love to have your help! I'll check where we're at with the transfer tomorrow. 🙂

**Comment by Qard** [comment]
The transfer will be a major topic of the next WG call next Thursday. Please join us for the call, if you can! It is my _hope_ that we can have the transfer done before then and the discussion can be focused on direction for the project, but there may be additional migration-related concerns that will need to be dealt with in the call too.

It is my goal to use the Diagnostics WG as a home for a few things we (Datadog) currently own but would prefer ownership by the Node.js project, so I would like to bring this working group back to a healthy state where we have a few active projects to work on. 😄

**Comment by AbhiPrasad** [comment]
First release of `import-in-the-middle` under the Node.js org: https://www.npmjs.com/package/import-in-the-middle/v/1.9.0 🎉

Thanks everyone for your help with the transfer! I think we can close this issue now.
