### ISSUE TITLE
New meeting day/time?

### ISSUE THREAD

**Issue by Qard** [nodejs/diagnostics#638]
The current time is always in conflict for me (for _anyone_ working on Node.js at Datadog, actually) and I've also heard from others the time is not great. Can we adjust the day/time of the meetings? What days/times are free for other folks?

My Wednesdays through Fridays are mostly free in the time range that is good for EU overlap. Mondays and Tuesdays are full of meetings for me. Do we want to try same time on another day? Or even slightly earlier would be fine too. Much earlier though and we lose accessibility for folks in San Francisco/Seattle/Vancouver.

Also, I am able to host the meetings now, so I can ensure we keep things running more consistently going forward. 😄 

cc @nodejs/diagnostics

**Comment by jsumners-nr** [comment]
Most of my company meetings happen on Tuesdays. But I am almost always open prior to 11:00 EDT. On days other than Tuesday, I have a stand-up at 13:30 EDT every day, but not much else.

**Comment by tony-go** [comment]
> The current time is always in conflict for me

Same for me. This is why I struggle to attend meetings these days.

Wednesday and Thursday work better for me.

**Comment by RafaelGSS** [comment]
cc: @santigimeno @trevnorris

**Comment by mhdawson** [comment]
The current time always seems to conflict for me as well.

**Comment by AbhiPrasad** [comment]
Anytime Wednesday, Thursday, Friday works well with me. Note that the OpenTelemetry JavaScript SIG is at 12 PM EST on Wednesday, so ideally we avoid conflicting with that to encourage contributors between the two organizations to attend meetings.

**Comment by Qard** [comment]
Does Wednesday at 11AM EST work then? That'd put it one hour before the OTel SIG, so people can block out that time together. Makes sense that many folks would want to attend both meetings.

Any objections to Wed 11AM EST? That's 8AM PST, 5PM CET--on the edge of too early for west coast AMER and may overlap with EMEA dinner time, but I think that's likely the most _balanced_ discomfort we're going to get with a single time slot.

**Comment by legendecas** [comment]
11AM EST would conflict with Node.js TSC meeting for every two weeks

**Comment by Qard** [comment]
It looks like the TSC slot shifts every two weeks, so we could fit it in the timing where it _doesn't_ overlap?

**Comment by Qard** [comment]
Actually, that overlaps with next-10...so maybe Thursday would be better? Could do 12PM EST/9AM PST/6PM CET to also not overlap with security or release WGs.

Any objections to Thursday at 12PM EST/9AM PST/6PM CET, or would overlapping with next-10 be a preferable time slot for most people?

**Comment by jsumners-nr** [comment]
> Any objections to Thursday at 12PM EST/

This works best for me.

**Comment by legendecas** [comment]
Thursday at 12PM EST looks good. I think Node.js zoom would not allow overlapping meetings.

**Comment by mhdawson** [comment]
Correct that we cannot have two meetings at the same time

**Comment by Qard** [comment]
Thursday at 12PM EST it is. Who has calendar-adjusting powers? @mhdawson Can you update that and I'll take over running those events again?

**Comment by tony-go** [comment]
> Any objections to Thursday at 12PM EST/

It works for me.

**Comment by mhdawson** [comment]
@Qard moved in the calendar. Next meeting is on Thursday the 27th at 12 ET.

**Comment by Qard** [comment]
Thanks! 🙇🏻

**Comment by legendecas** [comment]
Closing since the new time is set.
