### ISSUE TITLE
Add zoom link to recurring calendar invite

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/diagnostics#645]
> [!NOTE]  
> This is cleanup from https://github.com/nodejs/admin/issues/923

People interacting with the WG via https://nodejs.org/calendar are met with not enough information to join.

![image](https://github.com/user-attachments/assets/b2bf7329-329a-4fc1-8a0c-dda8095df2ec)

And they won't necessarily know to look for issues like https://github.com/nodejs/diagnostics/issues/644

Further https://nodejs.org/en/about/get-involved/events only displays events with a zoom link.

To resolve all of this, please add https://zoom.us/j/466707925 (which I think is a durable enough link, taken from the above issue) to the calendar.

**Comment by Qard** [comment]
This was fixed once before but appears to have been reverted, probably when the calendar got deleted and recreated a while ago.

I don't think many people in here have permissions to edit the calendar events. Maybe @mhdawson?

**Comment by mhdawson** [comment]
Added
