### ISSUE TITLE
What's the official name for the new protocol introduced by v8_inspector?

### ISSUE THREAD

**Issue by auchenberg** [nodejs/diagnostics#66]
What's the official name for the new protocol introduced by v8_inspector?

I've seen **V8 Inspector Protocol** and **Chrome Debugging Protocol** being used interchangeably several places.

**Comment by joshgav** [comment]
/cc @ofrobots @pavelfeldman

No official name here in Node as far as I'm aware. In code (https://github.com/v8/v8/tree/master/src/inspector) it's sometimes referred to as "inspector protocol" but I don't think that matters.

**Comment by joshgav** [comment]
Closing now, if others have input feel free to re-open.
