### ISSUE TITLE
Updating this WG's description in the WG directory

### ISSUE THREAD

**Issue by nebrius** [nodejs/diagnostics#69]
There is a [list of working groups](https://github.com/nodejs/node/blob/master/WORKING_GROUPS.md#tracing) that still lists this working group as the Tracing Working Group, and the list of responsibilities seems to be very tracing-specific still. Looking at this groups README, it wasn't readily apparent to me what this working groups responsibilities are, and you probably don't want me to come up with the list ;-).

Can someone submit a PR to that file with the updated name and an updated list of responsibilities? Bonus points: list the responsibilities on in this repo's README too.

**Comment by joshgav** [comment]
I hope to do some housekeeping here once I'm back from vacation next week. Will add this to the list unless someone else jumps in first. #46 has all the info.
