### ISSUE TITLE
Diag WG Meeting - November 2016

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#70]
## Date/Time

Wednesday November 9, 3:00 PM US Pacific

[Click][] for your local time.

Note that US Daylight Savings Time ends on Sunday November 6.

[Click]: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Diag+WG+Meeting&iso=20161109T23

## Join/Watch

If you are primarily observing please use the YouTube channel; Hangouts limits the number of connections. You can interact from YouTube via chat.

- YouTube: https://www.youtube.com/watch?v=JGRpLZzWqss
- Hangouts: https://hangouts.google.com/hangouts/_/ytl/2rFWXYtntZeYKBCl3SBiNDtr3Le13lZ5CFdh7RvkXPs=?eid=100598160817214911030

## Minutes

- Minutes: https://docs.google.com/document/d/1651e1fY-cvlpN7gk3Jtp92BCig7KILShJ96RiIbIdlU
- Previous minutes: https://docs.google.com/document/d/1ksAjU0ypopwZ70kzMOq7XSHrIh20wsOlcFicGbkNly8

## Agenda

- Trace event support for Node.js [[node#9304](https://github.com/nodejs/node/pull/9304)]
- Bringing node-inspect into the fold (debugger for inspector protocol) [[diagnostics#67](https://github.com/nodejs/diagnostics/issues/67)]
- Membership in the Diagnostics WG
- Agenda for Diagnostics WG at Node Interactive and Collaboration Summit [[summit#30](https://github.com/nodejs/summit/issues/30)]

---

/cc @nodejs/diagnostics @nodejs/post-mortem

**Comment by watson** [comment]
I'm flying to Tokyo on the 3rd for NodeFest, so the timezone is probably gonna make me skip this one

**Comment by joshgav** [comment]
Anyone else who plans to attend please respond to [the Doodle](http://doodle.com/poll/vhxh9gafmrbqtms5) in the next 24 hours, at which point we'll finalize.

Top selections at the moment seem to be:
* [this Wednesday, 11/2 at 12pm US Pacific](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Diag+WG+Meeting&iso=20161102T19)
* [next Wednesday, 11/9 at 3pm US Pacific](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Diag+WG+Meeting&iso=20161109T22)

**Comment by joshgav** [comment]
The vote is for [next Wednesday, 11/9 at 3pm US Pacific](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Diag+WG+Meeting&iso=20161109T22) so updating the original post accordingly.

Also added part of agenda:

- Trace event support for Node.js [[node#9304](https://github.com/nodejs/node/pull/9304)]
- Updated debugger for v8_inspector protocol [[#67](https://github.com/nodejs/diagnostics/issues/67)]
- Agenda for Diagnostics WG at Node Interactive and Collaboration Summit [[summit#30](https://github.com/nodejs/summit/issues/30)]

**Comment by watson** [comment]
I'll most likely not be able to make it as it's 6am in Tokyo at that time. But it depends on my jetlag ;)

**Comment by AndreasMadsen** [comment]
It's 11pm in Denmark and I have class early morning the following day, so I won't attend either.

**Comment by AndreasMadsen** [comment]
Agenda/Task:

* Add @Fishrock123 to @nodejs/diagnostics team.

**Comment by Fishrock123** [comment]
(I can technically do that myself, but feel free to do the formalities.)

**Comment by AndreasMadsen** [comment]
@Fishrock123 oh, please do it yourself then. It always takes a while for us, because we don't have the privileges.

**Comment by Fishrock123** [comment]
I did the thing.

**Comment by mhdawson** [comment]
I there an issue with the hangouts link or is it just me.  It tells me I'm not authorized to start the video call

**Comment by mhdawson** [comment]
Looks like I've got the wrong time.  I think the link that converts the to your local time was off by an hour for me.

**Comment by joshgav** [comment]
Fixed, Daylight Savings Time confusion. Talk to you in about an hour.

**Comment by jkrems** [comment]
Is the streaming issue from last time fixed (youtube shows "live stream is starting soon")

**Comment by jkrems** [comment]
Works now for me.

**Comment by joshgav** [comment]
Notes at https://github.com/nodejs/diagnostics/pull/74. Thanks!
