### ISSUE TITLE
Add Fishrock123 to the Diagnostics WG

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/diagnostics#72]
I'm quite involved with async_hooks, and interested in nodereport.

I'm not super into a lot of tracing types but general diagnostics is much more interesting.

**Comment by AndreasMadsen** [comment]
LGTM. Normally people create a PR ([example](https://github.com/nodejs/diagnostics/pull/28)).

/cc @joshgav

**Comment by AndreasMadsen** [comment]
Welcome
