### ISSUE TITLE
question about asyncwrap

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/diagnostics#78]
I saw that async-wrap made it into Node.js

https://github.com/nodejs/node/blob/master/src/async-wrap.cc

is there any documentation about how to use it?
sorry for spam question, but don't know who to ask.

**Comment by AndreasMadsen** [comment]
It has been there for about 2 years I think. Currently it is an undocumented API, which means that it is completely unsupported. So expect bugs, pain, and an API that will change under your feet in a single patch update.

But yes we do have documentation for the undocumented API :) – https://github.com/nodejs/diagnostics/tree/master/tracing/AsyncWrap

The API is actually guaranteed to change drastically, the official API will be called `async-hooks`.
* enhancements proposal: https://github.com/nodejs/node-eps/pull/18
* work in progress pull request: https://github.com/nodejs/node/pull/8531

But regardless of it being an undocumented API, we would still like to hear your thoughts.

If you have specific question to the current API feel free to open a new issue. Questions to the upcoming API should be put in the enhancements proposal.
