### ISSUE TITLE
[trace_event] implementing a listener system

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#81]
Trace Controller writes traces to a buffer and eventually a file on disk. Currently reading that file is the only way to review or be notified that an event occurred.

This issue is to discuss **implementing a listener system** in Node's and/or V8's Trace Controller.

Diagnostics subsystems and libraries would benefit from being able to listen/subscribe to a stream of trace events to better monitor, respond to, and report on changing conditions in an app. Also, a generic listen capability makes Trace Events a more appropriate target for other trace data too, such as the proposed [network trace][] provider. 

@jasongin's [JS API Proposal][] also discusses a [trace listener API][].

[network trace]: https://github.com/nodejs/diagnostics/issues/75
[JS API Proposal]: https://github.com/nodejs/node-eps/pull/48
[trace listener API]: https://github.com/jasongin/node-eps/blob/81cf5a6c28da9f5cbdf6f92c47094bcfacd9c2d0/00X-tracing.md#3-tracing-listener-apis

**Comment by jasnell** [comment]
Need to determine the specific use cases for this and just how granular it needs to be. I, for one, would like to use this to selectively emit timing data for various categories using the perf API but this kind of listener could be a major firehose and bottleneck.

**Comment by jasnell** [comment]
This can be closed
