### ISSUE TITLE
[trace_event] C wrappers over macros

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#83]
Should we wrap the raw macros from [trace_event.h][] with a simpler C (or C++) API? The current set of macros can be hard to understand.

This impacts how to add trace points to core (#82).

[trace_event.h]: https://github.com/nodejs/node/blob/master/src/tracing/trace_event.h

**Comment by gireeshpunathil** [comment]
should this remain open? [ I am trying to chase dormant issues to closure ]
