### ISSUE TITLE
Diag WG Meeting - 2017-02

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#85]
## Date/Time

Thursday [Feb 23 2100 UTC][Click] (1pm US Pacific)

It's helpful if you give this post a :+1: or :-1: so we know you'd like to attend.

[Click]: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Diag+WG+Meeting&iso=20170223T21

## Join/Watch

If you are only observing please use the YouTube channel; Hangouts limits the number of connections.

- Watch on YouTube: http://youtu.be/ccwZGCJ3tC4
- Participate on Hangouts: https://hangouts.google.com/hangouts/_/ytl/ItG6jcVC7JeStHp44T_Sl2NHMMFk7wWeztcQS0sDITE=?eid=100598160817214911030&hl=en_US&authuser=0

> **If the Hangouts link isn't working for you** try removing the query string (the `?` and all which follows).

## Minutes

- Minutes: https://docs.google.com/document/d/1Rt6yFAgCSmBFYpWDd9JL90f8BWG-AhhiJ7gOluRo-XQ
- Previous minutes: https://github.com/nodejs/diagnostics/blob/master/wg-meetings/2016-01-19.md

## Agenda

**Issues tagged `diag-agenda` across the nodejs GitHub organization.**

### nodejs/node

* proposal: programmatically expose the V8 inspector URL [#11496](https://github.com/nodejs/node/issues/11496)
* inspector: make `debug` an alias for `inspect` [#11441](https://github.com/nodejs/node/pull/11441)
* Switch the CLI debugger to V8 inspector [#11421](https://github.com/nodejs/node/issues/11421)
* \[WIP\] inspector: hint text update [#11207](https://github.com/nodejs/node/pull/11207)
* What will Domain be replaced with? [#10843](https://github.com/nodejs/node/issues/10843)
* src: separate trace_event_common from trace_event [#10628](https://github.com/nodejs/node/pull/10628)
* async_hooks initial implementation [#8531](https://github.com/nodejs/node/pull/8531)

### nodejs/diagnostics

* wg: nominating jkrems [#87](https://github.com/nodejs/diagnostics/pull/87)
* Request to join Diagnostics WG [#86](https://github.com/nodejs/diagnostics/pull/86)
* \[trace\] tracking issue; out of experimental [#84](https://github.com/nodejs/diagnostics/issues/84)
* AsyncWrap issues - overview [#29](https://github.com/nodejs/diagnostics/issues/29)

### nodejs/nodejs.org

* guides: debugging getting started guide [#1131](https://github.com/nodejs/nodejs.org/pull/1131)
* blog: diag wg update and --debug deprecation [nodejs.org#1156](https://github.com/nodejs/nodejs.org/pull/1156)

---

/cc @nodejs/diagnostics @nodejs/post-mortem

**Comment by misterdjules** [comment]
The agenda isn't specific enough to determine what will be discussed. For instance, what specific topics related to post-mortem will be discussed?

**Comment by naugtur** [comment]
I watched a recording of the previous meeting and it seems this post-mortem point is a continuation as there wasn't enough time left for covering what the WG is up to.

Also, there's more details in the minutes googledoc linked.

**Comment by joshgav** [comment]
@misterdjules @naugtur the agenda in the OP at the moment is just a list of domains we cover here, specific agenda items still need to be added.

We've also added the [diag-wg-agenda](https://github.com/nodejs/diagnostics/labels/diag-wg-agenda) label in this repo to tag specific issues or PRs for discussion.

**Comment by misterdjules** [comment]
> the agenda in the OP at the moment is just a list of domains we cover here, specific agenda items still need to be added.

Ok, then that's a bit misleading, as in its current form the agenda seems to be complete. I think it would help to mention that's not the case.

**Comment by AndreasMadsen** [comment]
Add @naugtur to the @nodejs/diagnostics team.

**Comment by watson** [comment]
@joshgav did we settle on a date?

**Comment by joshgav** [comment]
Final time: Thursday [Feb 23 2100 UTC][Click] (1pm US Pacific) (next Thursday)

[Click]: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Diag+WG+Meeting&iso=20170223T21

**Comment by joshgav** [comment]
We've also added the `diag-agenda` label in this repo and some others. Could you all please tag issues you'd like to discuss in the meeting? Thanks!

**Comment by watson** [comment]
Changing my RSVP to tentative. Something unfortunately came up that I have to go to on that day. It might finish in time for me to attend though, but not sure

**Comment by joshgav** [comment]
I've added the `diag-agenda` label over the past couple weeks wherever I had permissions across the nodejs org and tagged some issues to get us started. Following is generated by Rod's [node-meeting-agenda](https://github.com/rvagg/node-meeting-agenda) script; I'll add it to the OP and notes too.


### nodejs/node

* proposal: programmatically expose the V8 inspector URL [#11496](https://github.com/nodejs/node/issues/11496)
* inspector: make `debug` an alias for `inspect` [#11441](https://github.com/nodejs/node/pull/11441)
* Switch the CLI debugger to V8 inspector [#11421](https://github.com/nodejs/node/issues/11421)
* \[WIP\] inspector: hint text update [#11207](https://github.com/nodejs/node/pull/11207)
* What will Domain be replaced with? [#10843](https://github.com/nodejs/node/issues/10843)
* src: separate trace_event_common from trace_event [#10628](https://github.com/nodejs/node/pull/10628)
* async_hooks initial implementation [#8531](https://github.com/nodejs/node/pull/8531)

### nodejs/diagnostics

* wg: nominating jkrems [#87](https://github.com/nodejs/diagnostics/pull/87)
* \[trace\] tracking issue; out of experimental [#84](https://github.com/nodejs/diagnostics/issues/84)
* AsyncWrap issues - overview [#29](https://github.com/nodejs/diagnostics/issues/29)

### nodejs/nodejs.org

* guides: debugging getting started guide [#1131](https://github.com/nodejs/nodejs.org/pull/1131)

**Comment by joshgav** [comment]
One more just added:

* blog: diag wg update and --debug deprecation [nodejs.org#1156](https://github.com/nodejs/nodejs.org/pull/1156)

**Comment by joshgav** [comment]
Notes in https://github.com/nodejs/diagnostics/pull/88.

Hangouts worked fine, but strangely there wasn't an option to broadcast, so no recording this month. Might have been because the scheduled time in YouTube was incorrect, I'll double-check that next time.

Thank you!

**Comment by naugtur** [comment]
Another thing I noticed about the hangout - it seems I could only join using a paid Google account, not my private one.

**Comment by mhdawson** [comment]
Sorry I missed it, meant to be there.  As for the recording I've had lots of problems. Sometimes option is there sometimes not.

**Comment by mhdawson** [comment]
From reading the notes, I agree with Ali that node-report should be in core.  Looking forward to the discussion in the Issue Richard's going to open.
