### ISSUE TITLE
Diag WG Meeting - 2017-03

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#89]
## Date/Time

Thursday [Mar 23 2100 UTC][Click] (click for your local time)

It's helpful if you give this post a :+1: or :-1: so we know you'd like to attend.

[Click]: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Diag+WG+Meeting&iso=20170323T21

## Join/Watch

If you are only observing please use the YouTube channel; Hangouts limits the number of connections.

- Watch on YouTube: <https://www.youtube.com/watch?v=_-9ygz6yOBo>
- Participate on Hangouts: <https://hangouts.google.com/hangouts/_/ytl/5ABV3Mgcnwe1eTgeD8GM8PaqUzMicAtYDSpy7v44NvI=>

> **If the Hangouts link isn't working for you** try removing the query string (the `?` and all which follows).

## Minutes

- Minutes: <https://docs.google.com/document/d/1lhy1H37hsbjKljY0XYr5tt2nO5Xbo54Vf_PjBuIjvOA>- Previous minutes: <https://docs.google.com/document/d/1Rt6yFAgCSmBFYpWDd9JL90f8BWG-AhhiJ7gOluRo-XQ>

## Agenda

**Issues tagged `diag-agenda` across the nodejs GitHub organization.**

### nodejs/node

* inspector: make `debug` an alias for `inspect` [#11441](https://github.com/nodejs/node/pull/11441)
* debug: activate inspector with _debugProcess [#11431](https://github.com/nodejs/node/pull/11431)
* Switch the CLI debugger to V8 inspector [#11421](https://github.com/nodejs/node/issues/11421)
* \[WIP\] inspector: hint text update [#11207](https://github.com/nodejs/node/pull/11207)
* What will Domain be replaced with? [#10843](https://github.com/nodejs/node/issues/10843)

### nodejs/diagnostics

* fixed monthly schedule for Diag WG meetings [#90](https://github.com/nodejs/diagnostics/issues/90)
* \[trace\] tracking issue [#84](https://github.com/nodejs/diagnostics/issues/84)
* \[async_hooks\] tracking issue [#29](https://github.com/nodejs/diagnostics/issues/29)

/cc @nodejs/diagnostics @nodejs/post-mortem

**Comment by joshgav** [comment]
I went ahead and slotted this in for next week Thursday at 2100 UTC but let's discuss if we should open a Doodle or choose a different time. I also opened #90 to discuss a fixed schedule for the future. Thanks!

**Comment by joshgav** [comment]
@nodejs/diagnostics @nodejs/post-mortem reminder that we're meeting today at [2100 UTC](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Diag+WG+Meeting&iso=20170323T21), 2pm US Pacific.

Refreshed the agenda just now. Talk to you soon!

**Comment by joshgav** [comment]
!! Please use this updated Hangouts link: https://hangouts.google.com/hangouts/_/ytl/5ABV3Mgcnwe1eTgeD8GM8PaqUzMicAtYDSpy7v44NvI=?eid=100598160817214911030&hl=en_US&authuser=0

**Comment by jkrems** [comment]
Getting a 403 for that new link.

**Comment by naugtur** [comment]
works for me

**Comment by ofrobots** [comment]
403 here as well

**Comment by naugtur** [comment]
try without query string `?...` maybe

**Comment by jkrems** [comment]
Yeah, removing the query string fixed it.

**Comment by naugtur** [comment]
updated youtube link for watchers: https://www.youtube.com/watch?v=_-9ygz6yOBo

**Comment by joshgav** [comment]
notes in https://github.com/nodejs/diagnostics/pull/93. Thanks!
