### ISSUE TITLE
fixed monthly schedule for Diag WG meetings

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#90]
I think it would help consistency and make participation simpler if we start having a fixed monthly time and date for Diag WG meetings as is done for some other Node.js groups. What do you all think?

An initial proposal: Last Thursday of each month at [1900 UTC][time-link] (click to see your regional time), which would be one hour *before* the bi-weekly TSC meeting.

NB: Agenda for meetings is set by the `diag-agenda` label across the Node.js repos.

[time-link]: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Diag+WG+Meeting&iso=20170323T19

/cc @nodejs/diagnostics @nodejs/post-mortem

**Comment by jkrems** [comment]
Works for me.

P.S.: For people like me who can't handle timezones - it's 11am PT outside of DST:

```
> TZ="America/Los_Angeles" node -p "new Date('2017-01-01T19:00:00Z').toString()"
Sun Jan 01 2017 11:00:00 GMT-0800 (PST)

> TZ="America/Los_Angeles" node -p "new Date('2017-06-01T19:00:00Z').toString()"
Thu Jun 01 2017 12:00:00 GMT-0700 (PDT)
```

**Comment by joshgav** [comment]
In meeting yesterday I accidentally said *after* the TSC meeting, but here I proposed *before* :woman_shrugging:. To clarify, I propose the following for the Diag WG monthly meeting and unless there are objections we'll run with this next month. I'll also add to the [Node.js calendar](https://calendar.google.com/calendar/embed?src=kap.co_i17i575te0aes6kaanfjr2e4hs%40group.calendar.google.com). Thanks!

**Before last TSC meeting each month at [1900 UTC][time-link] (click to see your regional time).**

[time-link]: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Diag+WG+Meeting&iso=20170323T19

**Comment by watson** [comment]
I just noticed that next month it's not the last Thursday of the month, just so people don't get it wrong 😃

**Comment by watson** [comment]
Oh, will the meeting time move with DST btw? In most of Europe DST starts in a few days, but the time is specified in UTC which doesn't follow DST - so technically that means that the meeting will be one our later? Or will we move the time to compensate for DST?

**Comment by joshgav** [comment]
We ended up going with the last Thursday of the month in April. Perhaps we should stick with that?

**Comment by mike-kaufman** [comment]
I think this can be closed now given the new set of meetings & bi-weekly cadence.  Please reactivate if not the case.
