### ISSUE TITLE
[docs] requesting comments on diagnostics-howtos project

### ISSUE THREAD

**Issue by naugtur** [nodejs/diagnostics#92]
I'm working on creating a more accessible introduction to diagnostics.

https://github.com/naugtur/node-diagnostics-howtos

The flame graphs section is complete in terms of content (not to be confused with finished). I'm planning to extract the exercise into a separate repository or publish i to npm in a more terminal-interactive form.

Looking forward to any comments, especially on where to put this once ready, what should be included and overall direction/goals.

**Comment by AndreasMadsen** [comment]
Personally, I would love to get some more technical documentation in this repo, as long as it doesn't get to userland specific. As in, don't document an external tool but external references are fine.

Eventually, we can consider moving it to gh-pages and finally to nodejs.org under some more advanced documentation branch.

**Comment by rnchamberlain** [comment]
Suggest doc goes here: https://nodejs.org/en/docs/guides/ if it's foundation content. As above, links only if it's about external/3rd party tools.

**Comment by rnchamberlain** [comment]
Earlier PR - added more information about llnode: https://github.com/naugtur/node-diagnostics-howtos/pull/1

New PR adding information for node-report: https://github.com/naugtur/node-diagnostics-howtos/pull/2

**Comment by gireeshpunathil** [comment]
should this remain open? [ I am trying to chase dormant issues to closure ]

**Comment by naugtur** [comment]
I intended to keep adding more of those articles to the guides, but there's been this https://github.com/nodejs/diagnostics/issues/254 going on while I couldn't participate (fatherly duties)

I'm happy to help when I get time. 

Let's close this and converge on the other issue.
