### ISSUE TITLE
async_hooks: MakeCallback addition and ABI stability

### ISSUE THREAD

**Issue by AndreasMadsen** [nodejs/diagnostics#99]
The `async_hooks` EPS specify a [native API](https://github.com/nodejs/node-eps/blob/master/006-asynchooks-api.md) which is useful/necessary to make native add-ons work with AsyncHooks.

The current concern regarding getting `async_hooks` in node v8.x are:
1. Is the [native API](https://github.com/nodejs/node-eps/blob/master/006-asynchooks-api.md) going to get implemented before the release of node v8.x?
2. If not, can we implement it in a semver-minor release afterward?

I have requested a few time that someone should take care of this, but there don't appear to be any interest, thus I'm going to assume that "1." is not going to happen.

Regarding "2." the `async_hooks` EPS is mostly additional API that is either not implemented or not exposed. The one major exception (and please check, I don't have a deep understanding of C++) is that `MakeCallback` gets an additional parameter (`double id`).

```c++
// An API specific to emit before/after callbacks is unnecessary because
// MakeCallback will automatically call them for you.
// TODO(trevnorris): There should be a final optional parameter of
// "double triggerId" that's needed so async_hooks.triggerId() returns the
// correct value.
v8::MaybeLocal<v8::Value> node::MakeCallback(v8::Isolate* isolate,
                                             v8::Local<v8::Object> recv,
                                             v8::Local<v8::Function> callback,
                                             int argc,
                                             v8::Local<v8::Value>* argv,
                                             double id);
```

**question:** is this going to be ABI breaking? For example, will the normal `node::MakeCallback` symbol change?

If the additional `node::MakeCallback` for `async_hooks` is going to be a problem, I would suggest that we create a placeholder function until we have time to implement it, such that the ABI break happens in node v8.x.

/cc @trevnorris @thlorenz @addaleax @Fishrock123 @refack @nodejs/diagnostics

**Comment by addaleax** [comment]
Don’t worry, we can just add an almost identical overload with the extra parameter and make the old method wrap around that, no ABI breakage necessary. :)

I think I mentioned I can take a look at it, but I’m not a hundred percent sure I get the semantics right. I’ll try to take a stab at it later today.

**Comment by AndreasMadsen** [comment]
> Don’t worry, we can just add an almost identical overload with the extra parameter and make the old method wrap around that, no ABI breakage necessary. :)

Yeah, I was not sure if adding an overload would cause a symbol change for the existing function. I'm happy to hear that it don't.
